"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OpportunityState = exports.OpportunityNotes = exports.OpportunityLineNotes = exports.OpportunityLineDocuments = exports.OpportunityDocuments = void 0;
var OpportunityDocuments_1 = require("./OpportunityDocuments");
exports.OpportunityDocuments = OpportunityDocuments_1.default;
var OpportunityLineDocuments_1 = require("./OpportunityLineDocuments");
exports.OpportunityLineDocuments = OpportunityLineDocuments_1.default;
var OpportunityLineNotes_1 = require("./OpportunityLineNotes");
exports.OpportunityLineNotes = OpportunityLineNotes_1.default;
var OpportunityNotes_1 = require("./OpportunityNotes");
exports.OpportunityNotes = OpportunityNotes_1.default;
var OpportunityState_1 = require("./OpportunityState");
exports.OpportunityState = OpportunityState_1.default;
