"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TemplatePreview = TemplatePreview;
var react_1 = require("@carbon/react");
var react_2 = require("react");
var context_1 = require("./context");
var PREVIEW_DEBOUNCE_MS = 500;
/**
 * Server-rendered preview. The PDF is generated by the `.preview` route (Node,
 * where @react-pdf/renderer's Buffer/stream deps exist) and shown in the
 * browser's native PDF viewer via an iframe. No client-side react-pdf, no
 * polyfills, and the preview is byte-identical to the real document route.
 */
function TemplatePreview(_a) {
    var _this = this;
    var previewPath = _a.previewPath;
    var _b = (0, context_1.useDocumentTemplate)(), blocks = _b.blocks, theme = _b.theme, settings = _b.settings, headerSectionId = _b.headerSectionId, footerSectionId = _b.footerSectionId, headerConfig = _b.headerConfig, previewId = _b.previewId;
    var previewNonce = (0, context_1.useEditorStore)(function (s) { return s.previewNonce; });
    var labelSizeId = (0, context_1.useEditorStore)(function (s) { return s.labelSizeId; });
    var _c = (0, react_2.useState)(null), url = _c[0], setUrl = _c[1];
    var _d = (0, react_2.useState)(true), isLoading = _d[0], setIsLoading = _d[1];
    var urlRef = (0, react_2.useRef)(null);
    // biome-ignore lint/correctness/useExhaustiveDependencies: `previewNonce` is a manual retrigger — bumped by the toolbar refresh button to re-run the fetch.
    (0, react_2.useEffect)(function () {
        var controller = new AbortController();
        var handle = setTimeout(function () { return __awaiter(_this, void 0, void 0, function () {
            var formData, response, blob, nextUrl, error_1;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        setIsLoading(true);
                        _a.label = 1;
                    case 1:
                        _a.trys.push([1, 4, 5, 6]);
                        formData = new FormData();
                        formData.append("blocks", JSON.stringify(blocks));
                        formData.append("theme", JSON.stringify(theme));
                        formData.append("settings", JSON.stringify(settings));
                        formData.append("headerSectionId", headerSectionId !== null && headerSectionId !== void 0 ? headerSectionId : "");
                        formData.append("footerSectionId", footerSectionId !== null && footerSectionId !== void 0 ? footerSectionId : "");
                        formData.append("headerConfig", JSON.stringify(headerConfig));
                        formData.append("labelSizeId", labelSizeId);
                        if (previewId)
                            formData.append("previewId", previewId);
                        return [4 /*yield*/, fetch(previewPath, {
                                method: "post",
                                body: formData,
                                signal: controller.signal
                            })];
                    case 2:
                        response = _a.sent();
                        if (!response.ok)
                            return [2 /*return*/];
                        return [4 /*yield*/, response.blob()];
                    case 3:
                        blob = _a.sent();
                        nextUrl = URL.createObjectURL(blob);
                        if (urlRef.current)
                            URL.revokeObjectURL(urlRef.current);
                        urlRef.current = nextUrl;
                        setUrl(nextUrl);
                        return [3 /*break*/, 6];
                    case 4:
                        error_1 = _a.sent();
                        if (!controller.signal.aborted)
                            console.error(error_1);
                        return [3 /*break*/, 6];
                    case 5:
                        if (!controller.signal.aborted)
                            setIsLoading(false);
                        return [7 /*endfinally*/];
                    case 6: return [2 /*return*/];
                }
            });
        }); }, PREVIEW_DEBOUNCE_MS);
        return function () {
            controller.abort();
            clearTimeout(handle);
        };
        // `headerConfig` is a dep so logo/header edits (sent in the payload and
        // applied server-side) retrigger a fresh render without a save round-trip.
    }, [
        blocks,
        theme,
        settings,
        headerSectionId,
        footerSectionId,
        headerConfig,
        previewId,
        previewPath,
        previewNonce,
        labelSizeId
    ]);
    // Revoke the last object URL on unmount.
    (0, react_2.useEffect)(function () { return function () {
        if (urlRef.current)
            URL.revokeObjectURL(urlRef.current);
    }; }, []);
    return (<div className="relative mx-auto flex h-full w-full max-w-3xl flex-col overflow-hidden rounded-lg border bg-card shadow-sm">
      {url && (<iframe key={url} src={url} title="Document preview" className="block h-full w-full grow border-none"/>)}
      {isLoading && (<div className="absolute inset-0 flex items-center justify-center bg-background/60 backdrop-blur-[1px]">
          <react_1.Spinner className="size-6"/>
        </div>)}
    </div>);
}
