// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  getTrialBalance,
  getFinancialStatementBalances,
  getCompaniesInGroup,
  deleteAccount,
  deletePaymentTerm,
  getAccount,
  getAccounts,
  getAccountsList,
  getGroupAccounts,
  getBaseCurrency,
  getChartOfAccounts,
  getCurrency,
  getCurrencyByCode,
  getCurrencies,
  getCurrenciesList,
  getCurrentAccountingPeriod,
  getDefaultAccounts,
  getFiscalYearSettings,
  getPaymentTerm,
  getPaymentTerms,
  getPaymentTermsList,
  updateDefaultBalanceSheetAccounts,
  updateDefaultIncomeAccounts,
  updateFiscalYearSettings,
  upsertAccount,
  upsertCurrency,
  upsertPaymentTerm,
  deleteCostCenter,
  getCostCenter,
  getCostCenters,
  getCostCentersList,
  getCostCentersTree,
  upsertCostCenter,
  getDimensions,
  getDimension,
  upsertDimension,
  deleteDimension,
  getActiveDimensionsWithValues,
  getJournalLineDimensions,
  saveJournalLineDimensions,
  translateCompanyBalances,
  getConsolidatedBalances,
  getIntercompanyTransactions,
  createIntercompanyTransaction,
  runIntercompanyMatching,
  generateEliminations,
  getIntercompanyBalance,
  getExchangeRateHistory,
  getJournalEntries,
  getJournalEntry,
  createJournalEntry,
  updateJournalEntry,
  deleteJournalEntry,
  upsertJournalEntryLine,
  deleteJournalEntryLine,
  saveJournalEntryWithLines,
  postJournalEntry,
  reverseJournalEntry,
} from "~/modules/accounting/accounting.service";
import {
  defaultBalanceSheetAccountValidator,
  defaultIncomeAcountValidator,
  fiscalYearSettingsValidator,
  accountValidator,
  currencyValidator,
  paymentTermValidator,
  costCenterValidator,
  dimensionValidator,
  intercompanyTransactionValidator,
  journalEntryValidator,
  journalEntryLineValidator,
} from "~/modules/accounting/accounting.models";

export const registerAccountingTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "accounting_getTrialBalance",
    {
      description: "get trial balance",
      inputSchema: {
      companyGroupId: z.string(),
      args: z.object({
    startDate: z.string().nullable(),
    endDate: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrialBalance(ctx.client, params.companyGroupId, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getTrialBalance"),
  );

  server.registerTool(
    "accounting_getFinancialStatementBalances",
    {
      description: "get financial statement balances",
      inputSchema: {
      companyGroupId: z.string(),
      args: z.object({
    startDate: z.string().nullable(),
    endDate: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getFinancialStatementBalances(ctx.client, params.companyGroupId, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getFinancialStatementBalances"),
  );

  server.registerTool(
    "accounting_getCompaniesInGroup",
    {
      description: "get companies in group",
      inputSchema: {
      companyGroupId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCompaniesInGroup(ctx.client, params.companyGroupId);
      return toMcpResult(result);
    }, "Failed: accounting_getCompaniesInGroup"),
  );

  server.registerTool(
    "accounting_deleteAccount",
    {
      description: "delete account",
      inputSchema: z.object({
      accountId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteAccount(ctx.client, params.accountId);
      return toMcpResult(result);
    }, "Failed: accounting_deleteAccount"),
  );

  server.registerTool(
    "accounting_deleteAccountCategory",
    {
      description: "delete account category",
      inputSchema: z.object({
      accountCategoryId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteAccountCategory(ctx.client, params.accountCategoryId);
      return toMcpResult(result);
    }, "Failed: accounting_deleteAccountCategory"),
  );

  server.registerTool(
    "accounting_deleteAccountSubcategory",
    {
      description: "delete account subcategory",
      inputSchema: z.object({
      accountSubcategoryId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteAccountSubcategory(ctx.client, params.accountSubcategoryId);
      return toMcpResult(result);
    }, "Failed: accounting_deleteAccountSubcategory"),
  );

  server.registerTool(
    "accounting_deletePaymentTerm",
    {
      description: "delete payment term",
      inputSchema: z.object({
      paymentTermId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePaymentTerm(ctx.client, params.paymentTermId);
      return toMcpResult(result);
    }, "Failed: accounting_deletePaymentTerm"),
  );

  server.registerTool(
    "accounting_getAccount",
    {
      description: "get account",
      inputSchema: z.object({
      accountId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccount(ctx.client, params.accountId);
      return toMcpResult(result);
    }, "Failed: accounting_getAccount"),
  );

  server.registerTool(
    "accounting_getAccounts",
    {
      description: "get accounts",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccounts(ctx.client, params.companyGroupId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getAccounts"),
  );

  server.registerTool(
    "accounting_getAccountsList",
    {
      description: "get accounts list",
      inputSchema: z.object({
      args: z.object({
    isGroup: z.boolean().nullable().optional(),
    incomeBalance: z.any().optional(),
    classes: z.array(z.any()).optional()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountsList(ctx.client, params.companyGroupId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountsList"),
  );

  server.registerTool(
    "accounting_getGroupAccounts",
    {
      description: "get account categories",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getGroupAccounts(ctx.client, params.companyGroupId);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountCategories"),
  );

  server.registerTool(
    "accounting_getAccountCategoriesList",
    {
      description: "get account categories list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountCategoriesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountCategoriesList"),
  );

  server.registerTool(
    "accounting_getAccountCategory",
    {
      description: "get account category",
      inputSchema: z.object({
      accountCategoryId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountCategory(ctx.client, params.accountCategoryId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountCategory"),
  );

  server.registerTool(
    "accounting_getAccountSubcategories",
    {
      description: "get account subcategories",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountSubcategories(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountSubcategories"),
  );

  server.registerTool(
    "accounting_getAccountSubcategoriesByCategory",
    {
      description: "get account subcategories by category",
      inputSchema: z.object({
      accountCategoryId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountSubcategoriesByCategory(ctx.client, params.accountCategoryId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountSubcategoriesByCategory"),
  );

  server.registerTool(
    "accounting_getAccountSubcategory",
    {
      description: "get account subcategory",
      inputSchema: z.object({
      accountSubcategoryId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountSubcategory(ctx.client, params.accountSubcategoryId);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountSubcategory"),
  );

  server.registerTool(
    "accounting_getBaseCurrency",
    {
      description: "get base currency",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getBaseCurrency(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getBaseCurrency"),
  );

  server.registerTool(
    "accounting_getChartOfAccounts",
    {
      description: "get chart of accounts",
      inputSchema: z.object({
      args: z.object({
    incomeBalance: z.enum(["Income Statement", "Balance Sheet", "null"]),
    startDate: z.string().nullable(),
    endDate: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getChartOfAccounts(ctx.client, params.companyGroupId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getChartOfAccounts"),
  );

  server.registerTool(
    "accounting_getCurrency",
    {
      description: "get currency",
      inputSchema: z.object({
      currencyId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCurrency(ctx.client, params.currencyId);
      return toMcpResult(result);
    }, "Failed: accounting_getCurrency"),
  );

  server.registerTool(
    "accounting_getCurrencyByCode",
    {
      description: "get currency by code",
      inputSchema: z.object({
      currencyCode: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCurrencyByCode(ctx.client, params.companyGroupId, params.currencyCode);
      return toMcpResult(result);
    }, "Failed: accounting_getCurrencyByCode"),
  );

  server.registerTool(
    "accounting_getCurrencies",
    {
      description: "get currencies",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCurrencies(ctx.client, params.companyGroupId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getCurrencies"),
  );

  server.registerTool(
    "accounting_getCurrenciesList",
    {
      description: "get currencies list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCurrenciesList(ctx.client);
      return toMcpResult(result);
    }, "Failed: accounting_getCurrenciesList"),
  );

  server.registerTool(
    "accounting_getCurrentAccountingPeriod",
    {
      description: "get current accounting period",
      inputSchema: z.object({
      date: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCurrentAccountingPeriod(ctx.client, ctx.companyId, params.date);
      return toMcpResult(result);
    }, "Failed: accounting_getCurrentAccountingPeriod"),
  );

  server.registerTool(
    "accounting_getDefaultAccounts",
    {
      description: "get default accounts",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDefaultAccounts(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getDefaultAccounts"),
  );

  server.registerTool(
    "accounting_getFiscalYearSettings",
    {
      description: "get fiscal year settings",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getFiscalYearSettings(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getFiscalYearSettings"),
  );

  server.registerTool(
    "accounting_getInventoryPostingGroup",
    {
      description: "get inventory posting group",
      inputSchema: z.object({
      args: z.object({
    itemPostingGroupId: z.string().nullable(),
    locationId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getInventoryPostingGroup(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getInventoryPostingGroup"),
  );

  server.registerTool(
    "accounting_getInventoryPostingGroups",
    {
      description: "get inventory posting groups",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getInventoryPostingGroups(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getInventoryPostingGroups"),
  );

  server.registerTool(
    "accounting_getPaymentTerm",
    {
      description: "get payment term",
      inputSchema: z.object({
      paymentTermId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPaymentTerm(ctx.client, params.paymentTermId);
      return toMcpResult(result);
    }, "Failed: accounting_getPaymentTerm"),
  );

  server.registerTool(
    "accounting_getPaymentTerms",
    {
      description: "get payment terms",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPaymentTerms(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getPaymentTerms"),
  );

  server.registerTool(
    "accounting_getPaymentTermsList",
    {
      description: "get payment terms list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPaymentTermsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getPaymentTermsList"),
  );

  server.registerTool(
    "accounting_getPurchasingPostingGroup",
    {
      description: "get purchasing posting group",
      inputSchema: z.object({
      args: z.object({
    itemPostingGroupId: z.string().nullable(),
    supplierTypeId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingPostingGroup(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getPurchasingPostingGroup"),
  );

  server.registerTool(
    "accounting_getPurchasingPostingGroups",
    {
      description: "get purchasing posting groups",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingPostingGroups(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getPurchasingPostingGroups"),
  );

  server.registerTool(
    "accounting_getPurchasingSalesGroup",
    {
      description: "get purchasing sales group",
      inputSchema: z.object({
      args: z.object({
    itemPostingGroupId: z.string().nullable(),
    customerTypeId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingSalesGroup(ctx.client, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getPurchasingSalesGroup"),
  );

  server.registerTool(
    "accounting_getSalesPostingGroups",
    {
      description: "get sales posting groups",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesPostingGroups(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getSalesPostingGroups"),
  );

  server.registerTool(
    "accounting_updateDefaultBalanceSheetAccounts",
    {
      description: "update default balance sheet accounts",
      inputSchema: z.object({
      defaultAccounts: defaultBalanceSheetAccountValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateDefaultBalanceSheetAccounts(ctx.client, { ...params.defaultAccounts, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_updateDefaultBalanceSheetAccounts"),
  );

  server.registerTool(
    "accounting_updateDefaultIncomeAccounts",
    {
      description: "update default income accounts",
      inputSchema: z.object({
      defaultAccounts: defaultIncomeAcountValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateDefaultIncomeAccounts(ctx.client, { ...params.defaultAccounts, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_updateDefaultIncomeAccounts"),
  );

  server.registerTool(
    "accounting_updateFiscalYearSettings",
    {
      description: "update fiscal year settings",
      inputSchema: z.object({
      fiscalYearSettings: fiscalYearSettingsValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateFiscalYearSettings(ctx.client, { ...params.fiscalYearSettings, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_updateFiscalYearSettings"),
  );

  server.registerTool(
    "accounting_upsertAccount",
    {
      description: "upsert account",
      inputSchema: z.object({
      account: accountValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertAccount(ctx.client, { ...params.account, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_upsertAccount"),
  );

  server.registerTool(
    "accounting_upsertAccountCategory",
    {
      description: "upsert account category",
      inputSchema: z.object({
      accountCategory: accountCategoryValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertAccountCategory(ctx.client, { ...params.accountCategory, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_upsertAccountCategory"),
  );

  server.registerTool(
    "accounting_upsertAccountSubcategory",
    {
      description: "upsert account subcategory",
      inputSchema: z.object({
      accountSubcategory: accountSubcategoryValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertAccountSubcategory(ctx.client, { ...params.accountSubcategory, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_upsertAccountSubcategory"),
  );

  server.registerTool(
    "accounting_upsertCurrency",
    {
      description: "upsert currency",
      inputSchema: z.object({
      currency: currencyValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertCurrency(ctx.client, { ...params.currency, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_upsertCurrency"),
  );

  server.registerTool(
    "accounting_upsertPaymentTerm",
    {
      description: "upsert payment term",
      inputSchema: z.object({
      paymentTerm: paymentTermValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPaymentTerm(ctx.client, { ...params.paymentTerm, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_upsertPaymentTerm"),
  );

  server.registerTool(
    "accounting_deleteCostCenter",
    {
      description: "delete cost center",
      inputSchema: {
      costCenterId: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteCostCenter(ctx.client, params.costCenterId);
      return toMcpResult(result);
    }, "Failed: accounting_deleteCostCenter"),
  );

  server.registerTool(
    "accounting_getCostCenter",
    {
      description: "get cost center",
      inputSchema: {
      costCenterId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCostCenter(ctx.client, params.costCenterId);
      return toMcpResult(result);
    }, "Failed: accounting_getCostCenter"),
  );

  server.registerTool(
    "accounting_getCostCenters",
    {
      description: "get cost centers",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCostCenters(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getCostCenters"),
  );

  server.registerTool(
    "accounting_getCostCentersList",
    {
      description: "get cost centers list",
      inputSchema: {},
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCostCentersList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getCostCentersList"),
  );

  server.registerTool(
    "accounting_getCostCentersTree",
    {
      description: "get cost centers tree",
      inputSchema: {},
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCostCentersTree(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getCostCentersTree"),
  );

  server.registerTool(
    "accounting_upsertCostCenter",
    {
      description: "upsert cost center",
      inputSchema: {
      costCenter: costCenterValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertCostCenter(ctx.client, { ...params.costCenter, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_upsertCostCenter"),
  );

  server.registerTool(
    "accounting_getDimensions",
    {
      description: "get dimensions",
      inputSchema: {
      companyGroupId: z.string(),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDimensions(ctx.client, params.companyGroupId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getDimensions"),
  );

  server.registerTool(
    "accounting_getDimension",
    {
      description: "get dimension",
      inputSchema: {
      dimensionId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDimension(ctx.client, params.dimensionId);
      return toMcpResult(result);
    }, "Failed: accounting_getDimension"),
  );

  server.registerTool(
    "accounting_upsertDimension",
    {
      description: "upsert dimension",
      inputSchema: {
      dimension: dimensionValidator,
      dimensionValues: z.array(z.string()).optional(),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertDimension(ctx.client, { ...params.dimension, createdBy: ctx.userId, updatedBy: ctx.userId }, params.dimensionValues);
      return toMcpResult(result);
    }, "Failed: accounting_upsertDimension"),
  );

  server.registerTool(
    "accounting_deleteDimension",
    {
      description: "delete dimension",
      inputSchema: {
      dimensionId: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteDimension(ctx.client, params.dimensionId);
      return toMcpResult(result);
    }, "Failed: accounting_deleteDimension"),
  );

  server.registerTool(
    "accounting_getActiveDimensionsWithValues",
    {
      description: "get active dimensions with values",
      inputSchema: {
      companyGroupId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getActiveDimensionsWithValues(ctx.client, params.companyGroupId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getActiveDimensionsWithValues"),
  );

  server.registerTool(
    "accounting_getJournalLineDimensions",
    {
      description: "get journal line dimensions",
      inputSchema: {
      journalLineIds: z.array(z.string()),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJournalLineDimensions(ctx.client, params.journalLineIds);
      return toMcpResult(result);
    }, "Failed: accounting_getJournalLineDimensions"),
  );

  server.registerTool(
    "accounting_saveJournalLineDimensions",
    {
      description: "save journal line dimensions",
      inputSchema: {
      journalLineId: z.string(),
      dimensions: z.any(),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await saveJournalLineDimensions(ctx.client, params.journalLineId, ctx.companyId, params.dimensions);
      return toMcpResult(result);
    }, "Failed: accounting_saveJournalLineDimensions"),
  );

  server.registerTool(
    "accounting_translateCompanyBalances",
    {
      description: "translate company balances",
      inputSchema: {
      companyGroupId: z.string(),
      targetCurrency: z.string(),
      periodEnd: z.string(),
      periodStart: z.string().optional(),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await translateCompanyBalances(ctx.client, params.companyGroupId, ctx.companyId, params.targetCurrency, params.periodEnd, params.periodStart);
      return toMcpResult(result);
    }, "Failed: accounting_translateCompanyBalances"),
  );

  server.registerTool(
    "accounting_getConsolidatedBalances",
    {
      description: "get consolidated balances",
      inputSchema: {
      companyGroupId: z.string(),
      companyIds: z.array(z.string()),
      targetCurrency: z.string(),
      periodEnd: z.string(),
      periodStart: z.string().optional(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getConsolidatedBalances(ctx.client, params.companyGroupId, params.companyIds, params.targetCurrency, params.periodEnd, params.periodStart);
      return toMcpResult(result);
    }, "Failed: accounting_getConsolidatedBalances"),
  );

  server.registerTool(
    "accounting_getIntercompanyTransactions",
    {
      description: "get intercompany transactions",
      inputSchema: {
      companyGroupId: z.string(),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    status: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIntercompanyTransactions(ctx.client, params.companyGroupId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getIntercompanyTransactions"),
  );

  server.registerTool(
    "accounting_createIntercompanyTransaction",
    {
      description: "create intercompany transaction",
      inputSchema: {
      input: intercompanyTransactionValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createIntercompanyTransaction(ctx.client, { ...params.input, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_createIntercompanyTransaction"),
  );

  server.registerTool(
    "accounting_runIntercompanyMatching",
    {
      description: "run intercompany matching",
      inputSchema: {
      companyGroupId: z.string(),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await runIntercompanyMatching(ctx.client, params.companyGroupId);
      return toMcpResult(result);
    }, "Failed: accounting_runIntercompanyMatching"),
  );

  server.registerTool(
    "accounting_generateEliminations",
    {
      description: "generate eliminations",
      inputSchema: {
      companyGroupId: z.string(),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await generateEliminations(ctx.client, params.companyGroupId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: accounting_generateEliminations"),
  );

  server.registerTool(
    "accounting_getIntercompanyBalance",
    {
      description: "get intercompany balance",
      inputSchema: {
      companyGroupId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIntercompanyBalance(ctx.client, params.companyGroupId);
      return toMcpResult(result);
    }, "Failed: accounting_getIntercompanyBalance"),
  );

  server.registerTool(
    "accounting_getExchangeRateHistory",
    {
      description: "get exchange rate history",
      inputSchema: {
      companyGroupId: z.string(),
      currencyCode: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getExchangeRateHistory(ctx.client, params.companyGroupId, params.currencyCode);
      return toMcpResult(result);
    }, "Failed: accounting_getExchangeRateHistory"),
  );

  server.registerTool(
    "accounting_getJournalEntries",
    {
      description: "get journal entries",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    status: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJournalEntries(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getJournalEntries"),
  );

  server.registerTool(
    "accounting_getJournalEntry",
    {
      description: "get journal entry",
      inputSchema: {
      id: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJournalEntry(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: accounting_getJournalEntry"),
  );

  server.registerTool(
    "accounting_createJournalEntry",
    {
      description: "create journal entry",
      inputSchema: {
      data: journalEntryValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createJournalEntry(ctx.client, { ...params.data, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_createJournalEntry"),
  );

  server.registerTool(
    "accounting_updateJournalEntry",
    {
      description: "update journal entry",
      inputSchema: {
      id: z.string(),
      data: journalEntryValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateJournalEntry(ctx.client, params.id, { ...params.data, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_updateJournalEntry"),
  );

  server.registerTool(
    "accounting_deleteJournalEntry",
    {
      description: "delete journal entry",
      inputSchema: {
      id: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteJournalEntry(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: accounting_deleteJournalEntry"),
  );

  server.registerTool(
    "accounting_upsertJournalEntryLine",
    {
      description: "upsert journal entry line",
      inputSchema: {
      data: journalEntryLineValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertJournalEntryLine(ctx.client, { ...params.data, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_upsertJournalEntryLine"),
  );

  server.registerTool(
    "accounting_deleteJournalEntryLine",
    {
      description: "delete journal entry line",
      inputSchema: {
      id: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteJournalEntryLine(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: accounting_deleteJournalEntryLine"),
  );

  server.registerTool(
    "accounting_saveJournalEntryWithLines",
    {
      description: "save journal entry with lines",
      inputSchema: {
      data: z.object({
    journalEntryId: z.string(),
    postingDate: z.string(),
    description: z.string().optional(),
    lines: z.any(),
    accountId: z.string(),
    description: z.string().optional(),
    debit: z.number(),
    credit: z.number(),
    dimensions: z.any().optional(),
    valueId: z.any(),
    companyGroupId: z.string()
  }),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await saveJournalEntryWithLines(ctx.client, { ...params.data, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_saveJournalEntryWithLines"),
  );

  server.registerTool(
    "accounting_postJournalEntry",
    {
      description: "post journal entry",
      inputSchema: {
      id: z.string(),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await postJournalEntry(ctx.client, params.id, ctx.userId);
      return toMcpResult(result);
    }, "Failed: accounting_postJournalEntry"),
  );

  server.registerTool(
    "accounting_reverseJournalEntry",
    {
      description: "reverse journal entry",
      inputSchema: {
      id: z.string(),
      data: z.object({
    journalEntryId: z.string()
  }),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await reverseJournalEntry(ctx.client, params.id, { ...params.data, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_reverseJournalEntry"),
  );
};
