// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  deleteBatchProperty,
  deleteKanban,
  deleteReceipt,
  deleteReceiptLine,
  deleteStorageUnit,
  deleteShipment,
  deleteShipmentLine,
  deleteShippingMethod,
  deleteStockTransfer,
  deleteStockTransferLine,
  deleteWarehouseTransfer,
  deleteWarehouseTransferLine,
  getItemLedgerPage,
  getBatchProperties,
  getInventoryItems,
  getInventoryItemsCount,
  getKanbans,
  getKanban,
  getStockTransfer,
  getStockTransferLine,
  getStockTransferLines,
  getStockTransferTracking,
  getStockTransfers,
  getDefaultStorageUnitOrStorageUnitWithHighestQuantity,
  getReceipts,
  getReceipt,
  getReceiptLines,
  getReceiptTracking,
  getReceiptLineTracking,
  getReceiptFiles,
  getSerialNumbersForItem,
  getBatchNumbersForItem,
  getStorageUnitsList,
  getStorageUnitsListForLocation,
  getStorageUnits,
  getStorageUnit,
  getShipments,
  getShipment,
  getShipmentLines,
  getShipmentLinesWithDetails,
  getShipmentFiles,
  getShipmentRelatedItems,
  getShipmentTracking,
  getShipmentLineTracking,
  getShippingMethod,
  getShippingMethods,
  getShippingMethodsList,
  getShippingTermsList,
  getTrackedEntities,
  getTrackedEntitiesByMakeMethodId,
  getTrackedEntity,
  getTrackedEntitiesByOperationId,
  getWarehouseTransfers,
  getWarehouseTransfer,
  getWarehouseTransferLine,
  getWarehouseTransferLines,
  insertManualInventoryAdjustment,
  updateBatchPropertyOrder,
  updateStockTransferStatus,
  upsertBatchProperty,
  upsertKanban,
  upsertReceipt,
  upsertStorageUnit,
  upsertShippingMethod,
  upsertShipment,
  upsertStockTransfer,
  upsertStockTransferLine,
  upsertStockTransferLines,
  upsertWarehouseTransfer,
  updateWarehouseTransferStatus,
  upsertWarehouseTransferLine,
  getDefaultStorageUnitForJob,
} from "~/modules/inventory/inventory.service";
import {
  inventoryAdjustmentValidator,
  batchPropertyOrderValidator,
  batchPropertyValidator,
  kanbanValidator,
  receiptValidator,
  storageUnitValidator,
  shippingMethodValidator,
  shipmentValidator,
  stockTransferLineValidator,
  stockTransferValidator,
  warehouseTransferValidator,
} from "~/modules/inventory/inventory.models";

export const registerInventoryTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "inventory_deleteBatchProperty",
    {
      description: "delete batch property",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteBatchProperty(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: inventory_deleteBatchProperty"),
  );

  server.registerTool(
    "inventory_deleteKanban",
    {
      description: "delete kanban",
      inputSchema: z.object({
      kanbanId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteKanban(ctx.client, params.kanbanId);
      return toMcpResult(result);
    }, "Failed: inventory_deleteKanban"),
  );

  server.registerTool(
    "inventory_deleteReceipt",
    {
      description: "delete receipt",
      inputSchema: z.object({
      receiptId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteReceipt(ctx.client, params.receiptId);
      return toMcpResult(result);
    }, "Failed: inventory_deleteReceipt"),
  );

  server.registerTool(
    "inventory_deleteReceiptLine",
    {
      description: "delete receipt line",
      inputSchema: z.object({
      receiptLineId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteReceiptLine(ctx.client, params.receiptLineId);
      return toMcpResult(result);
    }, "Failed: inventory_deleteReceiptLine"),
  );

  server.registerTool(
    "inventory_deleteStorageUnit",
    {
      description: "delete storage unit",
      inputSchema: z.object({
      storageUnitId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteStorageUnit(ctx.client, params.storageUnitId);
      return toMcpResult(result);
    }, "Failed: inventory_deleteStorageUnit"),
  );

  server.registerTool(
    "inventory_deleteShipment",
    {
      description: "delete shipment",
      inputSchema: z.object({
      shipmentId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteShipment(ctx.client, params.shipmentId);
      return toMcpResult(result);
    }, "Failed: inventory_deleteShipment"),
  );

  server.registerTool(
    "inventory_deleteShipmentLine",
    {
      description: "delete shipment line",
      inputSchema: z.object({
      shipmentLineId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteShipmentLine(ctx.client, params.shipmentLineId);
      return toMcpResult(result);
    }, "Failed: inventory_deleteShipmentLine"),
  );

  server.registerTool(
    "inventory_deleteShippingMethod",
    {
      description: "delete shipping method",
      inputSchema: z.object({
      shippingMethodId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteShippingMethod(ctx.client, params.shippingMethodId);
      return toMcpResult(result);
    }, "Failed: inventory_deleteShippingMethod"),
  );

  server.registerTool(
    "inventory_deleteStockTransfer",
    {
      description: "delete stock transfer",
      inputSchema: z.object({
      stockTransferId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteStockTransfer(ctx.client, params.stockTransferId);
      return toMcpResult(result);
    }, "Failed: inventory_deleteStockTransfer"),
  );

  server.registerTool(
    "inventory_deleteStockTransferLine",
    {
      description: "delete stock transfer line",
      inputSchema: z.object({
      stockTransferLineId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteStockTransferLine(ctx.client, params.stockTransferLineId);
      return toMcpResult(result);
    }, "Failed: inventory_deleteStockTransferLine"),
  );

  server.registerTool(
    "inventory_deleteWarehouseTransfer",
    {
      description: "delete warehouse transfer",
      inputSchema: z.object({
      transferId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteWarehouseTransfer(ctx.client, params.transferId);
      return toMcpResult(result);
    }, "Failed: inventory_deleteWarehouseTransfer"),
  );

  server.registerTool(
    "inventory_deleteWarehouseTransferLine",
    {
      description: "delete warehouse transfer line",
      inputSchema: z.object({
      transferLineId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteWarehouseTransferLine(ctx.client, params.transferLineId);
      return toMcpResult(result);
    }, "Failed: inventory_deleteWarehouseTransferLine"),
  );

  server.registerTool(
    "inventory_getItemLedgerPage",
    {
      description: "get item ledger page",
      inputSchema: z.object({
      itemId: z.string(),
      locationId: z.string(),
      sortDescending: z.boolean().optional(),
      page: z.number().optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getItemLedgerPage(ctx.client, params.itemId, ctx.companyId, params.locationId, params.sortDescending, params.page);
      return toMcpResult(result);
    }, "Failed: inventory_getItemLedgerPage"),
  );

  server.registerTool(
    "inventory_getBatchProperties",
    {
      description: "get batch properties",
      inputSchema: z.object({
      itemIds: z.array(z.string()),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getBatchProperties(ctx.client, params.itemIds, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: inventory_getBatchProperties"),
  );

  server.registerTool(
    "inventory_getInventoryItems",
    {
      description: "get inventory items",
      inputSchema: z.object({
      locationId: z.string(),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getInventoryItems(ctx.client, params.locationId, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: inventory_getInventoryItems"),
  );

  server.registerTool(
    "inventory_getInventoryItemsCount",
    {
      description: "get inventory items count",
      inputSchema: z.object({
      locationId: z.string(),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getInventoryItemsCount(ctx.client, params.locationId, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: inventory_getInventoryItemsCount"),
  );

  server.registerTool(
    "inventory_getKanbans",
    {
      description: "get kanbans",
      inputSchema: z.object({
      locationId: z.string(),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getKanbans(ctx.client, params.locationId, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: inventory_getKanbans"),
  );

  server.registerTool(
    "inventory_getKanban",
    {
      description: "get kanban",
      inputSchema: z.object({
      kanbanId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getKanban(ctx.client, params.kanbanId);
      return toMcpResult(result);
    }, "Failed: inventory_getKanban"),
  );

  server.registerTool(
    "inventory_getStockTransfer",
    {
      description: "get stock transfer",
      inputSchema: z.object({
      stockTransferId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getStockTransfer(ctx.client, params.stockTransferId);
      return toMcpResult(result);
    }, "Failed: inventory_getStockTransfer"),
  );

  server.registerTool(
    "inventory_getStockTransferLine",
    {
      description: "get stock transfer line",
      inputSchema: z.object({
      stockTransferLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getStockTransferLine(ctx.client, params.stockTransferLineId);
      return toMcpResult(result);
    }, "Failed: inventory_getStockTransferLine"),
  );

  server.registerTool(
    "inventory_getStockTransferLines",
    {
      description: "get stock transfer lines",
      inputSchema: z.object({
      stockTransferId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getStockTransferLines(ctx.client, params.stockTransferId);
      return toMcpResult(result);
    }, "Failed: inventory_getStockTransferLines"),
  );

  server.registerTool(
    "inventory_getStockTransferTracking",
    {
      description: "get stock transfer tracking",
      inputSchema: z.object({
      stockTransferId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getStockTransferTracking(ctx.client, params.stockTransferId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: inventory_getStockTransferTracking"),
  );

  server.registerTool(
    "inventory_getStockTransfers",
    {
      description: "get stock transfers",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    locationId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getStockTransfers(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: inventory_getStockTransfers"),
  );

  server.registerTool(
    "inventory_getDefaultStorageUnitOrStorageUnitWithHighestQuantity",
    {
      description: "get default storage unit or storage unit with highest quantity",
      inputSchema: z.object({
      itemId: z.string(),
      locationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDefaultStorageUnitOrStorageUnitWithHighestQuantity(ctx.client, params.itemId, params.locationId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: inventory_getDefaultStorageUnitOrStorageUnitWithHighestQuantity"),
  );

  server.registerTool(
    "inventory_getReceipts",
    {
      description: "get receipts",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getReceipts(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: inventory_getReceipts"),
  );

  server.registerTool(
    "inventory_getReceipt",
    {
      description: "get receipt",
      inputSchema: z.object({
      receiptId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getReceipt(ctx.client, params.receiptId);
      return toMcpResult(result);
    }, "Failed: inventory_getReceipt"),
  );

  server.registerTool(
    "inventory_getReceiptLines",
    {
      description: "get receipt lines",
      inputSchema: z.object({
      receiptId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getReceiptLines(ctx.client, params.receiptId);
      return toMcpResult(result);
    }, "Failed: inventory_getReceiptLines"),
  );

  server.registerTool(
    "inventory_getReceiptTracking",
    {
      description: "get receipt tracking",
      inputSchema: z.object({
      receiptId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getReceiptTracking(ctx.client, params.receiptId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: inventory_getReceiptTracking"),
  );

  server.registerTool(
    "inventory_getReceiptLineTracking",
    {
      description: "get receipt line tracking",
      inputSchema: z.object({
      receiptLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getReceiptLineTracking(ctx.client, params.receiptLineId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: inventory_getReceiptLineTracking"),
  );

  server.registerTool(
    "inventory_getReceiptFiles",
    {
      description: "get receipt files",
      inputSchema: z.object({
      lineIds: z.array(z.string()),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getReceiptFiles(ctx.client, ctx.companyId, params.lineIds);
      return toMcpResult(result);
    }, "Failed: inventory_getReceiptFiles"),
  );

  server.registerTool(
    "inventory_getSerialNumbersForItem",
    {
      description: "get serial numbers for item",
      inputSchema: z.object({
      args: z.object({
    itemId: z.string()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSerialNumbersForItem(ctx.client, { ...params.args, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: inventory_getSerialNumbersForItem"),
  );

  server.registerTool(
    "inventory_getBatchNumbersForItem",
    {
      description: "get batch numbers for item",
      inputSchema: z.object({
      args: z.object({
    itemId: z.string(),
    isReadOnly: z.boolean().optional()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getBatchNumbersForItem(ctx.client, { ...params.args, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: inventory_getBatchNumbersForItem"),
  );

  server.registerTool(
    "inventory_getStorageUnitsList",
    {
      description: "get storage units list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getStorageUnitsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: inventory_getStorageUnitsList"),
  );

  server.registerTool(
    "inventory_getStorageUnitsListForLocation",
    {
      description: "get storage units list for location",
      inputSchema: z.object({
      locationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getStorageUnitsListForLocation(ctx.client, ctx.companyId, params.locationId);
      return toMcpResult(result);
    }, "Failed: inventory_getStorageUnitsListForLocation"),
  );

  server.registerTool(
    "inventory_getStorageUnits",
    {
      description: "get storage units",
      inputSchema: z.object({
      locationId: z.string(),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getStorageUnits(ctx.client, params.locationId, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: inventory_getStorageUnits"),
  );

  server.registerTool(
    "inventory_getStorageUnit",
    {
      description: "get storage unit",
      inputSchema: z.object({
      storageUnitId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getStorageUnit(ctx.client, params.storageUnitId);
      return toMcpResult(result);
    }, "Failed: inventory_getStorageUnit"),
  );

  server.registerTool(
    "inventory_getShipments",
    {
      description: "get shipments",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShipments(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: inventory_getShipments"),
  );

  server.registerTool(
    "inventory_getShipment",
    {
      description: "get shipment",
      inputSchema: z.object({
      shipmentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShipment(ctx.client, params.shipmentId);
      return toMcpResult(result);
    }, "Failed: inventory_getShipment"),
  );

  server.registerTool(
    "inventory_getShipmentLines",
    {
      description: "get shipment lines",
      inputSchema: z.object({
      shipmentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShipmentLines(ctx.client, params.shipmentId);
      return toMcpResult(result);
    }, "Failed: inventory_getShipmentLines"),
  );

  server.registerTool(
    "inventory_getShipmentLinesWithDetails",
    {
      description: "get shipment lines with details",
      inputSchema: z.object({
      shipmentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShipmentLinesWithDetails(ctx.client, params.shipmentId);
      return toMcpResult(result);
    }, "Failed: inventory_getShipmentLinesWithDetails"),
  );

  server.registerTool(
    "inventory_getShipmentFiles",
    {
      description: "get shipment files",
      inputSchema: z.object({
      lineIds: z.array(z.string()),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShipmentFiles(ctx.client, ctx.companyId, params.lineIds);
      return toMcpResult(result);
    }, "Failed: inventory_getShipmentFiles"),
  );

  server.registerTool(
    "inventory_getShipmentRelatedItems",
    {
      description: "get shipment related items",
      inputSchema: z.object({
      shipmentId: z.string(),
      sourceDocumentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShipmentRelatedItems(ctx.client, params.shipmentId, params.sourceDocumentId);
      return toMcpResult(result);
    }, "Failed: inventory_getShipmentRelatedItems"),
  );

  server.registerTool(
    "inventory_getShipmentTracking",
    {
      description: "get shipment tracking",
      inputSchema: z.object({
      shipmentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShipmentTracking(ctx.client, params.shipmentId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: inventory_getShipmentTracking"),
  );

  server.registerTool(
    "inventory_getShipmentLineTracking",
    {
      description: "get shipment line tracking",
      inputSchema: z.object({
      shipmentLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShipmentLineTracking(ctx.client, params.shipmentLineId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: inventory_getShipmentLineTracking"),
  );

  server.registerTool(
    "inventory_getShippingMethod",
    {
      description: "get shipping method",
      inputSchema: z.object({
      shippingMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShippingMethod(ctx.client, params.shippingMethodId);
      return toMcpResult(result);
    }, "Failed: inventory_getShippingMethod"),
  );

  server.registerTool(
    "inventory_getShippingMethods",
    {
      description: "get shipping methods",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShippingMethods(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: inventory_getShippingMethods"),
  );

  server.registerTool(
    "inventory_getShippingMethodsList",
    {
      description: "get shipping methods list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShippingMethodsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: inventory_getShippingMethodsList"),
  );

  server.registerTool(
    "inventory_getShippingTermsList",
    {
      description: "get shipping terms list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShippingTermsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: inventory_getShippingTermsList"),
  );

  server.registerTool(
    "inventory_getTrackedEntities",
    {
      description: "get tracked entities",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrackedEntities(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: inventory_getTrackedEntities"),
  );

  server.registerTool(
    "inventory_getTrackedEntitiesByMakeMethodId",
    {
      description: "get tracked entities by make method id",
      inputSchema: z.object({
      jobMakeMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrackedEntitiesByMakeMethodId(ctx.client, params.jobMakeMethodId);
      return toMcpResult(result);
    }, "Failed: inventory_getTrackedEntitiesByMakeMethodId"),
  );

  server.registerTool(
    "inventory_getTrackedEntity",
    {
      description: "get tracked entity",
      inputSchema: z.object({
      trackedEntityId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrackedEntity(ctx.client, params.trackedEntityId);
      return toMcpResult(result);
    }, "Failed: inventory_getTrackedEntity"),
  );

  server.registerTool(
    "inventory_getTrackedEntitiesByOperationId",
    {
      description: "get tracked entities by operation id",
      inputSchema: z.object({
      operationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrackedEntitiesByOperationId(ctx.client, params.operationId);
      return toMcpResult(result);
    }, "Failed: inventory_getTrackedEntitiesByOperationId"),
  );

  server.registerTool(
    "inventory_getWarehouseTransfers",
    {
      description: "get warehouse transfers",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWarehouseTransfers(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: inventory_getWarehouseTransfers"),
  );

  server.registerTool(
    "inventory_getWarehouseTransfer",
    {
      description: "get warehouse transfer",
      inputSchema: z.object({
      transferId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWarehouseTransfer(ctx.client, params.transferId);
      return toMcpResult(result);
    }, "Failed: inventory_getWarehouseTransfer"),
  );

  server.registerTool(
    "inventory_getWarehouseTransferLine",
    {
      description: "get warehouse transfer line",
      inputSchema: z.object({
      transferId: z.string(),
      lineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWarehouseTransferLine(ctx.client, params.transferId, params.lineId);
      return toMcpResult(result);
    }, "Failed: inventory_getWarehouseTransferLine"),
  );

  server.registerTool(
    "inventory_getWarehouseTransferLines",
    {
      description: "get warehouse transfer lines",
      inputSchema: z.object({
      transferId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWarehouseTransferLines(ctx.client, params.transferId);
      return toMcpResult(result);
    }, "Failed: inventory_getWarehouseTransferLines"),
  );

  server.registerTool(
    "inventory_insertManualInventoryAdjustment",
    {
      description: "insert manual inventory adjustment",
      inputSchema: z.object({
      inventoryAdjustment: inventoryAdjustmentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      // TODO(item-rules): MCP path bypasses item-rule gate. This wrapper is
      // dead code — actual MCP dispatch goes through direct-executor.ts
      // calling the service directly. Place the gate in direct-executor or
      // inside insertManualInventoryAdjustment itself.
      const result = await insertManualInventoryAdjustment(ctx.client, { ...params.inventoryAdjustment, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_insertManualInventoryAdjustment"),
  );

  server.registerTool(
    "inventory_updateBatchPropertyOrder",
    {
      description: "update batch property order",
      inputSchema: z.object({
      data: batchPropertyOrderValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateBatchPropertyOrder(ctx.client, { ...params.data, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_updateBatchPropertyOrder"),
  );

  server.registerTool(
    "inventory_updateStockTransferStatus",
    {
      description: "update stock transfer status",
      inputSchema: z.object({
      args: z.object({
    id: z.string(),
    status: z.any(),
    assignee: z.string().nullable().optional(),
    completedAt: z.string().nullable()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateStockTransferStatus(ctx.client, { ...params.args, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_updateStockTransferStatus"),
  );

  server.registerTool(
    "inventory_upsertBatchProperty",
    {
      description: "upsert batch property",
      inputSchema: z.object({
      batchProperty: batchPropertyValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertBatchProperty(ctx.client, { ...params.batchProperty, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_upsertBatchProperty"),
  );

  server.registerTool(
    "inventory_upsertKanban",
    {
      description: "upsert kanban",
      inputSchema: z.object({
      kanban: kanbanValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertKanban(ctx.client, { ...params.kanban, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_upsertKanban"),
  );

  server.registerTool(
    "inventory_upsertReceipt",
    {
      description: "upsert receipt",
      inputSchema: z.object({
      receipt: receiptValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertReceipt(ctx.client, { ...params.receipt, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_upsertReceipt"),
  );

  server.registerTool(
    "inventory_upsertStorageUnit",
    {
      description: "upsert storage unit",
      inputSchema: z.object({
      storageUnit: storageUnitValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertStorageUnit(ctx.client, { ...params.storageUnit, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_upsertStorageUnit"),
  );

  server.registerTool(
    "inventory_upsertShippingMethod",
    {
      description: "upsert shipping method",
      inputSchema: z.object({
      shippingMethod: shippingMethodValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertShippingMethod(ctx.client, { ...params.shippingMethod, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_upsertShippingMethod"),
  );

  server.registerTool(
    "inventory_upsertShipment",
    {
      description: "upsert shipment",
      inputSchema: z.object({
      shipment: shipmentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertShipment(ctx.client, { ...params.shipment, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_upsertShipment"),
  );

  server.registerTool(
    "inventory_upsertStockTransfer",
    {
      description: "upsert stock transfer",
      inputSchema: z.object({
      stockTransfer: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertStockTransfer(ctx.client, { ...params.stockTransfer, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_upsertStockTransfer"),
  );

  server.registerTool(
    "inventory_upsertStockTransferLine",
    {
      description: "upsert stock transfer line",
      inputSchema: z.object({
      stockTransferLine: stockTransferLineValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertStockTransferLine(ctx.client, { ...params.stockTransferLine, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_upsertStockTransferLine"),
  );

  server.registerTool(
    "inventory_upsertStockTransferLines",
    {
      description: "upsert stock transfer lines",
      inputSchema: z.object({
      args: stockTransferValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertStockTransferLines(ctx.client, { ...params.args, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_upsertStockTransferLines"),
  );

  server.registerTool(
    "inventory_upsertWarehouseTransfer",
    {
      description: "upsert warehouse transfer",
      inputSchema: z.object({
      transfer: warehouseTransferValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertWarehouseTransfer(ctx.client, { ...params.transfer, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: inventory_upsertWarehouseTransfer"),
  );

  server.registerTool(
    "inventory_updateWarehouseTransferStatus",
    {
      description: "update warehouse transfer status",
      inputSchema: z.object({
      transferId: z.string(),
      status: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateWarehouseTransferStatus(ctx.client, params.transferId, params.status, ctx.userId);
      return toMcpResult(result);
    }, "Failed: inventory_updateWarehouseTransferStatus"),
  );

  server.registerTool(
    "inventory_upsertWarehouseTransferLine",
    {
      description: "upsert warehouse transfer line",
      inputSchema: z.object({
      line: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertWarehouseTransferLine(ctx.client, params.line);
      return toMcpResult(result);
    }, "Failed: inventory_upsertWarehouseTransferLine"),
  );

  server.registerTool(
    "inventory_getDefaultStorageUnitForJob",
    {
      description: "get default storage unit for job",
      inputSchema: z.object({
      itemId: z.string(),
      locationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDefaultStorageUnitForJob(ctx.client, params.itemId, params.locationId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: inventory_getDefaultStorageUnitForJob"),
  );
};
