// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  createPurchaseInvoiceFromPurchaseOrder,
  createSalesInvoiceFromSalesOrder,
  createSalesInvoiceFromShipment,
  deletePurchaseInvoice,
  deletePurchaseInvoiceLine,
  deleteSalesInvoice,
  deleteSalesInvoiceLine,
  getPurchaseInvoice,
  getPurchaseInvoices,
  getPurchaseInvoiceDelivery,
  getPurchaseInvoiceLines,
  getPurchaseInvoiceLine,
  getSalesInvoice,
  getSalesInvoiceCustomerDetails,
  getSalesInvoices,
  getSalesInvoiceShipment,
  getSalesInvoiceLines,
  getSalesInvoiceLine,
  updatePurchaseInvoiceExchangeRate,
  updatePurchaseInvoiceStatus,
  updateSalesInvoiceExchangeRate,
  updateSalesInvoiceStatus,
  upsertPurchaseInvoice,
  upsertPurchaseInvoiceDelivery,
  upsertPurchaseInvoiceLine,
  upsertSalesInvoice,
  upsertSalesInvoiceShipment,
  upsertSalesInvoiceLine,
} from "~/modules/invoicing/invoicing.service";
import {
  purchaseInvoiceValidator,
  purchaseInvoiceDeliveryValidator,
  purchaseInvoiceLineValidator,
  salesInvoiceValidator,
  salesInvoiceShipmentValidator,
  salesInvoiceLineValidator,
} from "~/modules/invoicing/invoicing.models";

export const registerInvoicingTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "invoicing_createPurchaseInvoiceFromPurchaseOrder",
    {
      description: "create purchase invoice from purchase order",
      inputSchema: z.object({
      purchaseOrderId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createPurchaseInvoiceFromPurchaseOrder(ctx.client, params.purchaseOrderId, ctx.companyId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: invoicing_createPurchaseInvoiceFromPurchaseOrder"),
  );

  server.registerTool(
    "invoicing_createSalesInvoiceFromSalesOrder",
    {
      description: "create sales invoice from sales order",
      inputSchema: z.object({
      salesOrderId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createSalesInvoiceFromSalesOrder(ctx.client, params.salesOrderId, ctx.companyId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: invoicing_createSalesInvoiceFromSalesOrder"),
  );

  server.registerTool(
    "invoicing_createSalesInvoiceFromShipment",
    {
      description: "create sales invoice from shipment",
      inputSchema: z.object({
      shipmentId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createSalesInvoiceFromShipment(ctx.client, params.shipmentId, ctx.companyId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: invoicing_createSalesInvoiceFromShipment"),
  );

  server.registerTool(
    "invoicing_deletePurchaseInvoice",
    {
      description: "delete purchase invoice",
      inputSchema: z.object({
      purchaseInvoiceId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePurchaseInvoice(ctx.client, params.purchaseInvoiceId);
      return toMcpResult(result);
    }, "Failed: invoicing_deletePurchaseInvoice"),
  );

  server.registerTool(
    "invoicing_deletePurchaseInvoiceLine",
    {
      description: "delete purchase invoice line",
      inputSchema: z.object({
      purchaseInvoiceLineId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePurchaseInvoiceLine(ctx.client, params.purchaseInvoiceLineId);
      return toMcpResult(result);
    }, "Failed: invoicing_deletePurchaseInvoiceLine"),
  );

  server.registerTool(
    "invoicing_deleteSalesInvoice",
    {
      description: "delete sales invoice",
      inputSchema: z.object({
      salesInvoiceId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSalesInvoice(ctx.client, params.salesInvoiceId);
      return toMcpResult(result);
    }, "Failed: invoicing_deleteSalesInvoice"),
  );

  server.registerTool(
    "invoicing_deleteSalesInvoiceLine",
    {
      description: "delete sales invoice line",
      inputSchema: z.object({
      salesInvoiceLineId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSalesInvoiceLine(ctx.client, params.salesInvoiceLineId);
      return toMcpResult(result);
    }, "Failed: invoicing_deleteSalesInvoiceLine"),
  );

  server.registerTool(
    "invoicing_getPurchaseInvoice",
    {
      description: "get purchase invoice",
      inputSchema: z.object({
      purchaseInvoiceId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseInvoice(ctx.client, params.purchaseInvoiceId);
      return toMcpResult(result);
    }, "Failed: invoicing_getPurchaseInvoice"),
  );

  server.registerTool(
    "invoicing_getPurchaseInvoices",
    {
      description: "get purchase invoices",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    supplierId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseInvoices(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: invoicing_getPurchaseInvoices"),
  );

  server.registerTool(
    "invoicing_getPurchaseInvoiceDelivery",
    {
      description: "get purchase invoice delivery",
      inputSchema: z.object({
      purchaseInvoiceId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseInvoiceDelivery(ctx.client, params.purchaseInvoiceId);
      return toMcpResult(result);
    }, "Failed: invoicing_getPurchaseInvoiceDelivery"),
  );

  server.registerTool(
    "invoicing_getPurchaseInvoiceLines",
    {
      description: "get purchase invoice lines",
      inputSchema: z.object({
      purchaseInvoiceId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseInvoiceLines(ctx.client, params.purchaseInvoiceId);
      return toMcpResult(result);
    }, "Failed: invoicing_getPurchaseInvoiceLines"),
  );

  server.registerTool(
    "invoicing_getPurchaseInvoiceLine",
    {
      description: "get purchase invoice line",
      inputSchema: z.object({
      purchaseInvoiceLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseInvoiceLine(ctx.client, params.purchaseInvoiceLineId);
      return toMcpResult(result);
    }, "Failed: invoicing_getPurchaseInvoiceLine"),
  );

  server.registerTool(
    "invoicing_getSalesInvoice",
    {
      description: "get sales invoice",
      inputSchema: z.object({
      salesInvoiceId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesInvoice(ctx.client, params.salesInvoiceId);
      return toMcpResult(result);
    }, "Failed: invoicing_getSalesInvoice"),
  );

  server.registerTool(
    "invoicing_getSalesInvoiceCustomerDetails",
    {
      description: "get sales invoice customer details",
      inputSchema: z.object({
      salesInvoiceId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesInvoiceCustomerDetails(ctx.client, params.salesInvoiceId);
      return toMcpResult(result);
    }, "Failed: invoicing_getSalesInvoiceCustomerDetails"),
  );

  server.registerTool(
    "invoicing_getSalesInvoices",
    {
      description: "get sales invoices",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    customerId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesInvoices(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: invoicing_getSalesInvoices"),
  );

  server.registerTool(
    "invoicing_getSalesInvoiceShipment",
    {
      description: "get sales invoice shipment",
      inputSchema: z.object({
      salesInvoiceId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesInvoiceShipment(ctx.client, params.salesInvoiceId);
      return toMcpResult(result);
    }, "Failed: invoicing_getSalesInvoiceShipment"),
  );

  server.registerTool(
    "invoicing_getSalesInvoiceLines",
    {
      description: "get sales invoice lines",
      inputSchema: z.object({
      salesInvoiceId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesInvoiceLines(ctx.client, params.salesInvoiceId);
      return toMcpResult(result);
    }, "Failed: invoicing_getSalesInvoiceLines"),
  );

  server.registerTool(
    "invoicing_getSalesInvoiceLine",
    {
      description: "get sales invoice line",
      inputSchema: z.object({
      salesInvoiceLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesInvoiceLine(ctx.client, params.salesInvoiceLineId);
      return toMcpResult(result);
    }, "Failed: invoicing_getSalesInvoiceLine"),
  );

  server.registerTool(
    "invoicing_updatePurchaseInvoiceExchangeRate",
    {
      description: "update purchase invoice exchange rate",
      inputSchema: z.object({
      data: z.object({
    id: z.string(),
    exchangeRate: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePurchaseInvoiceExchangeRate(ctx.client, params.data);
      return toMcpResult(result);
    }, "Failed: invoicing_updatePurchaseInvoiceExchangeRate"),
  );

  server.registerTool(
    "invoicing_updatePurchaseInvoiceStatus",
    {
      description: "update purchase invoice status",
      inputSchema: z.object({
      update: z.object({
    id: z.string(),
    status: z.any(),
    assignee: z.any()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePurchaseInvoiceStatus(ctx.client, { ...params.update, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: invoicing_updatePurchaseInvoiceStatus"),
  );

  server.registerTool(
    "invoicing_updateSalesInvoiceExchangeRate",
    {
      description: "update sales invoice exchange rate",
      inputSchema: z.object({
      data: z.object({
    id: z.string(),
    exchangeRate: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSalesInvoiceExchangeRate(ctx.client, params.data);
      return toMcpResult(result);
    }, "Failed: invoicing_updateSalesInvoiceExchangeRate"),
  );

  server.registerTool(
    "invoicing_updateSalesInvoiceStatus",
    {
      description: "update sales invoice status",
      inputSchema: z.object({
      update: z.object({
    id: z.string(),
    status: z.any(),
    assignee: z.any()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSalesInvoiceStatus(ctx.client, { ...params.update, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: invoicing_updateSalesInvoiceStatus"),
  );

  server.registerTool(
    "invoicing_upsertPurchaseInvoice",
    {
      description: "upsert purchase invoice",
      inputSchema: z.object({
      purchaseInvoice: purchaseInvoiceValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPurchaseInvoice(ctx.client, { ...params.purchaseInvoice, companyId: ctx.companyId, companyGroupId: ctx.companyGroupId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: invoicing_upsertPurchaseInvoice"),
  );

  server.registerTool(
    "invoicing_upsertPurchaseInvoiceDelivery",
    {
      description: "upsert purchase invoice delivery",
      inputSchema: z.object({
      purchaseInvoiceDelivery: purchaseInvoiceDeliveryValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPurchaseInvoiceDelivery(ctx.client, { ...params.purchaseInvoiceDelivery, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: invoicing_upsertPurchaseInvoiceDelivery"),
  );

  server.registerTool(
    "invoicing_upsertPurchaseInvoiceLine",
    {
      description: "upsert purchase invoice line",
      inputSchema: z.object({
      purchaseInvoiceLine: purchaseInvoiceLineValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPurchaseInvoiceLine(ctx.client, { ...params.purchaseInvoiceLine, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: invoicing_upsertPurchaseInvoiceLine"),
  );

  server.registerTool(
    "invoicing_upsertSalesInvoice",
    {
      description: "upsert sales invoice",
      inputSchema: z.object({
      salesInvoice: salesInvoiceValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSalesInvoice(ctx.client, { ...params.salesInvoice, companyId: ctx.companyId, companyGroupId: ctx.companyGroupId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: invoicing_upsertSalesInvoice"),
  );

  server.registerTool(
    "invoicing_upsertSalesInvoiceShipment",
    {
      description: "upsert sales invoice shipment",
      inputSchema: z.object({
      salesInvoiceShipment: salesInvoiceShipmentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSalesInvoiceShipment(ctx.client, { ...params.salesInvoiceShipment, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: invoicing_upsertSalesInvoiceShipment"),
  );

  server.registerTool(
    "invoicing_upsertSalesInvoiceLine",
    {
      description: "upsert sales invoice line",
      inputSchema: z.object({
      salesInvoiceLine: salesInvoiceLineValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSalesInvoiceLine(ctx.client, { ...params.salesInvoiceLine, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: invoicing_upsertSalesInvoiceLine"),
  );
};
