// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  deleteAttribute,
  deleteAttributeCategory,
  deleteDepartment,
  deleteHoliday,
  deleteShift,
  getAttribute,
  getAttributeCategories,
  getAttributeCategory,
  getAttributeDataTypes,
  getDepartment,
  getDepartments,
  getDepartmentsList,
  getDepartmentsTree,
  getEmployeeJob,
  getEmployeeSummary,
  getHoliday,
  getHolidays,
  getPeople,
  getContacts,
  getShift,
  getShifts,
  getShiftsList,
  insertAttribute,
  insertAttributeCategory,
  insertEmployeeJob,
  updateAttribute,
  updateAttributeCategory,
  updateAttributeSortOrder,
  updateEmployeeJob,
  upsertDepartment,
  upsertHoliday,
  upsertShift,
  clockIn,
  clockOut,
  createTimeCardEntry,
  deleteTimeCardEntry,
  getClockedInEmployees,
  getOpenClockEntry,
  getRecentTimecards,
  getScheduledEmployeesToday,
  getTimeCardEntry,
  getTimeCardEntries,
  getTimecardEntries,
  getWeeklyHoursForEmployees,
  updateTimeCardEntry,
} from "~/modules/people/people.service";
import {
  employeeJobValidator,
  departmentValidator,
  holidayValidator,
  shiftValidator,
} from "~/modules/people/people.models";

export const registerPeopleTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "people_deleteAttribute",
    {
      description: "delete attribute",
      inputSchema: z.object({
      attributeId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteAttribute(ctx.client, params.attributeId);
      return toMcpResult(result);
    }, "Failed: people_deleteAttribute"),
  );

  server.registerTool(
    "people_deleteAttributeCategory",
    {
      description: "delete attribute category",
      inputSchema: z.object({
      attributeCategoryId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteAttributeCategory(ctx.client, params.attributeCategoryId);
      return toMcpResult(result);
    }, "Failed: people_deleteAttributeCategory"),
  );

  server.registerTool(
    "people_deleteDepartment",
    {
      description: "delete department",
      inputSchema: z.object({
      departmentId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteDepartment(ctx.client, params.departmentId);
      return toMcpResult(result);
    }, "Failed: people_deleteDepartment"),
  );

  server.registerTool(
    "people_deleteHoliday",
    {
      description: "delete holiday",
      inputSchema: z.object({
      holidayId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteHoliday(ctx.client, params.holidayId);
      return toMcpResult(result);
    }, "Failed: people_deleteHoliday"),
  );

  server.registerTool(
    "people_deleteShift",
    {
      description: "delete shift",
      inputSchema: z.object({
      shiftId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteShift(ctx.client, params.shiftId);
      return toMcpResult(result);
    }, "Failed: people_deleteShift"),
  );

  server.registerTool(
    "people_getAttribute",
    {
      description: "get attribute",
      inputSchema: z.object({
      attributeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAttribute(ctx.client, params.attributeId);
      return toMcpResult(result);
    }, "Failed: people_getAttribute"),
  );

  server.registerTool(
    "people_getAttributeCategories",
    {
      description: "get attribute categories",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAttributeCategories(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: people_getAttributeCategories"),
  );

  server.registerTool(
    "people_getAttributeCategory",
    {
      description: "get attribute category",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAttributeCategory(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: people_getAttributeCategory"),
  );

  server.registerTool(
    "people_getAttributeDataTypes",
    {
      description: "get attribute data types",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAttributeDataTypes(ctx.client);
      return toMcpResult(result);
    }, "Failed: people_getAttributeDataTypes"),
  );

  server.registerTool(
    "people_getDepartment",
    {
      description: "get department",
      inputSchema: z.object({
      departmentId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDepartment(ctx.client, params.departmentId);
      return toMcpResult(result);
    }, "Failed: people_getDepartment"),
  );

  server.registerTool(
    "people_getDepartments",
    {
      description: "get departments",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDepartments(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: people_getDepartments"),
  );

  server.registerTool(
    "people_getDepartmentsList",
    {
      description: "get departments list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDepartmentsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: people_getDepartmentsList"),
  );

  server.registerTool(
    "people_getDepartmentsTree",
    {
      description: "get departments tree",
      inputSchema: {},
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDepartmentsTree(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: people_getDepartmentsTree"),
  );

  server.registerTool(
    "people_getEmployeeJob",
    {
      description: "get employee job",
      inputSchema: z.object({
      employeeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getEmployeeJob(ctx.client, params.employeeId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: people_getEmployeeJob"),
  );

  server.registerTool(
    "people_getEmployeeSummary",
    {
      description: "get employee summary",
      inputSchema: z.object({
      employeeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getEmployeeSummary(ctx.client, params.employeeId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: people_getEmployeeSummary"),
  );

  server.registerTool(
    "people_getHoliday",
    {
      description: "get holiday",
      inputSchema: z.object({
      holidayId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getHoliday(ctx.client, params.holidayId);
      return toMcpResult(result);
    }, "Failed: people_getHoliday"),
  );

  server.registerTool(
    "people_getHolidays",
    {
      description: "get holidays",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getHolidays(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: people_getHolidays"),
  );

  server.registerTool(
    "people_getPeople",
    {
      description: "get people",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPeople(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: people_getPeople"),
  );

  server.registerTool(
    "people_getContacts",
    {
      description: "get contacts",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getContacts(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: people_getContacts"),
  );

  server.registerTool(
    "people_getShift",
    {
      description: "get shift",
      inputSchema: z.object({
      shiftId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShift(ctx.client, params.shiftId);
      return toMcpResult(result);
    }, "Failed: people_getShift"),
  );

  server.registerTool(
    "people_getShifts",
    {
      description: "get shifts",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShifts(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: people_getShifts"),
  );

  server.registerTool(
    "people_getShiftsList",
    {
      description: "get shifts list",
      inputSchema: z.object({
      locationId: z.string().nullable(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getShiftsList(ctx.client, params.locationId);
      return toMcpResult(result);
    }, "Failed: people_getShiftsList"),
  );

  server.registerTool(
    "people_insertAttribute",
    {
      description: "insert attribute",
      inputSchema: z.object({
      attribute: z.object({
    name: z.string(),
    attributeDataTypeId: z.number(),
    userAttributeCategoryId: z.string(),
    listOptions: z.array(z.string()).optional(),
    canSelfManage: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertAttribute(ctx.client, { ...params.attribute, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_insertAttribute"),
  );

  server.registerTool(
    "people_insertAttributeCategory",
    {
      description: "insert attribute category",
      inputSchema: z.object({
      attributeCategory: z.object({
    name: z.string(),
    emoji: z.string().optional(),
    public: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertAttributeCategory(ctx.client, { ...params.attributeCategory, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_insertAttributeCategory"),
  );

  server.registerTool(
    "people_insertEmployeeJob",
    {
      description: "insert employee job",
      inputSchema: z.object({
      job: z.object({
    id: z.string(),
    locationId: z.string().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertEmployeeJob(ctx.client, { ...params.job, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: people_insertEmployeeJob"),
  );

  server.registerTool(
    "people_updateAttribute",
    {
      description: "update attribute",
      inputSchema: z.object({
      attribute: z.object({
    id: z.string().optional(),
    name: z.string(),
    listOptions: z.array(z.string()).optional(),
    canSelfManage: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateAttribute(ctx.client, { ...params.attribute, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_updateAttribute"),
  );

  server.registerTool(
    "people_updateAttributeCategory",
    {
      description: "update attribute category",
      inputSchema: z.object({
      attributeCategory: z.object({
    id: z.string(),
    name: z.string(),
    emoji: z.string().optional(),
    public: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateAttributeCategory(ctx.client, { ...params.attributeCategory, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_updateAttributeCategory"),
  );

  server.registerTool(
    "people_updateAttributeSortOrder",
    {
      description: "update attribute sort order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    sortOrder: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateAttributeSortOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_updateAttributeSortOrder"),
  );

  server.registerTool(
    "people_updateEmployeeJob",
    {
      description: "update employee job",
      inputSchema: z.object({
      employeeId: z.string(),
      employeeJob: employeeJobValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateEmployeeJob(ctx.client, params.employeeId, { ...params.employeeJob, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_updateEmployeeJob"),
  );

  server.registerTool(
    "people_upsertDepartment",
    {
      description: "upsert department",
      inputSchema: z.object({
      department: departmentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertDepartment(ctx.client, { ...params.department, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_upsertDepartment"),
  );

  server.registerTool(
    "people_upsertHoliday",
    {
      description: "upsert holiday",
      inputSchema: z.object({
      holiday: holidayValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertHoliday(ctx.client, { ...params.holiday, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_upsertHoliday"),
  );

  server.registerTool(
    "people_upsertShift",
    {
      description: "upsert shift",
      inputSchema: z.object({
      shift: shiftValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertShift(ctx.client, { ...params.shift, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_upsertShift"),
  );

  server.registerTool(
    "people_clockIn",
    {
      description: "clock in",
      inputSchema: z.object({
      args: z.object({
    employeeId: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await clockIn(ctx.client, { ...params.args, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_clockIn"),
  );

  server.registerTool(
    "people_clockOut",
    {
      description: "clock out",
      inputSchema: z.object({
      args: z.object({
    employeeId: z.string(),
    clockOut: z.string().optional(),
    note: z.string().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await clockOut(ctx.client, { ...params.args, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_clockOut"),
  );

  server.registerTool(
    "people_createTimeCardEntry",
    {
      description: "create time card entry",
      inputSchema: z.object({
      entry: z.object({
    employeeId: z.string(),
    clockIn: z.string(),
    clockOut: z.string().nullable().optional(),
    note: z.string().nullable().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createTimeCardEntry(ctx.client, { ...params.entry, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_createTimeCardEntry"),
  );

  server.registerTool(
    "people_deleteTimeCardEntry",
    {
      description: "delete time card entry",
      inputSchema: z.object({
      entryId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteTimeCardEntry(ctx.client, params.entryId);
      return toMcpResult(result);
    }, "Failed: people_deleteTimeCardEntry"),
  );

  server.registerTool(
    "people_getClockedInEmployees",
    {
      description: "get clocked in employees",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getClockedInEmployees(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: people_getClockedInEmployees"),
  );

  server.registerTool(
    "people_getOpenClockEntry",
    {
      description: "get open clock entry",
      inputSchema: z.object({
      employeeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getOpenClockEntry(ctx.client, params.employeeId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: people_getOpenClockEntry"),
  );

  server.registerTool(
    "people_getRecentTimecards",
    {
      description: "get recent timecards",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getRecentTimecards(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: people_getRecentTimecards"),
  );

  server.registerTool(
    "people_getScheduledEmployeesToday",
    {
      description: "get scheduled employees today",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getScheduledEmployeesToday(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: people_getScheduledEmployeesToday"),
  );

  server.registerTool(
    "people_getTimeCardEntry",
    {
      description: "get time card entry",
      inputSchema: z.object({
      entryId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTimeCardEntry(ctx.client, params.entryId);
      return toMcpResult(result);
    }, "Failed: people_getTimeCardEntry"),
  );

  server.registerTool(
    "people_getTimeCardEntries",
    {
      description: "get time card entries",
      inputSchema: z.object({
      args: z.object({
    employeeId: z.string(),
    from: z.string().optional(),
    to: z.string().optional()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTimeCardEntries(ctx.client, { ...params.args, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: people_getTimeCardEntries"),
  );

  server.registerTool(
    "people_getTimecardEntries",
    {
      description: "get timecard entries",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTimecardEntries(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: people_getTimecardEntries"),
  );

  server.registerTool(
    "people_getWeeklyHoursForEmployees",
    {
      description: "get weekly hours for employees",
      inputSchema: z.object({
      employeeIds: z.array(z.string()),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWeeklyHoursForEmployees(ctx.client, ctx.companyId, params.employeeIds);
      return toMcpResult(result);
    }, "Failed: people_getWeeklyHoursForEmployees"),
  );

  server.registerTool(
    "people_updateTimeCardEntry",
    {
      description: "update time card entry",
      inputSchema: z.object({
      args: z.object({
    entryId: z.string(),
    clockIn: z.string().optional(),
    clockOut: z.string().nullable().optional(),
    note: z.string().nullable().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateTimeCardEntry(ctx.client, { ...params.args, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: people_updateTimeCardEntry"),
  );
};
