// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  convertSalesOrderLinesToJobs,
  calculateJobPriority,
  deleteDemandForecasts,
  deleteDemandProjections,
  deleteJob,
  deleteJobMaterial,
  deleteJobOperation,
  deleteJobOperationStep,
  deleteJobOperationParameter,
  deleteJobOperationTool,
  deleteProcedure,
  deleteProcedureStep,
  deleteProcedureParameter,
  deleteProductionEvent,
  deleteProductionQuantity,
  getActiveJobOperationByJobId,
  getActiveJobOperationsByLocation,
  getJobsByDateRange,
  getUnscheduledJobs,
  getActiveProductionEvents,
  deleteScrapReason,
  deleteFailureMode,
  deleteMaintenanceDispatch,
  deleteMaintenanceDispatchComment,
  deleteMaintenanceDispatchEvent,
  deleteMaintenanceDispatchItem,
  deleteMaintenanceDispatchWorkCenter,
  deleteMaintenanceSchedule,
  deleteMaintenanceScheduleItem,
  getDemandForecasts,
  getDemandProjections,
  getJobDocuments,
  getJobDocumentsWithItemId,
  getJob,
  getJobByOperationId,
  getJobPurchaseOrderLines,
  getJobs,
  getJobsBySalesOrderLine,
  getJobsList,
  getJobMakeMethodById,
  getRootMakeMethod,
  getJobMaterialsWithQuantityOnHand,
  getJobMethodTree,
  getJobMethodTreeArray,
  getJobMaterial,
  getJobMaterialsByMethodId,
  getJobOperation,
  getJobOperations,
  getJobOperationsAssignedToEmployee,
  getJobOperationAttachments,
  getJobOperationsList,
  getJobOperationsByMethodId,
  getJobOperationStepRecords,
  getOutsideOperationsByJobId,
  getProcedure,
  getProcedureSteps,
  getProcedureParameters,
  getProcedureVersions,
  getProcedures,
  getProceduresList,
  getProductionEvent,
  getProductionEvents,
  getProductionEventsPage,
  getProductionEventsByOperations,
  getProductionPlanning,
  getProductionProjections,
  getProductionQuantity,
  getProductionQuantities,
  getProductionDataByOperations,
  getScrapReasonsList,
  getScrapReason,
  getScrapReasons,
  getFailureMode,
  getFailureModes,
  getFailureModesList,
  getMaintenanceDispatch,
  getMaintenanceDispatches,
  getMaintenanceDispatchComments,
  getMaintenanceDispatchEvents,
  getMaintenanceDispatchItems,
  getMaintenanceDispatchWorkCenters,
  getMaintenanceSchedule,
  getMaintenanceSchedules,
  getMaintenanceScheduleItems,
  getTrackedEntityByJobId,
  getTrackedEntitiesByJobId,
  recalculateJobOperationDependencies,
  recalculateJobRequirements,
  recalculateJobMakeMethodRequirements,
  runMRP,
  updateJobBatchNumber,
  updateJobStatus,
  updateJobMaterialOrder,
  updateJobOperationOrder,
  updateJobOperationStepOrder,
  updateKanbanJob,
  updateQuoteOperationStepOrder,
  updateMethodOperationStepOrder,
  updateJobOperationStatus,
  updateJobOperationDueDate,
  updateProcedureStepOrder,
  upsertProductionEvent,
  updateProductionQuantity,
  upsertProductionQuantity,
  upsertJob,
  upsertJobMaterial,
  upsertJobOperation,
  upsertJobOperationStep,
  upsertJobOperationParameter,
  upsertJobOperationTool,
  upsertJobMethod,
  upsertJobMaterialMakeMethod,
  upsertMakeMethodFromJob,
  upsertMakeMethodFromJobMethod,
  upsertProcedure,
  upsertProcedureStep,
  upsertProcedureParameter,
  upsertScrapReason,
  upsertFailureMode,
  upsertMaintenanceDispatch,
  upsertMaintenanceDispatchComment,
  upsertMaintenanceDispatchEvent,
  upsertMaintenanceDispatchItem,
  upsertMaintenanceDispatchWorkCenter,
  upsertMaintenanceSchedule,
  upsertMaintenanceScheduleItem,
  upsertDemandForecasts,
  upsertDemandProjections,
  triggerJobSchedule,
} from "~/modules/production/production.service";
import {
  productionEventValidator,
  productionQuantityValidator,
  jobValidator,
  jobMaterialValidator,
  jobOperationValidator,
  procedureValidator,
  procedureStepValidator,
  procedureParameterValidator,
  scrapReasonValidator,
  failureModeValidator,
  maintenanceDispatchValidator,
  maintenanceDispatchCommentValidator,
  maintenanceDispatchEventValidator,
  maintenanceDispatchItemValidator,
  maintenanceDispatchWorkCenterValidator,
  maintenanceScheduleValidator,
  maintenanceScheduleItemValidator,
} from "~/modules/production/production.models";
import {
  operationStepValidator,
  operationParameterValidator,
  operationToolValidator,
} from "~/modules/shared";

export const registerProductionTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "production_convertSalesOrderLinesToJobs",
    {
      description: "convert sales order lines to jobs",
      inputSchema: z.object({
      arg1: z.object({
    orderId: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await convertSalesOrderLinesToJobs(ctx.client, { ...params.arg1, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_convertSalesOrderLinesToJobs"),
  );

  server.registerTool(
    "production_calculateJobPriority",
    {
      description: "calculate job priority",
      inputSchema: z.object({
      params: z.object({
    jobId: z.string().optional(),
    dueDate: z.string().nullable(),
    deadlineType: z.any(),
    locationId: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await calculateJobPriority(ctx.client, { ...params.params, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: production_calculateJobPriority"),
  );

  server.registerTool(
    "production_deleteDemandForecasts",
    {
      description: "delete demand forecasts",
      inputSchema: z.object({
      params: z.object({
    itemId: z.string(),
    locationId: z.string(),
    futurePeriodIds: z.array(z.string())
  }),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteDemandForecasts(ctx.client, { ...params.params, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: production_deleteDemandForecasts"),
  );

  server.registerTool(
    "production_deleteDemandProjections",
    {
      description: "delete demand projections",
      inputSchema: z.object({
      params: z.object({
    itemId: z.string(),
    locationId: z.string(),
    futurePeriodIds: z.array(z.string())
  }),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteDemandProjections(ctx.client, { ...params.params, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: production_deleteDemandProjections"),
  );

  server.registerTool(
    "production_deleteJob",
    {
      description: "delete job",
      inputSchema: z.object({
      jobId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteJob(ctx.client, params.jobId);
      return toMcpResult(result);
    }, "Failed: production_deleteJob"),
  );

  server.registerTool(
    "production_deleteJobMaterial",
    {
      description: "delete job material",
      inputSchema: z.object({
      jobMaterialId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteJobMaterial(ctx.client, params.jobMaterialId);
      return toMcpResult(result);
    }, "Failed: production_deleteJobMaterial"),
  );

  server.registerTool(
    "production_deleteJobOperation",
    {
      description: "delete job operation",
      inputSchema: z.object({
      jobOperationId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteJobOperation(ctx.client, params.jobOperationId);
      return toMcpResult(result);
    }, "Failed: production_deleteJobOperation"),
  );

  server.registerTool(
    "production_deleteJobOperationStep",
    {
      description: "delete job operation step",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteJobOperationStep(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: production_deleteJobOperationStep"),
  );

  server.registerTool(
    "production_deleteJobOperationParameter",
    {
      description: "delete job operation parameter",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteJobOperationParameter(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: production_deleteJobOperationParameter"),
  );

  server.registerTool(
    "production_deleteJobOperationTool",
    {
      description: "delete job operation tool",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteJobOperationTool(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: production_deleteJobOperationTool"),
  );

  server.registerTool(
    "production_deleteProcedure",
    {
      description: "delete procedure",
      inputSchema: z.object({
      procedureId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteProcedure(ctx.client, params.procedureId);
      return toMcpResult(result);
    }, "Failed: production_deleteProcedure"),
  );

  server.registerTool(
    "production_deleteProcedureStep",
    {
      description: "delete procedure step",
      inputSchema: z.object({
      procedureStepId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteProcedureStep(ctx.client, params.procedureStepId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_deleteProcedureStep"),
  );

  server.registerTool(
    "production_deleteProcedureParameter",
    {
      description: "delete procedure parameter",
      inputSchema: z.object({
      procedureParameterId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteProcedureParameter(ctx.client, params.procedureParameterId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_deleteProcedureParameter"),
  );

  server.registerTool(
    "production_deleteProductionEvent",
    {
      description: "delete production event",
      inputSchema: z.object({
      productionEventId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteProductionEvent(ctx.client, params.productionEventId);
      return toMcpResult(result);
    }, "Failed: production_deleteProductionEvent"),
  );

  server.registerTool(
    "production_deleteProductionQuantity",
    {
      description: "delete production quantity",
      inputSchema: z.object({
      productionQuantityId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteProductionQuantity(ctx.client, params.productionQuantityId);
      return toMcpResult(result);
    }, "Failed: production_deleteProductionQuantity"),
  );

  server.registerTool(
    "production_getActiveJobOperationByJobId",
    {
      description: "get active job operation by job id",
      inputSchema: z.object({
      jobId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getActiveJobOperationByJobId(ctx.client, params.jobId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_getActiveJobOperationByJobId"),
  );

  server.registerTool(
    "production_getActiveJobOperationsByLocation",
    {
      description: "get active job operations by location",
      inputSchema: z.object({
      locationId: z.string(),
      workCenterIds: z.array(z.string()).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getActiveJobOperationsByLocation(ctx.client, params.locationId, params.workCenterIds);
      return toMcpResult(result);
    }, "Failed: production_getActiveJobOperationsByLocation"),
  );

  server.registerTool(
    "production_getJobsByDateRange",
    {
      description: "get jobs by date range",
      inputSchema: z.object({
      locationId: z.string(),
      startDate: z.string(),
      endDate: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobsByDateRange(ctx.client, params.locationId, params.startDate, params.endDate);
      return toMcpResult(result);
    }, "Failed: production_getJobsByDateRange"),
  );

  server.registerTool(
    "production_getUnscheduledJobs",
    {
      description: "get unscheduled jobs",
      inputSchema: z.object({
      locationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getUnscheduledJobs(ctx.client, params.locationId);
      return toMcpResult(result);
    }, "Failed: production_getUnscheduledJobs"),
  );

  server.registerTool(
    "production_getActiveProductionEvents",
    {
      description: "get active production events",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getActiveProductionEvents(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_getActiveProductionEvents"),
  );

  server.registerTool(
    "production_deleteScrapReason",
    {
      description: "delete scrap reason",
      inputSchema: z.object({
      scrapReasonId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteScrapReason(ctx.client, params.scrapReasonId);
      return toMcpResult(result);
    }, "Failed: production_deleteScrapReason"),
  );

  server.registerTool(
    "production_deleteFailureMode",
    {
      description: "delete failure mode",
      inputSchema: z.object({
      failureModeId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteFailureMode(ctx.client, params.failureModeId);
      return toMcpResult(result);
    }, "Failed: production_deleteFailureMode"),
  );

  server.registerTool(
    "production_deleteMaintenanceDispatch",
    {
      description: "delete maintenance dispatch",
      inputSchema: z.object({
      dispatchId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceDispatch(ctx.client, params.dispatchId);
      return toMcpResult(result);
    }, "Failed: production_deleteMaintenanceDispatch"),
  );

  server.registerTool(
    "production_deleteMaintenanceDispatchComment",
    {
      description: "delete maintenance dispatch comment",
      inputSchema: z.object({
      commentId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceDispatchComment(ctx.client, params.commentId);
      return toMcpResult(result);
    }, "Failed: production_deleteMaintenanceDispatchComment"),
  );

  server.registerTool(
    "production_deleteMaintenanceDispatchEvent",
    {
      description: "delete maintenance dispatch event",
      inputSchema: z.object({
      eventId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceDispatchEvent(ctx.client, params.eventId);
      return toMcpResult(result);
    }, "Failed: production_deleteMaintenanceDispatchEvent"),
  );

  server.registerTool(
    "production_deleteMaintenanceDispatchItem",
    {
      description: "delete maintenance dispatch item",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceDispatchItem(ctx.client, params.itemId);
      return toMcpResult(result);
    }, "Failed: production_deleteMaintenanceDispatchItem"),
  );

  server.registerTool(
    "production_deleteMaintenanceDispatchWorkCenter",
    {
      description: "delete maintenance dispatch work center",
      inputSchema: z.object({
      workCenterId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceDispatchWorkCenter(ctx.client, params.workCenterId);
      return toMcpResult(result);
    }, "Failed: production_deleteMaintenanceDispatchWorkCenter"),
  );

  server.registerTool(
    "production_deleteMaintenanceSchedule",
    {
      description: "delete maintenance schedule",
      inputSchema: z.object({
      scheduleId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceSchedule(ctx.client, params.scheduleId);
      return toMcpResult(result);
    }, "Failed: production_deleteMaintenanceSchedule"),
  );

  server.registerTool(
    "production_deleteMaintenanceScheduleItem",
    {
      description: "delete maintenance schedule item",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteMaintenanceScheduleItem(ctx.client, params.itemId);
      return toMcpResult(result);
    }, "Failed: production_deleteMaintenanceScheduleItem"),
  );

  server.registerTool(
    "production_getDemandForecasts",
    {
      description: "get demand forecasts",
      inputSchema: z.object({
      params: z.object({
    itemId: z.string(),
    locationId: z.string(),
    periodIds: z.array(z.string())
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDemandForecasts(ctx.client, { ...params.params, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: production_getDemandForecasts"),
  );

  server.registerTool(
    "production_getDemandProjections",
    {
      description: "get demand projections",
      inputSchema: z.object({
      params: z.object({
    itemId: z.string(),
    locationId: z.string(),
    periodIds: z.array(z.string())
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDemandProjections(ctx.client, { ...params.params, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: production_getDemandProjections"),
  );

  server.registerTool(
    "production_getJobDocuments",
    {
      description: "get job documents",
      inputSchema: z.object({
      job: z.object({
    id: z.string().nullable(),
    salesOrderLineId: z.string().nullable().optional(),
    quoteLineId: z.string().nullable().optional(),
    itemId: z.string().nullable().optional()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobDocuments(ctx.client, ctx.companyId, params.job);
      return toMcpResult(result);
    }, "Failed: production_getJobDocuments"),
  );

  server.registerTool(
    "production_getJobDocumentsWithItemId",
    {
      description: "get job documents with item id",
      inputSchema: z.object({
      job: z.any(),
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobDocumentsWithItemId(ctx.client, ctx.companyId, params.job, params.itemId);
      return toMcpResult(result);
    }, "Failed: production_getJobDocumentsWithItemId"),
  );

  server.registerTool(
    "production_getJob",
    {
      description: "get job",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJob(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: production_getJob"),
  );

  server.registerTool(
    "production_getJobByOperationId",
    {
      description: "get job by operation id",
      inputSchema: z.object({
      operationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobByOperationId(ctx.client, params.operationId);
      return toMcpResult(result);
    }, "Failed: production_getJobByOperationId"),
  );

  server.registerTool(
    "production_getJobPurchaseOrderLines",
    {
      description: "get job purchase order lines",
      inputSchema: z.object({
      jobId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobPurchaseOrderLines(ctx.client, params.jobId);
      return toMcpResult(result);
    }, "Failed: production_getJobPurchaseOrderLines"),
  );

  server.registerTool(
    "production_getJobs",
    {
      description: "get jobs",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobs(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: production_getJobs"),
  );

  server.registerTool(
    "production_getJobsBySalesOrderLine",
    {
      description: "get jobs by sales order line",
      inputSchema: z.object({
      salesOrderLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobsBySalesOrderLine(ctx.client, params.salesOrderLineId);
      return toMcpResult(result);
    }, "Failed: production_getJobsBySalesOrderLine"),
  );

  server.registerTool(
    "production_getJobsList",
    {
      description: "get jobs list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_getJobsList"),
  );

  server.registerTool(
    "production_getJobMakeMethodById",
    {
      description: "get job make method by id",
      inputSchema: z.object({
      jobMakeMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobMakeMethodById(ctx.client, params.jobMakeMethodId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_getJobMakeMethodById"),
  );

  server.registerTool(
    "production_getRootMakeMethod",
    {
      description: "get root make method",
      inputSchema: z.object({
      jobId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getRootMakeMethod(ctx.client, params.jobId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_getRootMakeMethod"),
  );

  server.registerTool(
    "production_getJobMaterialsWithQuantityOnHand",
    {
      description: "get job materials with quantity on hand",
      inputSchema: z.object({
      jobId: z.string(),
      locationId: z.string(),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobMaterialsWithQuantityOnHand(ctx.client, params.jobId, ctx.companyId, params.locationId, params.args);
      return toMcpResult(result);
    }, "Failed: production_getJobMaterialsWithQuantityOnHand"),
  );

  server.registerTool(
    "production_getJobMethodTree",
    {
      description: "get job method tree",
      inputSchema: z.object({
      jobId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobMethodTree(ctx.client, params.jobId);
      return toMcpResult(result);
    }, "Failed: production_getJobMethodTree"),
  );

  server.registerTool(
    "production_getJobMethodTreeArray",
    {
      description: "get job method tree array",
      inputSchema: z.object({
      jobId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobMethodTreeArray(ctx.client, params.jobId);
      return toMcpResult(result);
    }, "Failed: production_getJobMethodTreeArray"),
  );

  server.registerTool(
    "production_getJobMaterial",
    {
      description: "get job material",
      inputSchema: z.object({
      materialId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobMaterial(ctx.client, params.materialId);
      return toMcpResult(result);
    }, "Failed: production_getJobMaterial"),
  );

  server.registerTool(
    "production_getJobMaterialsByMethodId",
    {
      description: "get job materials by method id",
      inputSchema: z.object({
      jobMakeMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobMaterialsByMethodId(ctx.client, params.jobMakeMethodId);
      return toMcpResult(result);
    }, "Failed: production_getJobMaterialsByMethodId"),
  );

  server.registerTool(
    "production_getJobOperation",
    {
      description: "get job operation",
      inputSchema: z.object({
      jobOperationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobOperation(ctx.client, params.jobOperationId);
      return toMcpResult(result);
    }, "Failed: production_getJobOperation"),
  );

  server.registerTool(
    "production_getJobOperations",
    {
      description: "get job operations",
      inputSchema: z.object({
      jobId: z.string(),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobOperations(ctx.client, params.jobId, params.args);
      return toMcpResult(result);
    }, "Failed: production_getJobOperations"),
  );

  server.registerTool(
    "production_getJobOperationsAssignedToEmployee",
    {
      description: "get job operations assigned to employee",
      inputSchema: z.object({
      employeeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobOperationsAssignedToEmployee(ctx.client, params.employeeId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_getJobOperationsAssignedToEmployee"),
  );

  server.registerTool(
    "production_getJobOperationAttachments",
    {
      description: "get job operation attachments",
      inputSchema: z.object({
      jobOperationIds: z.array(z.string()),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobOperationAttachments(ctx.client, params.jobOperationIds);
      return toMcpResult(result);
    }, "Failed: production_getJobOperationAttachments"),
  );

  server.registerTool(
    "production_getJobOperationsList",
    {
      description: "get job operations list",
      inputSchema: z.object({
      jobId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobOperationsList(ctx.client, params.jobId);
      return toMcpResult(result);
    }, "Failed: production_getJobOperationsList"),
  );

  server.registerTool(
    "production_getJobOperationsByMethodId",
    {
      description: "get job operations by method id",
      inputSchema: z.object({
      jobMakeMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobOperationsByMethodId(ctx.client, params.jobMakeMethodId);
      return toMcpResult(result);
    }, "Failed: production_getJobOperationsByMethodId"),
  );

  server.registerTool(
    "production_getJobOperationStepRecords",
    {
      description: "get job operation step records",
      inputSchema: z.object({
      jobId: z.string(),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getJobOperationStepRecords(ctx.client, params.jobId, params.args);
      return toMcpResult(result);
    }, "Failed: production_getJobOperationStepRecords"),
  );

  server.registerTool(
    "production_getOutsideOperationsByJobId",
    {
      description: "get outside operations by job id",
      inputSchema: z.object({
      jobId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getOutsideOperationsByJobId(ctx.client, params.jobId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_getOutsideOperationsByJobId"),
  );

  server.registerTool(
    "production_getProcedure",
    {
      description: "get procedure",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProcedure(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: production_getProcedure"),
  );

  server.registerTool(
    "production_getProcedureSteps",
    {
      description: "get procedure steps",
      inputSchema: z.object({
      procedureId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProcedureSteps(ctx.client, params.procedureId);
      return toMcpResult(result);
    }, "Failed: production_getProcedureSteps"),
  );

  server.registerTool(
    "production_getProcedureParameters",
    {
      description: "get procedure parameters",
      inputSchema: z.object({
      procedureId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProcedureParameters(ctx.client, params.procedureId);
      return toMcpResult(result);
    }, "Failed: production_getProcedureParameters"),
  );

  server.registerTool(
    "production_getProcedureVersions",
    {
      description: "get procedure versions",
      inputSchema: z.object({
      procedure: z.object({
    name: z.string(),
    version: z.number()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProcedureVersions(ctx.client, params.procedure, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_getProcedureVersions"),
  );

  server.registerTool(
    "production_getProcedures",
    {
      description: "get procedures",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProcedures(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: production_getProcedures"),
  );

  server.registerTool(
    "production_getProceduresList",
    {
      description: "get procedures list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProceduresList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_getProceduresList"),
  );

  server.registerTool(
    "production_getProductionEvent",
    {
      description: "get production event",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProductionEvent(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: production_getProductionEvent"),
  );

  server.registerTool(
    "production_getProductionEvents",
    {
      description: "get production events",
      inputSchema: z.object({
      jobOperationIds: z.array(z.string()),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProductionEvents(ctx.client, params.jobOperationIds, params.args);
      return toMcpResult(result);
    }, "Failed: production_getProductionEvents"),
  );

  server.registerTool(
    "production_getProductionEventsPage",
    {
      description: "get production events page",
      inputSchema: z.object({
      jobOperationId: z.string(),
      sortDescending: z.boolean().optional(),
      page: z.number().optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProductionEventsPage(ctx.client, params.jobOperationId, ctx.companyId, params.sortDescending, params.page);
      return toMcpResult(result);
    }, "Failed: production_getProductionEventsPage"),
  );

  server.registerTool(
    "production_getProductionEventsByOperations",
    {
      description: "get production events by operations",
      inputSchema: z.object({
      jobOperationIds: z.array(z.string()),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProductionEventsByOperations(ctx.client, params.jobOperationIds);
      return toMcpResult(result);
    }, "Failed: production_getProductionEventsByOperations"),
  );

  server.registerTool(
    "production_getProductionPlanning",
    {
      description: "get production planning",
      inputSchema: z.object({
      locationId: z.string(),
      periods: z.array(z.string()),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProductionPlanning(ctx.client, params.locationId, ctx.companyId, params.periods, params.args);
      return toMcpResult(result);
    }, "Failed: production_getProductionPlanning"),
  );

  server.registerTool(
    "production_getProductionProjections",
    {
      description: "get production projections",
      inputSchema: z.object({
      locationId: z.string(),
      periods: z.array(z.string()),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProductionProjections(ctx.client, params.locationId, params.periods, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: production_getProductionProjections"),
  );

  server.registerTool(
    "production_getProductionQuantity",
    {
      description: "get production quantity",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProductionQuantity(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: production_getProductionQuantity"),
  );

  server.registerTool(
    "production_getProductionQuantities",
    {
      description: "get production quantities",
      inputSchema: z.object({
      jobOperationIds: z.array(z.string()),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProductionQuantities(ctx.client, params.jobOperationIds, params.args);
      return toMcpResult(result);
    }, "Failed: production_getProductionQuantities"),
  );

  server.registerTool(
    "production_getProductionDataByOperations",
    {
      description: "get production data by operations",
      inputSchema: z.object({
      jobOperationIds: z.array(z.string()),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getProductionDataByOperations(ctx.client, params.jobOperationIds);
      return toMcpResult(result);
    }, "Failed: production_getProductionDataByOperations"),
  );

  server.registerTool(
    "production_getScrapReasonsList",
    {
      description: "get scrap reasons list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getScrapReasonsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_getScrapReasonsList"),
  );

  server.registerTool(
    "production_getScrapReason",
    {
      description: "get scrap reason",
      inputSchema: z.object({
      scrapReasonId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getScrapReason(ctx.client, params.scrapReasonId);
      return toMcpResult(result);
    }, "Failed: production_getScrapReason"),
  );

  server.registerTool(
    "production_getScrapReasons",
    {
      description: "get scrap reasons",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getScrapReasons(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: production_getScrapReasons"),
  );

  server.registerTool(
    "production_getFailureMode",
    {
      description: "get failure mode",
      inputSchema: z.object({
      failureModeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getFailureMode(ctx.client, params.failureModeId);
      return toMcpResult(result);
    }, "Failed: production_getFailureMode"),
  );

  server.registerTool(
    "production_getFailureModes",
    {
      description: "get failure modes",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getFailureModes(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: production_getFailureModes"),
  );

  server.registerTool(
    "production_getFailureModesList",
    {
      description: "get failure modes list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getFailureModesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: production_getFailureModesList"),
  );

  server.registerTool(
    "production_getMaintenanceDispatch",
    {
      description: "get maintenance dispatch",
      inputSchema: z.object({
      dispatchId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatch(ctx.client, params.dispatchId);
      return toMcpResult(result);
    }, "Failed: production_getMaintenanceDispatch"),
  );

  server.registerTool(
    "production_getMaintenanceDispatches",
    {
      description: "get maintenance dispatches",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    status: z.string().optional()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatches(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: production_getMaintenanceDispatches"),
  );

  server.registerTool(
    "production_getMaintenanceDispatchComments",
    {
      description: "get maintenance dispatch comments",
      inputSchema: z.object({
      dispatchId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatchComments(ctx.client, params.dispatchId);
      return toMcpResult(result);
    }, "Failed: production_getMaintenanceDispatchComments"),
  );

  server.registerTool(
    "production_getMaintenanceDispatchEvents",
    {
      description: "get maintenance dispatch events",
      inputSchema: z.object({
      dispatchId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatchEvents(ctx.client, params.dispatchId);
      return toMcpResult(result);
    }, "Failed: production_getMaintenanceDispatchEvents"),
  );

  server.registerTool(
    "production_getMaintenanceDispatchItems",
    {
      description: "get maintenance dispatch items",
      inputSchema: z.object({
      dispatchId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatchItems(ctx.client, params.dispatchId);
      return toMcpResult(result);
    }, "Failed: production_getMaintenanceDispatchItems"),
  );

  server.registerTool(
    "production_getMaintenanceDispatchWorkCenters",
    {
      description: "get maintenance dispatch work centers",
      inputSchema: z.object({
      dispatchId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceDispatchWorkCenters(ctx.client, params.dispatchId);
      return toMcpResult(result);
    }, "Failed: production_getMaintenanceDispatchWorkCenters"),
  );

  server.registerTool(
    "production_getMaintenanceSchedule",
    {
      description: "get maintenance schedule",
      inputSchema: z.object({
      scheduleId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceSchedule(ctx.client, params.scheduleId);
      return toMcpResult(result);
    }, "Failed: production_getMaintenanceSchedule"),
  );

  server.registerTool(
    "production_getMaintenanceSchedules",
    {
      description: "get maintenance schedules",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    active: z.boolean().optional()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceSchedules(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: production_getMaintenanceSchedules"),
  );

  server.registerTool(
    "production_getMaintenanceScheduleItems",
    {
      description: "get maintenance schedule items",
      inputSchema: z.object({
      scheduleId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getMaintenanceScheduleItems(ctx.client, params.scheduleId);
      return toMcpResult(result);
    }, "Failed: production_getMaintenanceScheduleItems"),
  );

  server.registerTool(
    "production_getTrackedEntityByJobId",
    {
      description: "get tracked entity by job id",
      inputSchema: z.object({
      jobId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrackedEntityByJobId(ctx.client, params.jobId);
      return toMcpResult(result);
    }, "Failed: production_getTrackedEntityByJobId"),
  );

  server.registerTool(
    "production_getTrackedEntitiesByJobId",
    {
      description: "get tracked entities by job id",
      inputSchema: z.object({
      jobId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTrackedEntitiesByJobId(ctx.client, params.jobId);
      return toMcpResult(result);
    }, "Failed: production_getTrackedEntitiesByJobId"),
  );

  server.registerTool(
    "production_recalculateJobOperationDependencies",
    {
      description: "recalculate job operation dependencies",
      inputSchema: z.object({
      params: z.object({
    jobId: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await recalculateJobOperationDependencies(ctx.client, { ...params.params, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_recalculateJobOperationDependencies"),
  );

  server.registerTool(
    "production_recalculateJobRequirements",
    {
      description: "recalculate job requirements",
      inputSchema: z.object({
      params: z.object({
    id: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await recalculateJobRequirements(ctx.client, { ...params.params, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_recalculateJobRequirements"),
  );

  server.registerTool(
    "production_recalculateJobMakeMethodRequirements",
    {
      description: "recalculate job make method requirements",
      inputSchema: z.object({
      params: z.object({
    id: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await recalculateJobMakeMethodRequirements(ctx.client, { ...params.params, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_recalculateJobMakeMethodRequirements"),
  );

  server.registerTool(
    "production_runMRP",
    {
      description: "run m r p",
      inputSchema: z.object({
      params: z.object({
    type: z.any(),
    id: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await runMRP(ctx.client, { ...params.params, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_runMRP"),
  );

  server.registerTool(
    "production_updateJobBatchNumber",
    {
      description: "update job batch number",
      inputSchema: z.object({
      trackedEntityId: z.string(),
      value: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateJobBatchNumber(ctx.client, params.trackedEntityId, params.value);
      return toMcpResult(result);
    }, "Failed: production_updateJobBatchNumber"),
  );

  server.registerTool(
    "production_updateJobStatus",
    {
      description: "update job status",
      inputSchema: z.object({
      params: z.object({
    id: z.string(),
    status: z.any(),
    assignee: z.string().nullable().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateJobStatus(ctx.client, { ...params.params, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_updateJobStatus"),
  );

  server.registerTool(
    "production_updateJobMaterialOrder",
    {
      description: "update job material order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    order: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateJobMaterialOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_updateJobMaterialOrder"),
  );

  server.registerTool(
    "production_updateJobOperationOrder",
    {
      description: "update job operation order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    order: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateJobOperationOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_updateJobOperationOrder"),
  );

  server.registerTool(
    "production_updateJobOperationStepOrder",
    {
      description: "update job operation step order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    sortOrder: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateJobOperationStepOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_updateJobOperationStepOrder"),
  );

  server.registerTool(
    "production_updateKanbanJob",
    {
      description: "update kanban job",
      inputSchema: z.object({
      params: z.object({
    id: z.string(),
    jobId: z.string().nullable()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateKanbanJob(ctx.client, { ...params.params, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_updateKanbanJob"),
  );

  server.registerTool(
    "production_updateQuoteOperationStepOrder",
    {
      description: "update quote operation step order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    sortOrder: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateQuoteOperationStepOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_updateQuoteOperationStepOrder"),
  );

  server.registerTool(
    "production_updateMethodOperationStepOrder",
    {
      description: "update method operation step order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    sortOrder: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateMethodOperationStepOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_updateMethodOperationStepOrder"),
  );

  server.registerTool(
    "production_updateJobOperationStatus",
    {
      description: "update job operation status",
      inputSchema: z.object({
      id: z.string(),
      status: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateJobOperationStatus(ctx.client, params.id, params.status, ctx.userId);
      return toMcpResult(result);
    }, "Failed: production_updateJobOperationStatus"),
  );

  server.registerTool(
    "production_updateJobOperationDueDate",
    {
      description: "update job operation due date",
      inputSchema: z.object({
      id: z.string(),
      dueDate: z.string().nullable(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateJobOperationDueDate(ctx.client, params.id, params.dueDate, ctx.userId);
      return toMcpResult(result);
    }, "Failed: production_updateJobOperationDueDate"),
  );

  server.registerTool(
    "production_updateProcedureStepOrder",
    {
      description: "update procedure step order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    sortOrder: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateProcedureStepOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_updateProcedureStepOrder"),
  );

  server.registerTool(
    "production_upsertProductionEvent",
    {
      description: "upsert production event",
      inputSchema: z.object({
      productionEvent: productionEventValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertProductionEvent(ctx.client, { ...params.productionEvent, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertProductionEvent"),
  );

  server.registerTool(
    "production_updateProductionQuantity",
    {
      description: "update production quantity",
      inputSchema: z.object({
      productionQuantity: productionQuantityValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateProductionQuantity(ctx.client, { ...params.productionQuantity, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_updateProductionQuantity"),
  );

  server.registerTool(
    "production_upsertProductionQuantity",
    {
      description: "upsert production quantity",
      inputSchema: z.object({
      productionQuantity: productionQuantityValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertProductionQuantity(ctx.client, { ...params.productionQuantity, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertProductionQuantity"),
  );

  server.registerTool(
    "production_upsertJob",
    {
      description: "upsert job",
      inputSchema: z.object({
      job: jobValidator,
      status: z.any().optional(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertJob(ctx.client, { ...params.job, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId }, params.status);
      return toMcpResult(result);
    }, "Failed: production_upsertJob"),
  );

  server.registerTool(
    "production_upsertJobMaterial",
    {
      description: "upsert job material",
      inputSchema: z.object({
      jobMaterial: jobMaterialValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertJobMaterial(ctx.client, { ...params.jobMaterial, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertJobMaterial"),
  );

  server.registerTool(
    "production_upsertJobOperation",
    {
      description: "upsert job operation",
      inputSchema: z.object({
      jobOperation: jobOperationValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertJobOperation(ctx.client, { ...params.jobOperation, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertJobOperation"),
  );

  server.registerTool(
    "production_upsertJobOperationStep",
    {
      description: "upsert job operation step",
      inputSchema: z.object({
      jobOperationStep: operationStepValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertJobOperationStep(ctx.client, { ...params.jobOperationStep, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertJobOperationStep"),
  );

  server.registerTool(
    "production_upsertJobOperationParameter",
    {
      description: "upsert job operation parameter",
      inputSchema: z.object({
      jobOperationParameter: operationParameterValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertJobOperationParameter(ctx.client, { ...params.jobOperationParameter, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertJobOperationParameter"),
  );

  server.registerTool(
    "production_upsertJobOperationTool",
    {
      description: "upsert job operation tool",
      inputSchema: z.object({
      jobOperationTool: operationToolValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertJobOperationTool(ctx.client, { ...params.jobOperationTool, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertJobOperationTool"),
  );

  server.registerTool(
    "production_upsertJobMethod",
    {
      description: "upsert job method",
      inputSchema: z.object({
      type: z.string(),
      jobMethod: z.object({
    sourceId: z.string(),
    targetId: z.string(),
    configuration: z.any().optional(),
    parts: z.any().optional(),
    billOfMaterial: z.boolean(),
    billOfProcess: z.boolean(),
    parameters: z.boolean(),
    tools: z.boolean(),
    steps: z.boolean(),
    workInstructions: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertJobMethod(ctx.client, params.type, { ...params.jobMethod, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertJobMethod"),
  );

  server.registerTool(
    "production_upsertJobMaterialMakeMethod",
    {
      description: "upsert job material make method",
      inputSchema: z.object({
      jobMaterial: z.object({
    sourceId: z.string(),
    targetId: z.string(),
    configuration: z.any().optional(),
    parts: z.any().optional(),
    billOfMaterial: z.boolean(),
    billOfProcess: z.boolean(),
    parameters: z.boolean(),
    tools: z.boolean(),
    steps: z.boolean(),
    workInstructions: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertJobMaterialMakeMethod(ctx.client, { ...params.jobMaterial, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertJobMaterialMakeMethod"),
  );

  server.registerTool(
    "production_upsertMakeMethodFromJob",
    {
      description: "upsert make method from job",
      inputSchema: z.object({
      jobMethod: z.object({
    sourceId: z.string(),
    targetId: z.string(),
    parts: z.any().optional(),
    billOfMaterial: z.boolean(),
    billOfProcess: z.boolean(),
    parameters: z.boolean(),
    tools: z.boolean(),
    steps: z.boolean(),
    workInstructions: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMakeMethodFromJob(ctx.client, { ...params.jobMethod, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertMakeMethodFromJob"),
  );

  server.registerTool(
    "production_upsertMakeMethodFromJobMethod",
    {
      description: "upsert make method from job method",
      inputSchema: z.object({
      jobMethod: z.object({
    sourceId: z.string(),
    targetId: z.string(),
    parts: z.any().optional(),
    billOfMaterial: z.boolean(),
    billOfProcess: z.boolean(),
    parameters: z.boolean(),
    tools: z.boolean(),
    steps: z.boolean(),
    workInstructions: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMakeMethodFromJobMethod(ctx.client, { ...params.jobMethod, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertMakeMethodFromJobMethod"),
  );

  server.registerTool(
    "production_upsertProcedure",
    {
      description: "upsert procedure",
      inputSchema: z.object({
      procedure: procedureValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertProcedure(ctx.client, { ...params.procedure, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertProcedure"),
  );

  server.registerTool(
    "production_upsertProcedureStep",
    {
      description: "upsert procedure step",
      inputSchema: z.object({
      procedureStep: procedureStepValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertProcedureStep(ctx.client, { ...params.procedureStep, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertProcedureStep"),
  );

  server.registerTool(
    "production_upsertProcedureParameter",
    {
      description: "upsert procedure parameter",
      inputSchema: z.object({
      procedureParameter: procedureParameterValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertProcedureParameter(ctx.client, { ...params.procedureParameter, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertProcedureParameter"),
  );

  server.registerTool(
    "production_upsertScrapReason",
    {
      description: "upsert scrap reason",
      inputSchema: z.object({
      scrapReason: scrapReasonValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertScrapReason(ctx.client, { ...params.scrapReason, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertScrapReason"),
  );

  server.registerTool(
    "production_upsertFailureMode",
    {
      description: "upsert failure mode",
      inputSchema: z.object({
      failureMode: failureModeValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertFailureMode(ctx.client, { ...params.failureMode, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertFailureMode"),
  );

  server.registerTool(
    "production_upsertMaintenanceDispatch",
    {
      description: "upsert maintenance dispatch",
      inputSchema: z.object({
      dispatch: maintenanceDispatchValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceDispatch(ctx.client, { ...params.dispatch, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertMaintenanceDispatch"),
  );

  server.registerTool(
    "production_upsertMaintenanceDispatchComment",
    {
      description: "upsert maintenance dispatch comment",
      inputSchema: z.object({
      comment: maintenanceDispatchCommentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceDispatchComment(ctx.client, { ...params.comment, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertMaintenanceDispatchComment"),
  );

  server.registerTool(
    "production_upsertMaintenanceDispatchEvent",
    {
      description: "upsert maintenance dispatch event",
      inputSchema: z.object({
      event: maintenanceDispatchEventValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceDispatchEvent(ctx.client, { ...params.event, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertMaintenanceDispatchEvent"),
  );

  server.registerTool(
    "production_upsertMaintenanceDispatchItem",
    {
      description: "upsert maintenance dispatch item",
      inputSchema: z.object({
      item: maintenanceDispatchItemValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceDispatchItem(ctx.client, { ...params.item, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertMaintenanceDispatchItem"),
  );

  server.registerTool(
    "production_upsertMaintenanceDispatchWorkCenter",
    {
      description: "upsert maintenance dispatch work center",
      inputSchema: z.object({
      workCenter: maintenanceDispatchWorkCenterValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceDispatchWorkCenter(ctx.client, { ...params.workCenter, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertMaintenanceDispatchWorkCenter"),
  );

  server.registerTool(
    "production_upsertMaintenanceSchedule",
    {
      description: "upsert maintenance schedule",
      inputSchema: z.object({
      schedule: maintenanceScheduleValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceSchedule(ctx.client, { ...params.schedule, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertMaintenanceSchedule"),
  );

  server.registerTool(
    "production_upsertMaintenanceScheduleItem",
    {
      description: "upsert maintenance schedule item",
      inputSchema: z.object({
      item: maintenanceScheduleItemValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMaintenanceScheduleItem(ctx.client, { ...params.item, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertMaintenanceScheduleItem"),
  );

  server.registerTool(
    "production_upsertDemandForecasts",
    {
      description: "upsert demand forecasts",
      inputSchema: z.object({
      forecasts: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertDemandForecasts(ctx.client, { ...params.forecasts, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertDemandForecasts"),
  );

  server.registerTool(
    "production_upsertDemandProjections",
    {
      description: "upsert demand projections",
      inputSchema: z.object({
      forecasts: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertDemandProjections(ctx.client, { ...params.forecasts, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: production_upsertDemandProjections"),
  );

  server.registerTool(
    "production_triggerJobSchedule",
    {
      description: "trigger job schedule",
      inputSchema: z.object({
      jobId: z.string(),
      mode: z.string().optional(),
      direction: z.string().optional(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await triggerJobSchedule(ctx.client, params.jobId, ctx.companyId, ctx.userId, params.mode, params.direction);
      return toMcpResult(result);
    }, "Failed: production_triggerJobSchedule"),
  );
};
