// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  closePurchaseOrder,
  convertSupplierQuoteToOrder,
  deletePurchaseOrder,
  deletePurchaseOrderLine,
  deleteSupplier,
  deleteSupplierContact,
  deleteSupplierLocation,
  deleteSupplierProcess,
  deleteSupplierQuote,
  deleteSupplierQuoteLine,
  deleteSupplierType,
  getPurchaseOrder,
  finalizeSupplierQuote,
  getPurchaseOrders,
  getPurchaseOrderDelivery,
  getPurchaseOrderLocations,
  getPurchaseOrderPayment,
  getPurchaseOrderLines,
  getPurchaseOrderLine,
  getPurchaseOrderSuppliers,
  getPurchasingDocumentsAssignedToMe,
  getPurchasingPlanning,
  getPurchasingTerms,
  getSupplier,
  getSupplierApprovalContext,
  getSupplierContact,
  getSupplierContacts,
  getSupplierInteraction,
  getSupplierInteractionDocuments,
  getSupplierInteractionLineDocuments,
  getSupplierLocations,
  getSupplierLocation,
  getSupplierPayment,
  getSupplierProcessById,
  getSupplierProcessesByProcess,
  getSupplierProcessesBySupplier,
  getSupplierQuote,
  getSupplierQuoteByInteractionId,
  getSupplierQuoteByExternalLinkId,
  getSupplierQuotes,
  getSupplierQuoteLine,
  getSupplierQuoteLines,
  getSupplierQuoteLinePrices,
  getSupplierQuoteLinePricesByQuoteId,
  getSupplierQuotesList,
  getSupplierShipping,
  getSuppliers,
  getSuppliersList,
  getSupplierType,
  getSupplierTypes,
  getSupplierTypesList,
  insertSupplier,
  insertSupplierContact,
  insertSupplierInteraction,
  insertSupplierLocation,
  finalizePurchaseOrder,
  sendSupplierQuote,
  updatePurchaseOrder,
  updatePurchaseOrderExchangeRate,
  updatePurchaseOrderFavorite,
  updatePurchaseOrderStatus,
  updateSupplierAccounting,
  updateSupplierContact,
  updateSupplierLocation,
  updateSupplierPayment,
  updateSupplierQuoteExchangeRate,
  updateSupplierQuoteFavorite,
  updateSupplierQuoteStatus,
  updateSupplierShipping,
  getSupplierTax,
  updateSupplierTax,
  upsertPurchaseOrder,
  upsertPurchaseOrderDelivery,
  upsertPurchaseOrderLine,
  upsertPurchaseOrderPayment,
  upsertSupplier,
  upsertSupplierProcess,
  upsertSupplierQuote,
  upsertSupplierQuoteLine,
  upsertSupplierType,
  deletePurchasingRFQ,
  deletePurchasingRFQLine,
  getPurchasingRFQ,
  getPurchasingRFQs,
  getPurchasingRFQLine,
  getPurchasingRFQLines,
  getPurchasingRFQSuppliers,
  upsertPurchasingRFQ,
  upsertPurchasingRFQLine,
  upsertPurchasingRFQSuppliers,
  updatePurchasingRFQStatus,
  getLinkedSupplierQuotes,
  getLinkedPurchasingRfqs,
  getLinkedPurchasingRfqsForInteraction,
  getSiblingQuotesForQuote,
  getLinkedPurchasingRfqsForOrder,
  getSupplierQuotesForComparison,
  getPurchasingRFQSuppliersWithLinks,
} from "~/modules/purchasing/purchasing.service";
import {
  selectedLinesValidator,
  supplierValidator,
  supplierContactValidator,
  supplierAccountingValidator,
  supplierPaymentValidator,
  supplierShippingValidator,
  supplierTaxValidator,
  purchaseOrderValidator,
  purchaseOrderDeliveryValidator,
  purchaseOrderLineValidator,
  purchaseOrderPaymentValidator,
  supplierProcessValidator,
  supplierQuoteValidator,
  supplierQuoteLineValidator,
  supplierTypeValidator,
} from "~/modules/purchasing/purchasing.models";

export const registerPurchasingTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "purchasing_closePurchaseOrder",
    {
      description: "close purchase order",
      inputSchema: z.object({
      purchaseOrderId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await closePurchaseOrder(ctx.client, params.purchaseOrderId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: purchasing_closePurchaseOrder"),
  );

  server.registerTool(
    "purchasing_convertSupplierQuoteToOrder",
    {
      description: "convert supplier quote to order",
      inputSchema: z.object({
      payload: selectedLinesValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await convertSupplierQuoteToOrder(ctx.client, { ...params.payload, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_convertSupplierQuoteToOrder"),
  );

  server.registerTool(
    "purchasing_deletePurchaseOrder",
    {
      description: "delete purchase order",
      inputSchema: z.object({
      purchaseOrderId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePurchaseOrder(ctx.client, params.purchaseOrderId);
      return toMcpResult(result);
    }, "Failed: purchasing_deletePurchaseOrder"),
  );

  server.registerTool(
    "purchasing_deletePurchaseOrderLine",
    {
      description: "delete purchase order line",
      inputSchema: z.object({
      purchaseOrderLineId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePurchaseOrderLine(ctx.client, params.purchaseOrderLineId);
      return toMcpResult(result);
    }, "Failed: purchasing_deletePurchaseOrderLine"),
  );

  server.registerTool(
    "purchasing_deleteSupplier",
    {
      description: "delete supplier",
      inputSchema: z.object({
      supplierId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSupplier(ctx.client, params.supplierId);
      return toMcpResult(result);
    }, "Failed: purchasing_deleteSupplier"),
  );

  server.registerTool(
    "purchasing_deleteSupplierContact",
    {
      description: "delete supplier contact",
      inputSchema: z.object({
      supplierId: z.string(),
      supplierContactId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSupplierContact(ctx.client, params.supplierId, params.supplierContactId);
      return toMcpResult(result);
    }, "Failed: purchasing_deleteSupplierContact"),
  );

  server.registerTool(
    "purchasing_deleteSupplierLocation",
    {
      description: "delete supplier location",
      inputSchema: z.object({
      supplierId: z.string(),
      supplierLocationId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSupplierLocation(ctx.client, params.supplierId, params.supplierLocationId);
      return toMcpResult(result);
    }, "Failed: purchasing_deleteSupplierLocation"),
  );

  server.registerTool(
    "purchasing_deleteSupplierProcess",
    {
      description: "delete supplier process",
      inputSchema: z.object({
      supplierProcessId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSupplierProcess(ctx.client, params.supplierProcessId);
      return toMcpResult(result);
    }, "Failed: purchasing_deleteSupplierProcess"),
  );

  server.registerTool(
    "purchasing_deleteSupplierQuote",
    {
      description: "delete supplier quote",
      inputSchema: z.object({
      supplierQuoteId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSupplierQuote(ctx.client, params.supplierQuoteId);
      return toMcpResult(result);
    }, "Failed: purchasing_deleteSupplierQuote"),
  );

  server.registerTool(
    "purchasing_deleteSupplierQuoteLine",
    {
      description: "delete supplier quote line",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSupplierQuoteLine(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: purchasing_deleteSupplierQuoteLine"),
  );

  server.registerTool(
    "purchasing_deleteSupplierType",
    {
      description: "delete supplier type",
      inputSchema: z.object({
      supplierTypeId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSupplierType(ctx.client, params.supplierTypeId);
      return toMcpResult(result);
    }, "Failed: purchasing_deleteSupplierType"),
  );

  server.registerTool(
    "purchasing_getPurchaseOrder",
    {
      description: "get purchase order",
      inputSchema: z.object({
      purchaseOrderId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseOrder(ctx.client, params.purchaseOrderId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchaseOrder"),
  );

  server.registerTool(
    "purchasing_finalizeSupplierQuote",
    {
      description: "finalize supplier quote",
      inputSchema: z.object({
      supplierQuoteId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await finalizeSupplierQuote(ctx.client, params.supplierQuoteId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: purchasing_finalizeSupplierQuote"),
  );

  server.registerTool(
    "purchasing_getPurchaseOrders",
    {
      description: "get purchase orders",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    status: z.string().nullable(),
    supplierId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseOrders(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchaseOrders"),
  );

  server.registerTool(
    "purchasing_getPurchaseOrderDelivery",
    {
      description: "get purchase order delivery",
      inputSchema: z.object({
      purchaseOrderId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseOrderDelivery(ctx.client, params.purchaseOrderId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchaseOrderDelivery"),
  );

  server.registerTool(
    "purchasing_getPurchaseOrderLocations",
    {
      description: "get purchase order locations",
      inputSchema: z.object({
      purchaseOrderId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseOrderLocations(ctx.client, params.purchaseOrderId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchaseOrderLocations"),
  );

  server.registerTool(
    "purchasing_getPurchaseOrderPayment",
    {
      description: "get purchase order payment",
      inputSchema: z.object({
      purchaseOrderId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseOrderPayment(ctx.client, params.purchaseOrderId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchaseOrderPayment"),
  );

  server.registerTool(
    "purchasing_getPurchaseOrderLines",
    {
      description: "get purchase order lines",
      inputSchema: z.object({
      purchaseOrderId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseOrderLines(ctx.client, params.purchaseOrderId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchaseOrderLines"),
  );

  server.registerTool(
    "purchasing_getPurchaseOrderLine",
    {
      description: "get purchase order line",
      inputSchema: z.object({
      purchaseOrderLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseOrderLine(ctx.client, params.purchaseOrderLineId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchaseOrderLine"),
  );

  server.registerTool(
    "purchasing_getPurchaseOrderSuppliers",
    {
      description: "get purchase order suppliers",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchaseOrderSuppliers(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchaseOrderSuppliers"),
  );

  server.registerTool(
    "purchasing_getPurchasingDocumentsAssignedToMe",
    {
      description: "get purchasing documents assigned to me",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingDocumentsAssignedToMe(ctx.client, ctx.userId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchasingDocumentsAssignedToMe"),
  );

  server.registerTool(
    "purchasing_getPurchasingPlanning",
    {
      description: "get purchasing planning",
      inputSchema: z.object({
      locationId: z.string(),
      periods: z.array(z.string()),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingPlanning(ctx.client, params.locationId, ctx.companyId, params.periods, params.args);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchasingPlanning"),
  );

  server.registerTool(
    "purchasing_getPurchasingTerms",
    {
      description: "get purchasing terms",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingTerms(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchasingTerms"),
  );

  server.registerTool(
    "purchasing_getSupplier",
    {
      description: "get supplier",
      inputSchema: z.object({
      supplierId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplier(ctx.client, params.supplierId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplier"),
  );

  server.registerTool(
    "purchasing_getSupplierApprovalContext",
    {
      description: "get supplier approval context",
      inputSchema: z.object({
      supplierId: z.string(),
      status: z.string().nullable(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierApprovalContext(ctx.client, params.supplierId, params.status, ctx.companyId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierApprovalContext"),
  );

  server.registerTool(
    "purchasing_getSupplierContact",
    {
      description: "get supplier contact",
      inputSchema: z.object({
      supplierContactId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierContact(ctx.client, params.supplierContactId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierContact"),
  );

  server.registerTool(
    "purchasing_getSupplierContacts",
    {
      description: "get supplier contacts",
      inputSchema: z.object({
      supplierId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierContacts(ctx.client, params.supplierId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierContacts"),
  );

  server.registerTool(
    "purchasing_getSupplierInteraction",
    {
      description: "get supplier interaction",
      inputSchema: z.object({
      opportunityId: z.string().nullable(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierInteraction(ctx.client, params.opportunityId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierInteraction"),
  );

  server.registerTool(
    "purchasing_getSupplierInteractionDocuments",
    {
      description: "get supplier interaction documents",
      inputSchema: z.object({
      interactionId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierInteractionDocuments(ctx.client, ctx.companyId, params.interactionId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierInteractionDocuments"),
  );

  server.registerTool(
    "purchasing_getSupplierInteractionLineDocuments",
    {
      description: "get supplier interaction line documents",
      inputSchema: z.object({
      lineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierInteractionLineDocuments(ctx.client, ctx.companyId, params.lineId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierInteractionLineDocuments"),
  );

  server.registerTool(
    "purchasing_getSupplierLocations",
    {
      description: "get supplier locations",
      inputSchema: z.object({
      supplierId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierLocations(ctx.client, params.supplierId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierLocations"),
  );

  server.registerTool(
    "purchasing_getSupplierLocation",
    {
      description: "get supplier location",
      inputSchema: z.object({
      supplierContactId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierLocation(ctx.client, params.supplierContactId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierLocation"),
  );

  server.registerTool(
    "purchasing_getSupplierPayment",
    {
      description: "get supplier payment",
      inputSchema: z.object({
      supplierId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierPayment(ctx.client, params.supplierId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierPayment"),
  );

  server.registerTool(
    "purchasing_getSupplierProcessById",
    {
      description: "get supplier process by id",
      inputSchema: z.object({
      supplierProcessId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierProcessById(ctx.client, params.supplierProcessId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierProcessById"),
  );

  server.registerTool(
    "purchasing_getSupplierProcessesByProcess",
    {
      description: "get supplier processes by process",
      inputSchema: z.object({
      processId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierProcessesByProcess(ctx.client, params.processId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierProcessesByProcess"),
  );

  server.registerTool(
    "purchasing_getSupplierProcessesBySupplier",
    {
      description: "get supplier processes by supplier",
      inputSchema: z.object({
      supplierId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierProcessesBySupplier(ctx.client, params.supplierId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierProcessesBySupplier"),
  );

  server.registerTool(
    "purchasing_getSupplierQuote",
    {
      description: "get supplier quote",
      inputSchema: z.object({
      supplierQuoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierQuote(ctx.client, params.supplierQuoteId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierQuote"),
  );

  server.registerTool(
    "purchasing_getSupplierQuoteByInteractionId",
    {
      description: "get supplier quote by interaction id",
      inputSchema: z.object({
      interactionId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierQuoteByInteractionId(ctx.client, params.interactionId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierQuoteByInteractionId"),
  );

  server.registerTool(
    "purchasing_getSupplierQuoteByExternalLinkId",
    {
      description: "get supplier quote by external link id",
      inputSchema: z.object({
      externalLinkId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierQuoteByExternalLinkId(ctx.client, params.externalLinkId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierQuoteByExternalLinkId"),
  );

  server.registerTool(
    "purchasing_getSupplierQuotes",
    {
      description: "get supplier quotes",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierQuotes(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierQuotes"),
  );

  server.registerTool(
    "purchasing_getSupplierQuoteLine",
    {
      description: "get supplier quote line",
      inputSchema: z.object({
      supplierQuoteLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierQuoteLine(ctx.client, params.supplierQuoteLineId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierQuoteLine"),
  );

  server.registerTool(
    "purchasing_getSupplierQuoteLines",
    {
      description: "get supplier quote lines",
      inputSchema: z.object({
      supplierQuoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierQuoteLines(ctx.client, params.supplierQuoteId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierQuoteLines"),
  );

  server.registerTool(
    "purchasing_getSupplierQuoteLinePrices",
    {
      description: "get supplier quote line prices",
      inputSchema: z.object({
      supplierQuoteLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierQuoteLinePrices(ctx.client, params.supplierQuoteLineId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierQuoteLinePrices"),
  );

  server.registerTool(
    "purchasing_getSupplierQuoteLinePricesByQuoteId",
    {
      description: "get supplier quote line prices by quote id",
      inputSchema: z.object({
      supplierQuoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierQuoteLinePricesByQuoteId(ctx.client, params.supplierQuoteId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierQuoteLinePricesByQuoteId"),
  );

  server.registerTool(
    "purchasing_getSupplierQuotesList",
    {
      description: "get supplier quotes list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierQuotesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierQuotesList"),
  );

  server.registerTool(
    "purchasing_getSupplierShipping",
    {
      description: "get supplier shipping",
      inputSchema: z.object({
      supplierId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierShipping(ctx.client, params.supplierId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierShipping"),
  );

  server.registerTool(
    "purchasing_getSuppliers",
    {
      description: "get suppliers",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    type: z.string().nullable(),
    status: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSuppliers(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: purchasing_getSuppliers"),
  );

  server.registerTool(
    "purchasing_getSuppliersList",
    {
      description: "get suppliers list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSuppliersList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSuppliersList"),
  );

  server.registerTool(
    "purchasing_getSupplierType",
    {
      description: "get supplier type",
      inputSchema: z.object({
      supplierTypeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierType(ctx.client, params.supplierTypeId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierType"),
  );

  server.registerTool(
    "purchasing_getSupplierTypes",
    {
      description: "get supplier types",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierTypes(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierTypes"),
  );

  server.registerTool(
    "purchasing_getSupplierTypesList",
    {
      description: "get supplier types list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierTypesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierTypesList"),
  );

  server.registerTool(
    "purchasing_insertSupplier",
    {
      description: "insert supplier",
      inputSchema: z.object({
      supplier: supplierValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertSupplier(ctx.client, { ...params.supplier, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_insertSupplier"),
  );

  server.registerTool(
    "purchasing_insertSupplierContact",
    {
      description: "insert supplier contact",
      inputSchema: z.object({
      supplierContact: supplierContactValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertSupplierContact(ctx.client, { ...params.supplierContact, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: purchasing_insertSupplierContact"),
  );

  server.registerTool(
    "purchasing_insertSupplierInteraction",
    {
      description: "insert supplier interaction",
      inputSchema: z.object({
      supplierId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertSupplierInteraction(ctx.client, ctx.companyId, params.supplierId);
      return toMcpResult(result);
    }, "Failed: purchasing_insertSupplierInteraction"),
  );

  server.registerTool(
    "purchasing_insertSupplierLocation",
    {
      description: "insert supplier location",
      inputSchema: z.object({
      supplierLocation: z.object({
    supplierId: z.string(),
    name: z.string(),
    address: z.any(),
    addressLine1: z.string().optional(),
    addressLine2: z.string().optional(),
    city: z.string().optional(),
    stateProvince: z.string().optional(),
    postalCode: z.string().optional(),
    countryCode: z.string().optional(),
    customFields: z.any().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertSupplierLocation(ctx.client, { ...params.supplierLocation, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: purchasing_insertSupplierLocation"),
  );

  server.registerTool(
    "purchasing_finalizePurchaseOrder",
    {
      description: "finalize purchase order",
      inputSchema: z.object({
      purchaseOrderId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await finalizePurchaseOrder(ctx.client, params.purchaseOrderId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: purchasing_finalizePurchaseOrder"),
  );

  server.registerTool(
    "purchasing_sendSupplierQuote",
    {
      description: "send supplier quote",
      inputSchema: z.object({
      supplierQuoteId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await sendSupplierQuote(ctx.client, params.supplierQuoteId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: purchasing_sendSupplierQuote"),
  );

  server.registerTool(
    "purchasing_updatePurchaseOrder",
    {
      description: "update purchase order",
      inputSchema: z.object({
      purchaseOrder: z.object({
    id: z.string(),
    status: z.any()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePurchaseOrder(ctx.client, { ...params.purchaseOrder, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_updatePurchaseOrder"),
  );

  server.registerTool(
    "purchasing_updatePurchaseOrderExchangeRate",
    {
      description: "update purchase order exchange rate",
      inputSchema: z.object({
      data: z.object({
    id: z.string(),
    exchangeRate: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePurchaseOrderExchangeRate(ctx.client, params.data);
      return toMcpResult(result);
    }, "Failed: purchasing_updatePurchaseOrderExchangeRate"),
  );

  server.registerTool(
    "purchasing_updatePurchaseOrderFavorite",
    {
      description: "update purchase order favorite",
      inputSchema: z.object({
      args: z.object({
    id: z.string(),
    favorite: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePurchaseOrderFavorite(ctx.client, { ...params.args, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_updatePurchaseOrderFavorite"),
  );

  server.registerTool(
    "purchasing_updatePurchaseOrderStatus",
    {
      description: "update purchase order status",
      inputSchema: z.object({
      update: z.object({
    id: z.string(),
    status: z.any(),
    assignee: z.any()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePurchaseOrderStatus(ctx.client, { ...params.update, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_updatePurchaseOrderStatus"),
  );

  server.registerTool(
    "purchasing_updateSupplierAccounting",
    {
      description: "update supplier accounting",
      inputSchema: z.object({
      supplierAccounting: supplierAccountingValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSupplierAccounting(ctx.client, { ...params.supplierAccounting, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_updateSupplierAccounting"),
  );

  server.registerTool(
    "purchasing_updateSupplierContact",
    {
      description: "update supplier contact",
      inputSchema: z.object({
      supplierContact: supplierContactValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSupplierContact(ctx.client, params.supplierContact);
      return toMcpResult(result);
    }, "Failed: purchasing_updateSupplierContact"),
  );

  server.registerTool(
    "purchasing_updateSupplierLocation",
    {
      description: "update supplier location",
      inputSchema: z.object({
      supplierLocation: z.object({
    addressId: z.string(),
    name: z.string(),
    address: z.any(),
    addressLine1: z.string().optional(),
    addressLine2: z.string().optional(),
    city: z.string().optional(),
    stateProvince: z.string().optional(),
    countryCode: z.string().optional(),
    postalCode: z.string().optional(),
    customFields: z.any().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSupplierLocation(ctx.client, params.supplierLocation);
      return toMcpResult(result);
    }, "Failed: purchasing_updateSupplierLocation"),
  );

  server.registerTool(
    "purchasing_updateSupplierPayment",
    {
      description: "update supplier payment",
      inputSchema: z.object({
      supplierPayment: supplierPaymentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSupplierPayment(ctx.client, { ...params.supplierPayment, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_updateSupplierPayment"),
  );

  server.registerTool(
    "purchasing_updateSupplierQuoteExchangeRate",
    {
      description: "update supplier quote exchange rate",
      inputSchema: z.object({
      data: z.object({
    id: z.string(),
    exchangeRate: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSupplierQuoteExchangeRate(ctx.client, params.data);
      return toMcpResult(result);
    }, "Failed: purchasing_updateSupplierQuoteExchangeRate"),
  );

  server.registerTool(
    "purchasing_updateSupplierQuoteFavorite",
    {
      description: "update supplier quote favorite",
      inputSchema: z.object({
      args: z.object({
    id: z.string(),
    favorite: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSupplierQuoteFavorite(ctx.client, { ...params.args, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_updateSupplierQuoteFavorite"),
  );

  server.registerTool(
    "purchasing_updateSupplierQuoteStatus",
    {
      description: "update supplier quote status",
      inputSchema: z.object({
      update: z.object({
    id: z.string(),
    status: z.any(),
    assignee: z.any()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSupplierQuoteStatus(ctx.client, { ...params.update, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_updateSupplierQuoteStatus"),
  );

  server.registerTool(
    "purchasing_updateSupplierShipping",
    {
      description: "update supplier shipping",
      inputSchema: z.object({
      supplierShipping: supplierShippingValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSupplierShipping(ctx.client, { ...params.supplierShipping, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_updateSupplierShipping"),
  );

  server.registerTool(
    "purchasing_getSupplierTax",
    {
      description: "get supplier tax",
      inputSchema: {
      supplierId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierTax(ctx.client, params.supplierId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierTax"),
  );

  server.registerTool(
    "purchasing_updateSupplierTax",
    {
      description: "update supplier tax",
      inputSchema: {
      supplierTax: supplierTaxValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSupplierTax(ctx.client, { ...params.supplierTax, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_updateSupplierTax"),
  );

  server.registerTool(
    "purchasing_upsertPurchaseOrder",
    {
      description: "upsert purchase order",
      inputSchema: z.object({
      purchaseOrder: purchaseOrderValidator,
      receiptRequestedDate: z.string().optional(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPurchaseOrder(ctx.client, { ...params.purchaseOrder, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId }, params.receiptRequestedDate);
      return toMcpResult(result);
    }, "Failed: purchasing_upsertPurchaseOrder"),
  );

  server.registerTool(
    "purchasing_upsertPurchaseOrderDelivery",
    {
      description: "upsert purchase order delivery",
      inputSchema: z.object({
      purchaseOrderDelivery: purchaseOrderDeliveryValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPurchaseOrderDelivery(ctx.client, { ...params.purchaseOrderDelivery, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_upsertPurchaseOrderDelivery"),
  );

  server.registerTool(
    "purchasing_upsertPurchaseOrderLine",
    {
      description: "upsert purchase order line",
      inputSchema: z.object({
      purchaseOrderLine: purchaseOrderLineValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPurchaseOrderLine(ctx.client, { ...params.purchaseOrderLine, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_upsertPurchaseOrderLine"),
  );

  server.registerTool(
    "purchasing_upsertPurchaseOrderPayment",
    {
      description: "upsert purchase order payment",
      inputSchema: z.object({
      purchaseOrderPayment: purchaseOrderPaymentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPurchaseOrderPayment(ctx.client, { ...params.purchaseOrderPayment, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_upsertPurchaseOrderPayment"),
  );

  server.registerTool(
    "purchasing_upsertSupplier",
    {
      description: "upsert supplier",
      inputSchema: z.object({
      supplier: supplierValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSupplier(ctx.client, { ...params.supplier, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_upsertSupplier"),
  );

  server.registerTool(
    "purchasing_upsertSupplierProcess",
    {
      description: "upsert supplier process",
      inputSchema: z.object({
      supplierProcess: supplierProcessValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSupplierProcess(ctx.client, { ...params.supplierProcess, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_upsertSupplierProcess"),
  );

  server.registerTool(
    "purchasing_upsertSupplierQuote",
    {
      description: "upsert supplier quote",
      inputSchema: z.object({
      supplierQuote: supplierQuoteValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSupplierQuote(ctx.client, { ...params.supplierQuote, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_upsertSupplierQuote"),
  );

  server.registerTool(
    "purchasing_upsertSupplierQuoteLine",
    {
      description: "upsert supplier quote line",
      inputSchema: z.object({
      supplierQuoteLine: supplierQuoteLineValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSupplierQuoteLine(ctx.client, { ...params.supplierQuoteLine, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_upsertSupplierQuoteLine"),
  );

  server.registerTool(
    "purchasing_upsertSupplierType",
    {
      description: "upsert supplier type",
      inputSchema: z.object({
      supplierType: supplierTypeValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSupplierType(ctx.client, { ...params.supplierType, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_upsertSupplierType"),
  );

  server.registerTool(
    "purchasing_deletePurchasingRFQ",
    {
      description: "delete purchasing r f q",
      inputSchema: z.object({
      purchasingRfqId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePurchasingRFQ(ctx.client, params.purchasingRfqId);
      return toMcpResult(result);
    }, "Failed: purchasing_deletePurchasingRFQ"),
  );

  server.registerTool(
    "purchasing_deletePurchasingRFQLine",
    {
      description: "delete purchasing r f q line",
      inputSchema: z.object({
      purchasingRfqLineId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePurchasingRFQLine(ctx.client, params.purchasingRfqLineId);
      return toMcpResult(result);
    }, "Failed: purchasing_deletePurchasingRFQLine"),
  );

  server.registerTool(
    "purchasing_getPurchasingRFQ",
    {
      description: "get purchasing r f q",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingRFQ(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchasingRFQ"),
  );

  server.registerTool(
    "purchasing_getPurchasingRFQs",
    {
      description: "get purchasing r f qs",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingRFQs(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchasingRFQs"),
  );

  server.registerTool(
    "purchasing_getPurchasingRFQLine",
    {
      description: "get purchasing r f q line",
      inputSchema: z.object({
      lineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingRFQLine(ctx.client, params.lineId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchasingRFQLine"),
  );

  server.registerTool(
    "purchasing_getPurchasingRFQLines",
    {
      description: "get purchasing r f q lines",
      inputSchema: z.object({
      purchasingRfqId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingRFQLines(ctx.client, params.purchasingRfqId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchasingRFQLines"),
  );

  server.registerTool(
    "purchasing_getPurchasingRFQSuppliers",
    {
      description: "get purchasing r f q suppliers",
      inputSchema: z.object({
      purchasingRfqId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingRFQSuppliers(ctx.client, params.purchasingRfqId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchasingRFQSuppliers"),
  );

  server.registerTool(
    "purchasing_upsertPurchasingRFQ",
    {
      description: "upsert purchasing r f q",
      inputSchema: z.object({
      purchasingRfq: z.object({
    id: z.string().optional(),
    rfqId: z.string(),
    rfqDate: z.string(),
    expirationDate: z.string().optional(),
    locationId: z.string().optional(),
    employeeId: z.string().optional(),
    status: z.any().optional(),
    customFields: z.any().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPurchasingRFQ(ctx.client, { ...params.purchasingRfq, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_upsertPurchasingRFQ"),
  );

  server.registerTool(
    "purchasing_upsertPurchasingRFQLine",
    {
      description: "upsert purchasing r f q line",
      inputSchema: z.object({
      purchasingRfqLine: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPurchasingRFQLine(ctx.client, { ...params.purchasingRfqLine, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_upsertPurchasingRFQLine"),
  );

  server.registerTool(
    "purchasing_upsertPurchasingRFQSuppliers",
    {
      description: "upsert purchasing r f q suppliers",
      inputSchema: z.object({
      purchasingRfqId: z.string(),
      supplierIds: z.array(z.string()),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPurchasingRFQSuppliers(ctx.client, params.purchasingRfqId, params.supplierIds, ctx.companyId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: purchasing_upsertPurchasingRFQSuppliers"),
  );

  server.registerTool(
    "purchasing_updatePurchasingRFQStatus",
    {
      description: "update purchasing r f q status",
      inputSchema: z.object({
      args: z.object({
    id: z.string(),
    status: z.any(),
    assignee: z.string().nullable().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePurchasingRFQStatus(ctx.client, { ...params.args, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: purchasing_updatePurchasingRFQStatus"),
  );

  server.registerTool(
    "purchasing_getLinkedSupplierQuotes",
    {
      description: "get linked supplier quotes",
      inputSchema: z.object({
      purchasingRfqId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getLinkedSupplierQuotes(ctx.client, params.purchasingRfqId);
      return toMcpResult(result);
    }, "Failed: purchasing_getLinkedSupplierQuotes"),
  );

  server.registerTool(
    "purchasing_getLinkedPurchasingRfqs",
    {
      description: "get linked purchasing rfqs",
      inputSchema: z.object({
      supplierQuoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getLinkedPurchasingRfqs(ctx.client, params.supplierQuoteId);
      return toMcpResult(result);
    }, "Failed: purchasing_getLinkedPurchasingRfqs"),
  );

  server.registerTool(
    "purchasing_getLinkedPurchasingRfqsForInteraction",
    {
      description: "get linked purchasing rfqs for interaction",
      inputSchema: z.object({
      supplierInteractionId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getLinkedPurchasingRfqsForInteraction(ctx.client, params.supplierInteractionId);
      return toMcpResult(result);
    }, "Failed: purchasing_getLinkedPurchasingRfqsForInteraction"),
  );

  server.registerTool(
    "purchasing_getSiblingQuotesForQuote",
    {
      description: "get sibling quotes for quote",
      inputSchema: z.object({
      supplierQuoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSiblingQuotesForQuote(ctx.client, params.supplierQuoteId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSiblingQuotesForQuote"),
  );

  server.registerTool(
    "purchasing_getLinkedPurchasingRfqsForOrder",
    {
      description: "get linked purchasing rfqs for order",
      inputSchema: z.object({
      purchaseOrderId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getLinkedPurchasingRfqsForOrder(ctx.client, params.purchaseOrderId);
      return toMcpResult(result);
    }, "Failed: purchasing_getLinkedPurchasingRfqsForOrder"),
  );

  server.registerTool(
    "purchasing_getSupplierQuotesForComparison",
    {
      description: "get supplier quotes for comparison",
      inputSchema: z.object({
      purchasingRfqId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSupplierQuotesForComparison(ctx.client, params.purchasingRfqId);
      return toMcpResult(result);
    }, "Failed: purchasing_getSupplierQuotesForComparison"),
  );

  server.registerTool(
    "purchasing_getPurchasingRFQSuppliersWithLinks",
    {
      description: "get purchasing r f q suppliers with links",
      inputSchema: z.object({
      purchasingRfqId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingRFQSuppliersWithLinks(ctx.client, params.purchasingRfqId);
      return toMcpResult(result);
    }, "Failed: purchasing_getPurchasingRFQSuppliersWithLinks"),
  );
};
