// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  closeSalesOrder,
  convertSalesRfqToQuote,
  convertQuoteToOrder,
  copyQuoteLine,
  copyQuote,
  deleteCustomer,
  deleteCustomerContact,
  deleteCustomerLocation,
  deleteCustomerStatus,
  deleteCustomerType,
  deleteNoQuoteReason,
  deleteQuote,
  deleteQuoteMakeMethod,
  deleteQuoteLine,
  deleteQuoteMaterial,
  deleteQuoteOperation,
  deleteQuoteOperationStep,
  deleteQuoteOperationParameter,
  deleteQuoteOperationTool,
  deleteSalesOrder,
  deleteSalesOrderLine,
  deleteSalesRFQ,
  deleteSalesRFQLine,
  getConfigurationParametersByQuoteLineId,
  getCustomer,
  getCustomerContact,
  getCustomerContacts,
  getCustomerLocation,
  getCustomerLocations,
  getCustomerPayment,
  getCustomerShipping,
  getCustomers,
  getCustomersList,
  getCustomerStatus,
  getCustomerStatuses,
  getCustomerStatusesList,
  getCustomerType,
  getCustomerTypes,
  getCustomerTypesList,
  getExternalSalesOrderLines,
  getModelByQuoteLineId,
  getNoQuoteReasonsList,
  getNoQuoteReason,
  getNoQuoteReasons,
  getOpportunity,
  getOpportunityDocuments,
  getOpportunityLineDocuments,
  getQuote,
  getQuoteFavorites,
  getQuotes,
  getQuotesList,
  getQuoteAssembliesByLine,
  getQuoteAssemblies,
  getQuoteCustomerDetails,
  getQuoteLine,
  getQuoteLinesList,
  getQuoteMakeMethod,
  getRootQuoteMakeMethod,
  getQuoteMethodTrees,
  getQuoteMethodTreeArray,
  getQuoteLines,
  getQuoteByExternalId,
  getQuoteLinePrices,
  getQuoteLinePricesByQuoteId,
  getQuoteLinePricesByItemId,
  getQuoteLinePricesByItemIds,
  getQuoteMaterials,
  getQuoteMaterial,
  getQuoteMaterialsByLine,
  getQuoteMaterialsByMethodId,
  getQuoteMaterialsByOperation,
  getQuoteOperation,
  getQuoteOperationsByLine,
  getQuoteOperationsByMethodId,
  getQuoteOperations,
  getQuotePayment,
  getQuoteShipment,
  getRelatedPricesForQuoteLine,
  getSalesDocumentsAssignedToMe,
  getSalesOrder,
  getSalesOrderCustomerDetails,
  getSalesOrderFavorites,
  getSalesOrderRelatedItems,
  getSalesOrders,
  getSalesOrdersList,
  getSalesOrderPayment,
  getSalesTerms,
  getSalesOrderShipment,
  getSalesOrderCustomers,
  getSalesOrderLines,
  getSalesOrderInvoiceLines,
  getSalesOrderInvoicesByIds,
  getSalesOrderLinesByItemId,
  getSalesOrderLinesByItemIds,
  getSalesOrderLine,
  getSalesOrderLineShipments,
  getSalesRFQ,
  getSalesRFQFavorites,
  getSalesRFQs,
  getSalesRFQLine,
  getSalesRFQLines,
  insertCustomerContact,
  insertCustomerLocation,
  insertSalesOrderLines,
  finalizeQuote,
  releaseSalesOrder,
  upsertCustomer,
  updateCustomerAccounting,
  updateCustomerContact,
  updateCustomerLocation,
  updateCustomerPayment,
  updateCustomerShipping,
  getCustomerTax,
  updateCustomerTax,
  upsertCustomerStatus,
  upsertCustomerType,
  upsertNoQuoteReason,
  updateSalesRFQFavorite,
  updateSalesRFQLineOrder,
  updateQuoteExchangeRate,
  updateQuoteLinePrecision,
  updateSalesOrderExchangeRate,
  updateQuoteFavorite,
  updateSalesRFQStatus,
  updateQuoteMaterialOrder,
  updateQuoteOperationOrder,
  updateQuoteStatus,
  upsertMakeMethodFromQuoteLine,
  upsertMakeMethodFromQuoteMethod,
  upsertQuote,
  upsertQuoteLine,
  upsertQuoteLineAdditionalCharges,
  upsertQuoteLinePrices,
  calculatePricesForQuantities,
  recalculateQuoteLinePrices,
  upsertQuoteLineMethod,
  upsertQuoteMaterial,
  upsertQuoteMaterialMakeMethod,
  upsertQuoteOperation,
  upsertQuoteOperationStep,
  upsertQuoteOperationParameter,
  upsertQuoteOperationTool,
  upsertQuotePayment,
  upsertQuoteShipment,
  updateSalesOrderFavorite,
  updateSalesOrderStatus,
  upsertSalesOrder,
  upsertSalesOrderShipment,
  upsertSalesOrderLine,
  upsertSalesOrderPayment,
  upsertSalesRFQ,
  upsertSalesRFQLine,
} from "~/modules/sales/sales.service";
import {
  selectedLinesValidator,
  getMethodValidator,
  customerContactValidator,
  salesOrderLineValidator,
  customerValidator,
  customerAccountingValidator,
  customerPaymentValidator,
  customerShippingValidator,
  customerTaxValidator,
  customerStatusValidator,
  customerTypeValidator,
  noQuoteReasonValidator,
  quoteValidator,
  quoteLineValidator,
  quoteLineAdditionalChargesValidator,
  quoteMaterialValidator,
  quoteOperationValidator,
  quotePaymentValidator,
  quoteShipmentValidator,
  salesOrderValidator,
  salesOrderShipmentValidator,
  salesOrderPaymentValidator,
  salesRfqValidator,
  salesRfqLineValidator,
} from "~/modules/sales/sales.models";
import {
  operationStepValidator,
  operationParameterValidator,
  operationToolValidator,
} from "~/modules/shared";

export const registerSalesTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "sales_closeSalesOrder",
    {
      description: "close sales order",
      inputSchema: z.object({
      salesOrderId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await closeSalesOrder(ctx.client, params.salesOrderId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: sales_closeSalesOrder"),
  );

  server.registerTool(
    "sales_convertSalesRfqToQuote",
    {
      description: "convert sales rfq to quote",
      inputSchema: z.object({
      payload: z.object({
    id: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await convertSalesRfqToQuote(ctx.client, { ...params.payload, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_convertSalesRfqToQuote"),
  );

  server.registerTool(
    "sales_convertQuoteToOrder",
    {
      description: "convert quote to order",
      inputSchema: z.object({
      payload: selectedLinesValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await convertQuoteToOrder(ctx.client, { ...params.payload, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_convertQuoteToOrder"),
  );

  server.registerTool(
    "sales_copyQuoteLine",
    {
      description: "copy quote line",
      inputSchema: z.object({
      payload: getMethodValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await copyQuoteLine(ctx.client, { ...params.payload, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_copyQuoteLine"),
  );

  server.registerTool(
    "sales_copyQuote",
    {
      description: "copy quote",
      inputSchema: z.object({
      payload: getMethodValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await copyQuote(ctx.client, { ...params.payload, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_copyQuote"),
  );

  server.registerTool(
    "sales_deleteCustomer",
    {
      description: "delete customer",
      inputSchema: z.object({
      customerId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteCustomer(ctx.client, params.customerId);
      return toMcpResult(result);
    }, "Failed: sales_deleteCustomer"),
  );

  server.registerTool(
    "sales_deleteCustomerContact",
    {
      description: "delete customer contact",
      inputSchema: z.object({
      customerId: z.string(),
      customerContactId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteCustomerContact(ctx.client, params.customerId, params.customerContactId);
      return toMcpResult(result);
    }, "Failed: sales_deleteCustomerContact"),
  );

  server.registerTool(
    "sales_deleteCustomerLocation",
    {
      description: "delete customer location",
      inputSchema: z.object({
      customerId: z.string(),
      customerLocationId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteCustomerLocation(ctx.client, params.customerId, params.customerLocationId);
      return toMcpResult(result);
    }, "Failed: sales_deleteCustomerLocation"),
  );

  server.registerTool(
    "sales_deleteCustomerStatus",
    {
      description: "delete customer status",
      inputSchema: z.object({
      customerStatusId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteCustomerStatus(ctx.client, params.customerStatusId);
      return toMcpResult(result);
    }, "Failed: sales_deleteCustomerStatus"),
  );

  server.registerTool(
    "sales_deleteCustomerType",
    {
      description: "delete customer type",
      inputSchema: z.object({
      customerTypeId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteCustomerType(ctx.client, params.customerTypeId);
      return toMcpResult(result);
    }, "Failed: sales_deleteCustomerType"),
  );

  server.registerTool(
    "sales_deleteNoQuoteReason",
    {
      description: "delete no quote reason",
      inputSchema: z.object({
      noQuoteReasonId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteNoQuoteReason(ctx.client, params.noQuoteReasonId);
      return toMcpResult(result);
    }, "Failed: sales_deleteNoQuoteReason"),
  );

  server.registerTool(
    "sales_deleteQuote",
    {
      description: "delete quote",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteQuote(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_deleteQuote"),
  );

  server.registerTool(
    "sales_deleteQuoteMakeMethod",
    {
      description: "delete quote make method",
      inputSchema: z.object({
      quoteMakeMethodId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteQuoteMakeMethod(ctx.client, params.quoteMakeMethodId);
      return toMcpResult(result);
    }, "Failed: sales_deleteQuoteMakeMethod"),
  );

  server.registerTool(
    "sales_deleteQuoteLine",
    {
      description: "delete quote line",
      inputSchema: z.object({
      quoteLineId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteQuoteLine(ctx.client, params.quoteLineId);
      return toMcpResult(result);
    }, "Failed: sales_deleteQuoteLine"),
  );

  server.registerTool(
    "sales_deleteQuoteMaterial",
    {
      description: "delete quote material",
      inputSchema: z.object({
      quoteMaterialId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteQuoteMaterial(ctx.client, params.quoteMaterialId);
      return toMcpResult(result);
    }, "Failed: sales_deleteQuoteMaterial"),
  );

  server.registerTool(
    "sales_deleteQuoteOperation",
    {
      description: "delete quote operation",
      inputSchema: z.object({
      quoteOperationId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteQuoteOperation(ctx.client, params.quoteOperationId);
      return toMcpResult(result);
    }, "Failed: sales_deleteQuoteOperation"),
  );

  server.registerTool(
    "sales_deleteQuoteOperationStep",
    {
      description: "delete quote operation step",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteQuoteOperationStep(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: sales_deleteQuoteOperationStep"),
  );

  server.registerTool(
    "sales_deleteQuoteOperationParameter",
    {
      description: "delete quote operation parameter",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteQuoteOperationParameter(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: sales_deleteQuoteOperationParameter"),
  );

  server.registerTool(
    "sales_deleteQuoteOperationTool",
    {
      description: "delete quote operation tool",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteQuoteOperationTool(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: sales_deleteQuoteOperationTool"),
  );

  server.registerTool(
    "sales_deleteSalesOrder",
    {
      description: "delete sales order",
      inputSchema: z.object({
      salesOrderId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSalesOrder(ctx.client, params.salesOrderId);
      return toMcpResult(result);
    }, "Failed: sales_deleteSalesOrder"),
  );

  server.registerTool(
    "sales_deleteSalesOrderLine",
    {
      description: "delete sales order line",
      inputSchema: z.object({
      salesOrderLineId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSalesOrderLine(ctx.client, params.salesOrderLineId);
      return toMcpResult(result);
    }, "Failed: sales_deleteSalesOrderLine"),
  );

  server.registerTool(
    "sales_deleteSalesRFQ",
    {
      description: "delete sales r f q",
      inputSchema: z.object({
      salesRfqId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSalesRFQ(ctx.client, params.salesRfqId);
      return toMcpResult(result);
    }, "Failed: sales_deleteSalesRFQ"),
  );

  server.registerTool(
    "sales_deleteSalesRFQLine",
    {
      description: "delete sales r f q line",
      inputSchema: z.object({
      salesRFQLineId: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteSalesRFQLine(ctx.client, params.salesRFQLineId);
      return toMcpResult(result);
    }, "Failed: sales_deleteSalesRFQLine"),
  );

  server.registerTool(
    "sales_getConfigurationParametersByQuoteLineId",
    {
      description: "get configuration parameters by quote line id",
      inputSchema: z.object({
      quoteLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getConfigurationParametersByQuoteLineId(ctx.client, params.quoteLineId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: sales_getConfigurationParametersByQuoteLineId"),
  );

  server.registerTool(
    "sales_getCustomer",
    {
      description: "get customer",
      inputSchema: z.object({
      customerId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomer(ctx.client, params.customerId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomer"),
  );

  server.registerTool(
    "sales_getCustomerContact",
    {
      description: "get customer contact",
      inputSchema: z.object({
      customerContactId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerContact(ctx.client, params.customerContactId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerContact"),
  );

  server.registerTool(
    "sales_getCustomerContacts",
    {
      description: "get customer contacts",
      inputSchema: z.object({
      customerId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerContacts(ctx.client, params.customerId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerContacts"),
  );

  server.registerTool(
    "sales_getCustomerLocation",
    {
      description: "get customer location",
      inputSchema: z.object({
      customerLocationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerLocation(ctx.client, params.customerLocationId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerLocation"),
  );

  server.registerTool(
    "sales_getCustomerLocations",
    {
      description: "get customer locations",
      inputSchema: z.object({
      customerId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerLocations(ctx.client, params.customerId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerLocations"),
  );

  server.registerTool(
    "sales_getCustomerPayment",
    {
      description: "get customer payment",
      inputSchema: z.object({
      customerId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerPayment(ctx.client, params.customerId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerPayment"),
  );

  server.registerTool(
    "sales_getCustomerShipping",
    {
      description: "get customer shipping",
      inputSchema: z.object({
      customerId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerShipping(ctx.client, params.customerId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerShipping"),
  );

  server.registerTool(
    "sales_getCustomers",
    {
      description: "get customers",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomers(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: sales_getCustomers"),
  );

  server.registerTool(
    "sales_getCustomersList",
    {
      description: "get customers list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomersList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomersList"),
  );

  server.registerTool(
    "sales_getCustomerStatus",
    {
      description: "get customer status",
      inputSchema: z.object({
      customerStatusId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerStatus(ctx.client, params.customerStatusId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerStatus"),
  );

  server.registerTool(
    "sales_getCustomerStatuses",
    {
      description: "get customer statuses",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerStatuses(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerStatuses"),
  );

  server.registerTool(
    "sales_getCustomerStatusesList",
    {
      description: "get customer statuses list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerStatusesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerStatusesList"),
  );

  server.registerTool(
    "sales_getCustomerType",
    {
      description: "get customer type",
      inputSchema: z.object({
      customerTypeId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerType(ctx.client, params.customerTypeId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerType"),
  );

  server.registerTool(
    "sales_getCustomerTypes",
    {
      description: "get customer types",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerTypes(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerTypes"),
  );

  server.registerTool(
    "sales_getCustomerTypesList",
    {
      description: "get customer types list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerTypesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerTypesList"),
  );

  server.registerTool(
    "sales_getExternalSalesOrderLines",
    {
      description: "get external sales order lines",
      inputSchema: z.object({
      customerId: z.string(),
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getExternalSalesOrderLines(ctx.client, params.customerId, params.args);
      return toMcpResult(result);
    }, "Failed: sales_getExternalSalesOrderLines"),
  );

  server.registerTool(
    "sales_getModelByQuoteLineId",
    {
      description: "get model by quote line id",
      inputSchema: z.object({
      quoteLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getModelByQuoteLineId(ctx.client, params.quoteLineId);
      return toMcpResult(result);
    }, "Failed: sales_getModelByQuoteLineId"),
  );

  server.registerTool(
    "sales_getNoQuoteReasonsList",
    {
      description: "get no quote reasons list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getNoQuoteReasonsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: sales_getNoQuoteReasonsList"),
  );

  server.registerTool(
    "sales_getNoQuoteReason",
    {
      description: "get no quote reason",
      inputSchema: z.object({
      noQuoteReasonId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getNoQuoteReason(ctx.client, params.noQuoteReasonId);
      return toMcpResult(result);
    }, "Failed: sales_getNoQuoteReason"),
  );

  server.registerTool(
    "sales_getNoQuoteReasons",
    {
      description: "get no quote reasons",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getNoQuoteReasons(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: sales_getNoQuoteReasons"),
  );

  server.registerTool(
    "sales_getOpportunity",
    {
      description: "get opportunity",
      inputSchema: z.object({
      opportunityId: z.string().nullable(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getOpportunity(ctx.client, params.opportunityId);
      return toMcpResult(result);
    }, "Failed: sales_getOpportunity"),
  );

  server.registerTool(
    "sales_getOpportunityDocuments",
    {
      description: "get opportunity documents",
      inputSchema: z.object({
      opportunityId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getOpportunityDocuments(ctx.client, ctx.companyId, params.opportunityId);
      return toMcpResult(result);
    }, "Failed: sales_getOpportunityDocuments"),
  );

  server.registerTool(
    "sales_getOpportunityLineDocuments",
    {
      description: "get opportunity line documents",
      inputSchema: z.object({
      lineId: z.string(),
      itemId: z.string().nullable().optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getOpportunityLineDocuments(ctx.client, ctx.companyId, params.lineId, params.itemId);
      return toMcpResult(result);
    }, "Failed: sales_getOpportunityLineDocuments"),
  );

  server.registerTool(
    "sales_getQuote",
    {
      description: "get quote",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuote(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuote"),
  );

  server.registerTool(
    "sales_getQuoteFavorites",
    {
      description: "get quote favorites",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteFavorites(ctx.client, ctx.companyId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteFavorites"),
  );

  server.registerTool(
    "sales_getQuotes",
    {
      description: "get quotes",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuotes(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: sales_getQuotes"),
  );

  server.registerTool(
    "sales_getQuotesList",
    {
      description: "get quotes list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuotesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: sales_getQuotesList"),
  );

  server.registerTool(
    "sales_getQuoteAssembliesByLine",
    {
      description: "get quote assemblies by line",
      inputSchema: z.object({
      quoteLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteAssembliesByLine(ctx.client, params.quoteLineId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteAssembliesByLine"),
  );

  server.registerTool(
    "sales_getQuoteAssemblies",
    {
      description: "get quote assemblies",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteAssemblies(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteAssemblies"),
  );

  server.registerTool(
    "sales_getQuoteCustomerDetails",
    {
      description: "get quote customer details",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteCustomerDetails(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteCustomerDetails"),
  );

  server.registerTool(
    "sales_getQuoteLine",
    {
      description: "get quote line",
      inputSchema: z.object({
      quoteLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteLine(ctx.client, params.quoteLineId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteLine"),
  );

  server.registerTool(
    "sales_getQuoteLinesList",
    {
      description: "get quote lines list",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteLinesList(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteLinesList"),
  );

  server.registerTool(
    "sales_getQuoteMakeMethod",
    {
      description: "get quote make method",
      inputSchema: z.object({
      quoteMakeMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteMakeMethod(ctx.client, params.quoteMakeMethodId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteMakeMethod"),
  );

  server.registerTool(
    "sales_getRootQuoteMakeMethod",
    {
      description: "get root quote make method",
      inputSchema: z.object({
      quoteLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getRootQuoteMakeMethod(ctx.client, params.quoteLineId);
      return toMcpResult(result);
    }, "Failed: sales_getRootQuoteMakeMethod"),
  );

  server.registerTool(
    "sales_getQuoteMethodTrees",
    {
      description: "get quote method trees",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteMethodTrees(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteMethodTrees"),
  );

  server.registerTool(
    "sales_getQuoteMethodTreeArray",
    {
      description: "get quote method tree array",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteMethodTreeArray(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteMethodTreeArray"),
  );

  server.registerTool(
    "sales_getQuoteLines",
    {
      description: "get quote lines",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteLines(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteLines"),
  );

  server.registerTool(
    "sales_getQuoteByExternalId",
    {
      description: "get quote by external id",
      inputSchema: z.object({
      externalId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteByExternalId(ctx.client, params.externalId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteByExternalId"),
  );

  server.registerTool(
    "sales_getQuoteLinePrices",
    {
      description: "get quote line prices",
      inputSchema: z.object({
      quoteLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteLinePrices(ctx.client, params.quoteLineId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteLinePrices"),
  );

  server.registerTool(
    "sales_getQuoteLinePricesByQuoteId",
    {
      description: "get quote line prices by quote id",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteLinePricesByQuoteId(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteLinePricesByQuoteId"),
  );

  server.registerTool(
    "sales_getQuoteLinePricesByItemId",
    {
      description: "get quote line prices by item id",
      inputSchema: z.object({
      itemId: z.string(),
      currentQuoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteLinePricesByItemId(ctx.client, params.itemId, params.currentQuoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteLinePricesByItemId"),
  );

  server.registerTool(
    "sales_getQuoteLinePricesByItemIds",
    {
      description: "get quote line prices by item ids",
      inputSchema: z.object({
      itemIds: z.array(z.string()),
      currentQuoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteLinePricesByItemIds(ctx.client, params.itemIds, params.currentQuoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteLinePricesByItemIds"),
  );

  server.registerTool(
    "sales_getQuoteMaterials",
    {
      description: "get quote materials",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteMaterials(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteMaterials"),
  );

  server.registerTool(
    "sales_getQuoteMaterial",
    {
      description: "get quote material",
      inputSchema: z.object({
      materialId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteMaterial(ctx.client, params.materialId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteMaterial"),
  );

  server.registerTool(
    "sales_getQuoteMaterialsByLine",
    {
      description: "get quote materials by line",
      inputSchema: z.object({
      quoteLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteMaterialsByLine(ctx.client, params.quoteLineId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteMaterialsByLine"),
  );

  server.registerTool(
    "sales_getQuoteMaterialsByMethodId",
    {
      description: "get quote materials by method id",
      inputSchema: z.object({
      quoteMakeMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteMaterialsByMethodId(ctx.client, params.quoteMakeMethodId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteMaterialsByMethodId"),
  );

  server.registerTool(
    "sales_getQuoteMaterialsByOperation",
    {
      description: "get quote materials by operation",
      inputSchema: z.object({
      quoteOperationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteMaterialsByOperation(ctx.client, params.quoteOperationId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteMaterialsByOperation"),
  );

  server.registerTool(
    "sales_getQuoteOperation",
    {
      description: "get quote operation",
      inputSchema: z.object({
      quoteOperationId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteOperation(ctx.client, params.quoteOperationId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteOperation"),
  );

  server.registerTool(
    "sales_getQuoteOperationsByLine",
    {
      description: "get quote operations by line",
      inputSchema: z.object({
      quoteLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteOperationsByLine(ctx.client, params.quoteLineId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteOperationsByLine"),
  );

  server.registerTool(
    "sales_getQuoteOperationsByMethodId",
    {
      description: "get quote operations by method id",
      inputSchema: z.object({
      quoteMakeMethodId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteOperationsByMethodId(ctx.client, params.quoteMakeMethodId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteOperationsByMethodId"),
  );

  server.registerTool(
    "sales_getQuoteOperations",
    {
      description: "get quote operations",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteOperations(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteOperations"),
  );

  server.registerTool(
    "sales_getQuotePayment",
    {
      description: "get quote payment",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuotePayment(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuotePayment"),
  );

  server.registerTool(
    "sales_getQuoteShipment",
    {
      description: "get quote shipment",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getQuoteShipment(ctx.client, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getQuoteShipment"),
  );

  server.registerTool(
    "sales_getRelatedPricesForQuoteLine",
    {
      description: "get related prices for quote line",
      inputSchema: z.object({
      itemId: z.string(),
      quoteId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getRelatedPricesForQuoteLine(ctx.client, params.itemId, params.quoteId);
      return toMcpResult(result);
    }, "Failed: sales_getRelatedPricesForQuoteLine"),
  );

  server.registerTool(
    "sales_getSalesDocumentsAssignedToMe",
    {
      description: "get sales documents assigned to me",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesDocumentsAssignedToMe(ctx.client, ctx.userId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesDocumentsAssignedToMe"),
  );

  server.registerTool(
    "sales_getSalesOrder",
    {
      description: "get sales order",
      inputSchema: z.object({
      salesOrderId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrder(ctx.client, params.salesOrderId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrder"),
  );

  server.registerTool(
    "sales_getSalesOrderCustomerDetails",
    {
      description: "get sales order customer details",
      inputSchema: z.object({
      salesOrderId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderCustomerDetails(ctx.client, params.salesOrderId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderCustomerDetails"),
  );

  server.registerTool(
    "sales_getSalesOrderFavorites",
    {
      description: "get sales order favorites",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderFavorites(ctx.client, ctx.companyId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderFavorites"),
  );

  server.registerTool(
    "sales_getSalesOrderRelatedItems",
    {
      description: "get sales order related items",
      inputSchema: z.object({
      salesOrderId: z.string(),
      opportunityId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderRelatedItems(ctx.client, params.salesOrderId, params.opportunityId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderRelatedItems"),
  );

  server.registerTool(
    "sales_getSalesOrders",
    {
      description: "get sales orders",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable(),
    status: z.string().nullable(),
    customerId: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrders(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrders"),
  );

  server.registerTool(
    "sales_getSalesOrdersList",
    {
      description: "get sales orders list",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrdersList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrdersList"),
  );

  server.registerTool(
    "sales_getSalesOrderPayment",
    {
      description: "get sales order payment",
      inputSchema: z.object({
      salesOrderId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderPayment(ctx.client, params.salesOrderId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderPayment"),
  );

  server.registerTool(
    "sales_getSalesTerms",
    {
      description: "get sales terms",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesTerms(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesTerms"),
  );

  server.registerTool(
    "sales_getSalesOrderShipment",
    {
      description: "get sales order shipment",
      inputSchema: z.object({
      salesOrderId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderShipment(ctx.client, params.salesOrderId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderShipment"),
  );

  server.registerTool(
    "sales_getSalesOrderCustomers",
    {
      description: "get sales order customers",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderCustomers(ctx.client);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderCustomers"),
  );

  server.registerTool(
    "sales_getSalesOrderLines",
    {
      description: "get sales order lines",
      inputSchema: z.object({
      salesOrderId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderLines(ctx.client, params.salesOrderId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderLines"),
  );

  server.registerTool(
    "sales_getSalesOrderInvoiceLines",
    {
      description: "get sales order invoice lines",
      inputSchema: z.object({
      salesOrderId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderInvoiceLines(ctx.client, params.salesOrderId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderInvoiceLines"),
  );

  server.registerTool(
    "sales_getSalesOrderInvoicesByIds",
    {
      description: "get sales order invoices by ids",
      inputSchema: z.object({
      invoiceIds: z.array(z.string()),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderInvoicesByIds(ctx.client, params.invoiceIds);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderInvoicesByIds"),
  );

  server.registerTool(
    "sales_getSalesOrderLinesByItemId",
    {
      description: "get sales order lines by item id",
      inputSchema: z.object({
      itemId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderLinesByItemId(ctx.client, params.itemId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderLinesByItemId"),
  );

  server.registerTool(
    "sales_getSalesOrderLinesByItemIds",
    {
      description: "get sales order lines by item ids",
      inputSchema: z.object({
      itemIds: z.array(z.string()),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderLinesByItemIds(ctx.client, params.itemIds);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderLinesByItemIds"),
  );

  server.registerTool(
    "sales_getSalesOrderLine",
    {
      description: "get sales order line",
      inputSchema: z.object({
      salesOrderLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderLine(ctx.client, params.salesOrderLineId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderLine"),
  );

  server.registerTool(
    "sales_getSalesOrderLineShipments",
    {
      description: "get sales order line shipments",
      inputSchema: z.object({
      salesOrderLineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrderLineShipments(ctx.client, params.salesOrderLineId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesOrderLineShipments"),
  );

  server.registerTool(
    "sales_getSalesRFQ",
    {
      description: "get sales r f q",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesRFQ(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: sales_getSalesRFQ"),
  );

  server.registerTool(
    "sales_getSalesRFQFavorites",
    {
      description: "get sales r f q favorites",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesRFQFavorites(ctx.client, ctx.companyId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesRFQFavorites"),
  );

  server.registerTool(
    "sales_getSalesRFQs",
    {
      description: "get sales r f qs",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesRFQs(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: sales_getSalesRFQs"),
  );

  server.registerTool(
    "sales_getSalesRFQLine",
    {
      description: "get sales r f q line",
      inputSchema: z.object({
      lineId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesRFQLine(ctx.client, params.lineId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesRFQLine"),
  );

  server.registerTool(
    "sales_getSalesRFQLines",
    {
      description: "get sales r f q lines",
      inputSchema: z.object({
      salesRfqId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesRFQLines(ctx.client, params.salesRfqId);
      return toMcpResult(result);
    }, "Failed: sales_getSalesRFQLines"),
  );

  server.registerTool(
    "sales_insertCustomerContact",
    {
      description: "insert customer contact",
      inputSchema: z.object({
      customerContact: customerContactValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertCustomerContact(ctx.client, { ...params.customerContact, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: sales_insertCustomerContact"),
  );

  server.registerTool(
    "sales_insertCustomerLocation",
    {
      description: "insert customer location",
      inputSchema: z.object({
      customerLocation: z.object({
    customerId: z.string(),
    name: z.string(),
    address: z.any(),
    addressLine1: z.string().optional(),
    addressLine2: z.string().optional(),
    city: z.string().optional(),
    stateProvince: z.string().optional(),
    countryCode: z.string().optional(),
    postalCode: z.string().optional(),
    customFields: z.any().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertCustomerLocation(ctx.client, { ...params.customerLocation, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: sales_insertCustomerLocation"),
  );

  server.registerTool(
    "sales_insertSalesOrderLines",
    {
      description: "insert sales order lines",
      inputSchema: z.object({
      salesOrderLines: salesOrderLineValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertSalesOrderLines(ctx.client, { ...params.salesOrderLines, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_insertSalesOrderLines"),
  );

  server.registerTool(
    "sales_finalizeQuote",
    {
      description: "finalize quote",
      inputSchema: z.object({
      quoteId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await finalizeQuote(ctx.client, params.quoteId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: sales_finalizeQuote"),
  );

  server.registerTool(
    "sales_releaseSalesOrder",
    {
      description: "release sales order",
      inputSchema: z.object({
      salesOrderId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await releaseSalesOrder(ctx.client, params.salesOrderId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: sales_releaseSalesOrder"),
  );

  server.registerTool(
    "sales_upsertCustomer",
    {
      description: "upsert customer",
      inputSchema: z.object({
      customer: customerValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertCustomer(ctx.client, { ...params.customer, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertCustomer"),
  );

  server.registerTool(
    "sales_updateCustomerAccounting",
    {
      description: "update customer accounting",
      inputSchema: z.object({
      customerAccounting: customerAccountingValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateCustomerAccounting(ctx.client, { ...params.customerAccounting, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateCustomerAccounting"),
  );

  server.registerTool(
    "sales_updateCustomerContact",
    {
      description: "update customer contact",
      inputSchema: z.object({
      customerContact: customerContactValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateCustomerContact(ctx.client, params.customerContact);
      return toMcpResult(result);
    }, "Failed: sales_updateCustomerContact"),
  );

  server.registerTool(
    "sales_updateCustomerLocation",
    {
      description: "update customer location",
      inputSchema: z.object({
      customerLocation: z.object({
    addressId: z.string(),
    name: z.string(),
    address: z.any(),
    addressLine1: z.string().optional(),
    addressLine2: z.string().optional(),
    city: z.string().optional(),
    stateProvince: z.string().optional(),
    countryCode: z.string().optional(),
    postalCode: z.string().optional(),
    customFields: z.any().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateCustomerLocation(ctx.client, params.customerLocation);
      return toMcpResult(result);
    }, "Failed: sales_updateCustomerLocation"),
  );

  server.registerTool(
    "sales_updateCustomerPayment",
    {
      description: "update customer payment",
      inputSchema: z.object({
      customerPayment: customerPaymentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateCustomerPayment(ctx.client, { ...params.customerPayment, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateCustomerPayment"),
  );

  server.registerTool(
    "sales_updateCustomerShipping",
    {
      description: "update customer shipping",
      inputSchema: z.object({
      customerShipping: customerShippingValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateCustomerShipping(ctx.client, { ...params.customerShipping, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateCustomerShipping"),
  );

  server.registerTool(
    "sales_getCustomerTax",
    {
      description: "get customer tax",
      inputSchema: {
      customerId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomerTax(ctx.client, params.customerId);
      return toMcpResult(result);
    }, "Failed: sales_getCustomerTax"),
  );

  server.registerTool(
    "sales_updateCustomerTax",
    {
      description: "update customer tax",
      inputSchema: {
      customerTax: customerTaxValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateCustomerTax(ctx.client, { ...params.customerTax, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateCustomerTax"),
  );

  server.registerTool(
    "sales_upsertCustomerStatus",
    {
      description: "upsert customer status",
      inputSchema: z.object({
      customerStatus: customerStatusValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertCustomerStatus(ctx.client, { ...params.customerStatus, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertCustomerStatus"),
  );

  server.registerTool(
    "sales_upsertCustomerType",
    {
      description: "upsert customer type",
      inputSchema: z.object({
      customerType: customerTypeValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertCustomerType(ctx.client, { ...params.customerType, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertCustomerType"),
  );

  server.registerTool(
    "sales_upsertNoQuoteReason",
    {
      description: "upsert no quote reason",
      inputSchema: z.object({
      noQuoteReason: noQuoteReasonValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertNoQuoteReason(ctx.client, { ...params.noQuoteReason, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertNoQuoteReason"),
  );

  server.registerTool(
    "sales_updateSalesRFQFavorite",
    {
      description: "update sales r f q favorite",
      inputSchema: z.object({
      args: z.object({
    id: z.string(),
    favorite: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSalesRFQFavorite(ctx.client, { ...params.args, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateSalesRFQFavorite"),
  );

  server.registerTool(
    "sales_updateSalesRFQLineOrder",
    {
      description: "update sales r f q line order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    order: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSalesRFQLineOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateSalesRFQLineOrder"),
  );

  server.registerTool(
    "sales_updateQuoteExchangeRate",
    {
      description: "update quote exchange rate",
      inputSchema: z.object({
      data: z.object({
    id: z.string(),
    exchangeRate: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateQuoteExchangeRate(ctx.client, params.data);
      return toMcpResult(result);
    }, "Failed: sales_updateQuoteExchangeRate"),
  );

  server.registerTool(
    "sales_updateQuoteLinePrecision",
    {
      description: "update quote line precision",
      inputSchema: z.object({
      quoteLineId: z.string(),
      precision: z.number(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateQuoteLinePrecision(ctx.client, params.quoteLineId, params.precision);
      return toMcpResult(result);
    }, "Failed: sales_updateQuoteLinePrecision"),
  );

  server.registerTool(
    "sales_updateSalesOrderExchangeRate",
    {
      description: "update sales order exchange rate",
      inputSchema: z.object({
      data: z.object({
    id: z.string(),
    exchangeRate: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSalesOrderExchangeRate(ctx.client, params.data);
      return toMcpResult(result);
    }, "Failed: sales_updateSalesOrderExchangeRate"),
  );

  server.registerTool(
    "sales_updateQuoteFavorite",
    {
      description: "update quote favorite",
      inputSchema: z.object({
      args: z.object({
    id: z.string(),
    favorite: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateQuoteFavorite(ctx.client, { ...params.args, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateQuoteFavorite"),
  );

  server.registerTool(
    "sales_updateSalesRFQStatus",
    {
      description: "update sales r f q status",
      inputSchema: z.object({
      update: z.object({
    id: z.string(),
    status: z.any(),
    noQuoteReasonId: z.string().nullable(),
    assignee: z.any()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSalesRFQStatus(ctx.client, { ...params.update, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateSalesRFQStatus"),
  );

  server.registerTool(
    "sales_updateQuoteMaterialOrder",
    {
      description: "update quote material order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    order: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateQuoteMaterialOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateQuoteMaterialOrder"),
  );

  server.registerTool(
    "sales_updateQuoteOperationOrder",
    {
      description: "update quote operation order",
      inputSchema: z.object({
      updates: z.object({
    id: z.string(),
    order: z.number()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateQuoteOperationOrder(ctx.client, { ...params.updates, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateQuoteOperationOrder"),
  );

  server.registerTool(
    "sales_updateQuoteStatus",
    {
      description: "update quote status",
      inputSchema: z.object({
      update: z.object({
    id: z.string(),
    status: z.any(),
    assignee: z.any()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateQuoteStatus(ctx.client, { ...params.update, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateQuoteStatus"),
  );

  server.registerTool(
    "sales_upsertMakeMethodFromQuoteLine",
    {
      description: "upsert make method from quote line",
      inputSchema: z.object({
      lineMethod: z.object({
    itemId: z.string(),
    quoteId: z.string(),
    quoteLineId: z.string(),
    parts: z.any().optional(),
    billOfMaterial: z.boolean(),
    billOfProcess: z.boolean(),
    parameters: z.boolean(),
    tools: z.boolean(),
    steps: z.boolean(),
    workInstructions: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMakeMethodFromQuoteLine(ctx.client, { ...params.lineMethod, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertMakeMethodFromQuoteLine"),
  );

  server.registerTool(
    "sales_upsertMakeMethodFromQuoteMethod",
    {
      description: "upsert make method from quote method",
      inputSchema: z.object({
      quoteMethod: z.object({
    sourceId: z.string(),
    targetId: z.string(),
    parts: z.any().optional(),
    billOfMaterial: z.boolean(),
    billOfProcess: z.boolean(),
    parameters: z.boolean(),
    tools: z.boolean(),
    steps: z.boolean(),
    workInstructions: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertMakeMethodFromQuoteMethod(ctx.client, { ...params.quoteMethod, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertMakeMethodFromQuoteMethod"),
  );

  server.registerTool(
    "sales_upsertQuote",
    {
      description: "upsert quote",
      inputSchema: z.object({
      quote: quoteValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuote(ctx.client, { ...params.quote, companyId: ctx.companyId, companyGroupId: ctx.companyGroupId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuote"),
  );

  server.registerTool(
    "sales_upsertQuoteLine",
    {
      description: "upsert quote line",
      inputSchema: z.object({
      quotationLine: quoteLineValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuoteLine(ctx.client, { ...params.quotationLine, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuoteLine"),
  );

  server.registerTool(
    "sales_upsertQuoteLineAdditionalCharges",
    {
      description: "upsert quote line additional charges",
      inputSchema: z.object({
      lineId: z.string(),
      update: quoteLineAdditionalChargesValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuoteLineAdditionalCharges(ctx.client, params.lineId, { ...params.update, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuoteLineAdditionalCharges"),
  );

  server.registerTool(
    "sales_upsertQuoteLinePrices",
    {
      description: "upsert quote line prices",
      inputSchema: z.object({
      quoteId: z.string(),
      lineId: z.string(),
      quoteLinePrices: z.object({
    quoteLineId: z.string(),
    unitPrice: z.number(),
    leadTime: z.number(),
    discountPercent: z.number(),
    quantity: z.number(),
    categoryMarkups: z.any().optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuoteLinePrices(ctx.client, params.quoteId, params.lineId, { ...params.quoteLinePrices, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuoteLinePrices"),
  );

  server.registerTool(
    "sales_calculatePricesForQuantities",
    {
      description: "calculate prices for quantities",
      inputSchema: z.object({
      quoteId: z.string(),
      quoteLineId: z.string(),
      quantities: z.array(z.number()),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await calculatePricesForQuantities(ctx.client, params.quoteId, params.quoteLineId, params.quantities, ctx.userId);
      return toMcpResult(result);
    }, "Failed: sales_calculatePricesForQuantities"),
  );

  server.registerTool(
    "sales_recalculateQuoteLinePrices",
    {
      description: "recalculate quote line prices",
      inputSchema: z.object({
      quoteId: z.string(),
      quoteLineId: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await recalculateQuoteLinePrices(ctx.client, params.quoteId, params.quoteLineId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: sales_recalculateQuoteLinePrices"),
  );

  server.registerTool(
    "sales_upsertQuoteLineMethod",
    {
      description: "upsert quote line method",
      inputSchema: z.object({
      lineMethod: z.object({
    itemId: z.string(),
    quoteId: z.string(),
    quoteLineId: z.string(),
    configuration: z.any().optional(),
    parts: z.any().optional(),
    billOfMaterial: z.boolean(),
    billOfProcess: z.boolean(),
    parameters: z.boolean(),
    tools: z.boolean(),
    steps: z.boolean(),
    workInstructions: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuoteLineMethod(ctx.client, { ...params.lineMethod, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuoteLineMethod"),
  );

  server.registerTool(
    "sales_upsertQuoteMaterial",
    {
      description: "upsert quote material",
      inputSchema: z.object({
      quoteMaterial: quoteMaterialValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuoteMaterial(ctx.client, { ...params.quoteMaterial, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuoteMaterial"),
  );

  server.registerTool(
    "sales_upsertQuoteMaterialMakeMethod",
    {
      description: "upsert quote material make method",
      inputSchema: z.object({
      quoteMethod: z.object({
    sourceId: z.string(),
    targetId: z.string(),
    configuration: z.any().optional(),
    parts: z.any().optional(),
    billOfMaterial: z.boolean(),
    billOfProcess: z.boolean(),
    parameters: z.boolean(),
    tools: z.boolean(),
    steps: z.boolean(),
    workInstructions: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuoteMaterialMakeMethod(ctx.client, { ...params.quoteMethod, companyId: ctx.companyId, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuoteMaterialMakeMethod"),
  );

  server.registerTool(
    "sales_upsertQuoteOperation",
    {
      description: "upsert quote operation",
      inputSchema: z.object({
      operation: quoteOperationValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuoteOperation(ctx.client, { ...params.operation, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuoteOperation"),
  );

  server.registerTool(
    "sales_upsertQuoteOperationStep",
    {
      description: "upsert quote operation step",
      inputSchema: z.object({
      quoteOperationStep: operationStepValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuoteOperationStep(ctx.client, { ...params.quoteOperationStep, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuoteOperationStep"),
  );

  server.registerTool(
    "sales_upsertQuoteOperationParameter",
    {
      description: "upsert quote operation parameter",
      inputSchema: z.object({
      quoteOperationParameter: operationParameterValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuoteOperationParameter(ctx.client, { ...params.quoteOperationParameter, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuoteOperationParameter"),
  );

  server.registerTool(
    "sales_upsertQuoteOperationTool",
    {
      description: "upsert quote operation tool",
      inputSchema: z.object({
      quoteOperationTool: operationToolValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuoteOperationTool(ctx.client, { ...params.quoteOperationTool, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuoteOperationTool"),
  );

  server.registerTool(
    "sales_upsertQuotePayment",
    {
      description: "upsert quote payment",
      inputSchema: z.object({
      quotePayment: quotePaymentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuotePayment(ctx.client, { ...params.quotePayment, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuotePayment"),
  );

  server.registerTool(
    "sales_upsertQuoteShipment",
    {
      description: "upsert quote shipment",
      inputSchema: z.object({
      quoteShipment: quoteShipmentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertQuoteShipment(ctx.client, { ...params.quoteShipment, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertQuoteShipment"),
  );

  server.registerTool(
    "sales_updateSalesOrderFavorite",
    {
      description: "update sales order favorite",
      inputSchema: z.object({
      args: z.object({
    id: z.string(),
    favorite: z.boolean()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSalesOrderFavorite(ctx.client, { ...params.args, userId: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateSalesOrderFavorite"),
  );

  server.registerTool(
    "sales_updateSalesOrderStatus",
    {
      description: "update sales order status",
      inputSchema: z.object({
      update: z.object({
    id: z.string(),
    status: z.any(),
    assignee: z.any()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSalesOrderStatus(ctx.client, { ...params.update, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_updateSalesOrderStatus"),
  );

  server.registerTool(
    "sales_upsertSalesOrder",
    {
      description: "upsert sales order",
      inputSchema: z.object({
      salesOrder: salesOrderValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSalesOrder(ctx.client, { ...params.salesOrder, companyId: ctx.companyId, companyGroupId: ctx.companyGroupId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertSalesOrder"),
  );

  server.registerTool(
    "sales_upsertSalesOrderShipment",
    {
      description: "upsert sales order shipment",
      inputSchema: z.object({
      salesOrderShipment: salesOrderShipmentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSalesOrderShipment(ctx.client, { ...params.salesOrderShipment, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertSalesOrderShipment"),
  );

  server.registerTool(
    "sales_upsertSalesOrderLine",
    {
      description: "upsert sales order line",
      inputSchema: z.object({
      salesOrderLine: salesOrderLineValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSalesOrderLine(ctx.client, { ...params.salesOrderLine, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertSalesOrderLine"),
  );

  server.registerTool(
    "sales_upsertSalesOrderPayment",
    {
      description: "upsert sales order payment",
      inputSchema: z.object({
      salesOrderPayment: salesOrderPaymentValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSalesOrderPayment(ctx.client, { ...params.salesOrderPayment, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertSalesOrderPayment"),
  );

  server.registerTool(
    "sales_upsertSalesRFQ",
    {
      description: "upsert sales r f q",
      inputSchema: z.object({
      rfq: salesRfqValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSalesRFQ(ctx.client, { ...params.rfq, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertSalesRFQ"),
  );

  server.registerTool(
    "sales_upsertSalesRFQLine",
    {
      description: "upsert sales r f q line",
      inputSchema: z.object({
      salesRfqLine: salesRfqLineValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertSalesRFQLine(ctx.client, { ...params.salesRfqLine, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: sales_upsertSalesRFQLine"),
  );
};
