"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SuppliersTable = exports.SupplierTaxForm = exports.SupplierSidebar = exports.SupplierShippingForm = exports.SupplierProcesses = exports.SupplierProcessForm = exports.SupplierPaymentForm = exports.SupplierLocations = exports.SupplierLocationForm = exports.SupplierHeader = exports.SupplierForm = exports.SupplierContacts = exports.SupplierContactForm = void 0;
var SupplierContactForm_1 = require("./SupplierContactForm");
exports.SupplierContactForm = SupplierContactForm_1.default;
var SupplierContacts_1 = require("./SupplierContacts");
exports.SupplierContacts = SupplierContacts_1.default;
var SupplierForm_1 = require("./SupplierForm");
exports.SupplierForm = SupplierForm_1.default;
var SupplierHeader_1 = require("./SupplierHeader");
exports.SupplierHeader = SupplierHeader_1.default;
var SupplierLocationForm_1 = require("./SupplierLocationForm");
exports.SupplierLocationForm = SupplierLocationForm_1.default;
var SupplierLocations_1 = require("./SupplierLocations");
exports.SupplierLocations = SupplierLocations_1.default;
var SupplierPaymentForm_1 = require("./SupplierPaymentForm");
exports.SupplierPaymentForm = SupplierPaymentForm_1.default;
var SupplierProcesses_1 = require("./SupplierProcesses");
exports.SupplierProcesses = SupplierProcesses_1.default;
var SupplierProcessForm_1 = require("./SupplierProcessForm");
exports.SupplierProcessForm = SupplierProcessForm_1.default;
var SupplierShippingForm_1 = require("./SupplierShippingForm");
exports.SupplierShippingForm = SupplierShippingForm_1.default;
var SupplierSidebar_1 = require("./SupplierSidebar");
exports.SupplierSidebar = SupplierSidebar_1.default;
var SuppliersTable_1 = require("./SuppliersTable");
exports.SuppliersTable = SuppliersTable_1.default;
var SupplierTaxForm_1 = require("./SupplierTaxForm");
exports.SupplierTaxForm = SupplierTaxForm_1.default;
