"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AttributeForm = exports.AttributeCategoryForm = exports.AttributeCategoryDetail = exports.AttributeCategoriesTable = void 0;
var AttributeCategoriesTable_1 = require("./AttributeCategoriesTable");
exports.AttributeCategoriesTable = AttributeCategoriesTable_1.default;
var AttributeCategoryDetail_1 = require("./AttributeCategoryDetail");
exports.AttributeCategoryDetail = AttributeCategoryDetail_1.default;
var AttributeCategoryForm_1 = require("./AttributeCategoryForm");
exports.AttributeCategoryForm = AttributeCategoryForm_1.default;
var AttributeForm_1 = require("./AttributeForm");
exports.AttributeForm = AttributeForm_1.default;
