#pragma once
#include <cstdint>
#include "rust/cxx.h"

namespace carbon_occt {
struct Tree;  // generated by cxx from the shared struct

Tree read_step(rust::Str path, double linear_deflection, double angular_deflection);

Tree read_iges(rust::Str path, double linear_deflection, double angular_deflection);

Tree read_brep(rust::Str path, double linear_deflection, double angular_deflection);

bool step_to_xbf(rust::Str step_path, rust::Str xbf_path);

Tree read_xbf(rust::Str path, double linear_deflection, double angular_deflection);

bool write_test_step(rust::Str path, uint32_t boxes);
}  // namespace carbon_occt
