#pragma once
#include "rust/cxx.h"
#include <cstdint>

namespace carbon_draco {
struct DracoEncoded;  // generated by cxx from the shared struct

DracoEncoded encode_mesh(rust::Slice<const float> positions,
                         rust::Slice<const float> normals,
                         rust::Slice<const float> uvs,
                         rust::Slice<const uint32_t> indices, int32_t pos_bits,
                         int32_t norm_bits, int32_t uv_bits);
}  // namespace carbon_draco
