"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.useSelectedLang = exports.useApiDocsConfig = exports.TableDocs = exports.Snippets = exports.CodeSnippet = exports.ApiDocsProvider = void 0;
var ApiDocsContext_1 = require("./ApiDocsContext");
Object.defineProperty(exports, "ApiDocsProvider", { enumerable: true, get: function () { return ApiDocsContext_1.ApiDocsProvider; } });
Object.defineProperty(exports, "useApiDocsConfig", { enumerable: true, get: function () { return ApiDocsContext_1.useApiDocsConfig; } });
var CodeSnippet_1 = require("./CodeSnippet");
exports.CodeSnippet = CodeSnippet_1.default;
var Snippets_1 = require("./Snippets");
exports.Snippets = Snippets_1.default;
var TableDocs_1 = require("./TableDocs");
exports.TableDocs = TableDocs_1.default;
var useSelectedLang_1 = require("./useSelectedLang");
Object.defineProperty(exports, "useSelectedLang", { enumerable: true, get: function () { return useSelectedLang_1.useSelectedLang; } });
