"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FixedAssetsTable = exports.FixedAssetStatus = exports.FixedAssetRegisterForm = exports.FixedAssetNotes = exports.FixedAssetForm = exports.FixedAssetDisposalForm = exports.DepreciationRunTable = exports.DepreciationRunStatus = exports.AssetClassesTable = exports.AssetClassForm = void 0;
var AssetClassesTable_1 = require("./AssetClassesTable");
exports.AssetClassesTable = AssetClassesTable_1.default;
var AssetClassForm_1 = require("./AssetClassForm");
exports.AssetClassForm = AssetClassForm_1.default;
var DepreciationRunStatus_1 = require("./DepreciationRunStatus");
exports.DepreciationRunStatus = DepreciationRunStatus_1.default;
var DepreciationRunTable_1 = require("./DepreciationRunTable");
exports.DepreciationRunTable = DepreciationRunTable_1.default;
var FixedAssetDisposalForm_1 = require("./FixedAssetDisposalForm");
exports.FixedAssetDisposalForm = FixedAssetDisposalForm_1.default;
var FixedAssetForm_1 = require("./FixedAssetForm");
exports.FixedAssetForm = FixedAssetForm_1.default;
var FixedAssetNotes_1 = require("./FixedAssetNotes");
exports.FixedAssetNotes = FixedAssetNotes_1.default;
var FixedAssetRegisterForm_1 = require("./FixedAssetRegisterForm");
exports.FixedAssetRegisterForm = FixedAssetRegisterForm_1.default;
var FixedAssetStatus_1 = require("./FixedAssetStatus");
exports.FixedAssetStatus = FixedAssetStatus_1.default;
var FixedAssetsTable_1 = require("./FixedAssetsTable");
exports.FixedAssetsTable = FixedAssetsTable_1.default;
