"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.overlayRegistry = exports.getOverlayRegistryEntry = exports.overlay = exports.useOverlay = exports.OverlayProvider = exports.OverlayHost = void 0;
var OverlayHost_1 = require("./OverlayHost");
Object.defineProperty(exports, "OverlayHost", { enumerable: true, get: function () { return OverlayHost_1.OverlayHost; } });
var OverlayProvider_1 = require("./OverlayProvider");
Object.defineProperty(exports, "OverlayProvider", { enumerable: true, get: function () { return OverlayProvider_1.OverlayProvider; } });
Object.defineProperty(exports, "useOverlay", { enumerable: true, get: function () { return OverlayProvider_1.useOverlay; } });
var overlay_1 = require("./overlay");
Object.defineProperty(exports, "overlay", { enumerable: true, get: function () { return overlay_1.overlay; } });
var overlay_registry_1 = require("./overlay.registry");
Object.defineProperty(exports, "getOverlayRegistryEntry", { enumerable: true, get: function () { return overlay_registry_1.getOverlayRegistryEntry; } });
Object.defineProperty(exports, "overlayRegistry", { enumerable: true, get: function () { return overlay_registry_1.overlayRegistry; } });
