"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SUPABASE_URL = exports.SUPABASE_SERVICE_ROLE_KEY = exports.SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI = exports.SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET = exports.SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID = exports.SUPABASE_ACCESS_TOKEN = void 0;
var dotenv = require("dotenv");
dotenv.config();
var SUPABASE_URL = process.env.SUPABASE_URL;
exports.SUPABASE_URL = SUPABASE_URL;
var SUPABASE_SERVICE_ROLE_KEY = process.env
    .SUPABASE_SERVICE_ROLE_KEY;
exports.SUPABASE_SERVICE_ROLE_KEY = SUPABASE_SERVICE_ROLE_KEY;
var SUPABASE_ACCESS_TOKEN = process.env.SUPABASE_ACCESS_TOKEN;
exports.SUPABASE_ACCESS_TOKEN = SUPABASE_ACCESS_TOKEN;
var SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID = process.env
    .SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID;
exports.SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID = SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID;
var SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET = process.env
    .SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET;
exports.SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET = SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET;
var SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI = process.env
    .SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI;
exports.SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI = SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI;
if (!SUPABASE_ACCESS_TOKEN)
    throw new Error("Missing SUPABASE_ACCESS_TOKEN");
if (!SUPABASE_URL)
    throw new Error("Missing SUPABASE_URL");
if (!SUPABASE_SERVICE_ROLE_KEY)
    throw new Error("Missing SUPABASE_SERVICE_ROLE_KEY");
