import type { MessageDescriptor } from "@lingui/core";
import { msg } from "@lingui/core/macro";

/**
 * English display names from seed data (packages/database/supabase/functions/lib/seed.data.ts).
 * Use with translateSeedDisplayName() so locales can translate seeded defaults; unknown names pass through.
 */
const seedDisplayNameMessages: Record<string, MessageDescriptor> = {
  "1% 10 Net 30": msg`1% 10 Net 30`,
  "2% 10 Net 30": msg`2% 10 Net 30`,
  "Accounts Payable": msg`Accounts Payable`,
  "Accounts Receivable": msg`Accounts Receivable`,
  "Accrued Expenses": msg`Accrued Expenses`,
  "Accrued Wages & Salaries": msg`Accrued Wages & Salaries`,
  "Accumulated Amortization": msg`Accumulated Amortization`,
  "Accumulated Depreciation": msg`Accumulated Depreciation`,
  "Accumulated Depreciation on Disposal": msg`Accumulated Depreciation on Disposal`,
  "Advertising & Marketing": msg`Advertising & Marketing`,
  "All Customers": msg`All Customers`,
  "All Employees": msg`All Employees`,
  "All Suppliers": msg`All Suppliers`,
  "Assets": msg`Assets`,
  "Bad Debts Expense": msg`Bad Debts Expense`,
  "Bag": msg`Bag`,
  "Balance Sheet": msg`Balance Sheet`,
  "Bank - Cash": msg`Bank - Cash`,
  "Bank - Foreign Currency": msg`Bank - Foreign Currency`,
  "Bank - Local Currency": msg`Bank - Local Currency`,
  "Bank Charges & Fees": msg`Bank Charges & Fees`,
  "Box": msg`Box`,
  "Buildings & Leasehold Improvements": msg`Buildings & Leasehold Improvements`,
  "Case": msg`Case`,
  "Cash & Bank": msg`Cash & Bank`,
  "COD": msg`COD`,
  "Common Stock / Share Capital": msg`Common Stock / Share Capital`,
  "Containment Action": msg`Containment Action`,
  "Corrective Action": msg`Corrective Action`,
  "Cost Center": msg`Cost Center`,
  "Cost of Goods Sold": msg`Cost of Goods Sold`,
  "Cost of Goods Sold - Direct": msg`Cost of Goods Sold - Direct`,
  "Current Liabilities": msg`Current Liabilities`,
  "Customer Communication": msg`Customer Communication`,
  "Customer Complaint": msg`Customer Complaint`,
  "Customer Payment Discounts": msg`Customer Payment Discounts`,
  "Customer Prepayments": msg`Customer Prepayments`,
  "Customer Type": msg`Customer Type`,
  "Deferred Revenue": msg`Deferred Revenue`,
  "Deferred Tax Assets": msg`Deferred Tax Assets`,
  "Deferred Tax Liabilities": msg`Deferred Tax Liabilities`,
  "Department": msg`Department`,
  "Depreciation & Amortization": msg`Depreciation & Amortization`,
  "Depreciation Expense": msg`Depreciation Expense`,
  "Design Error": msg`Design Error`,
  "Dividends Payable": msg`Dividends Payable`,
  "Documentation": msg`Documentation`,
  "Documentation Error": msg`Documentation Error`,
  "Drum": msg`Drum`,
  "Each": msg`Each`,
  "Employee": msg`Employee`,
  "Equipment Malfunction": msg`Equipment Malfunction`,
  "Equity": msg`Equity`,
  "Finished Goods": msg`Finished Goods`,
  "Fixed Asset Acquisition Cost": msg`Fixed Asset Acquisition Cost`,
  "Fixed Asset Acquisition Cost on Disposal": msg`Fixed Asset Acquisition Cost on Disposal`,
  "Foot": msg`Foot`,
  "Foreign Exchange Gains": msg`Foreign Exchange Gains`,
  "Foreign Exchange Losses": msg`Foreign Exchange Losses`,
  "Freight & Shipping Out": msg`Freight & Shipping Out`,
  "Gains and Losses on Disposal": msg`Gains and Losses on Disposal`,
  "Gallon": msg`Gallon`,
  "Gauge": msg`Gauge`,
  "GR/IR Clearing": msg`GR/IR Clearing`,
  "Headquarters": msg`Headquarters`,
  "Inbound Inspection": msg`Inbound Inspection`,
  "Inch": msg`Inch`,
  "Income Statement": msg`Income Statement`,
  "Income Tax Expense": msg`Income Tax Expense`,
  "Incoming Materials": msg`Incoming Materials`,
  "Indirect Materials & Services": msg`Indirect Materials & Services`,
  "Insurance": msg`Insurance`,
  "Intangible Assets": msg`Intangible Assets`,
  "Inter-Company Payables": msg`Inter-Company Payables`,
  "Inter-Company Receivables": msg`Inter-Company Receivables`,
  "Interest Expense": msg`Interest Expense`,
  "Inventory": msg`Inventory`,
  "Inventory & Stock": msg`Inventory & Stock`,
  "Inventory Adjustment": msg`Inventory Adjustment`,
  "Inventory Adjustments": msg`Inventory Adjustments`,
  "Inventory Reserves / Allowances": msg`Inventory Reserves / Allowances`,
  "Inventory Shipped Not Invoiced": msg`Inventory Shipped Not Invoiced`,
  "Investments in Subsidiaries": msg`Investments in Subsidiaries`,
  "Issue": msg`Issue`,
  "Item Posting Group": msg`Item Posting Group`,
  "Job": msg`Job`,
  "Journal Entry": msg`Journal Entry`,
  "Labor & Machine Absorption": msg`Labor & Machine Absorption`,
  "Labor & Machine Variance": msg`Labor & Machine Variance`,
  "Liabilities": msg`Liabilities`,
  "Liter": msg`Liter`,
  "Location": msg`Location`,
  "Long-Term Debt / Loans": msg`Long-Term Debt / Loans`,
  "Long-Term Liabilities": msg`Long-Term Liabilities`,
  "Lot Size Variance": msg`Lot Size Variance`,
  "Machinery & Equipment": msg`Machinery & Equipment`,
  "Maintenance Dispatch": msg`Maintenance Dispatch`,
  "Maintenance Expense": msg`Maintenance Expense`,
  "Manufacturing Defect": msg`Manufacturing Defect`,
  "Manufacturing Services Revenue": msg`Manufacturing Services Revenue`,
  "Material Issue": msg`Material Issue`,
  "Material Usage Variance": msg`Material Usage Variance`,
  "Meter": msg`Meter`,
  "Net 15": msg`Net 15`,
  "Net 30": msg`Net 30`,
  "Net 60": msg`Net 60`,
  "Net EOM 10th": msg`Net EOM 10th`,
  "Operating Expenses": msg`Operating Expenses`,
  "Other Assets": msg`Other Assets`,
  "Other Expenses": msg`Other Expenses`,
  "Other Income": msg`Other Income`,
  "Ounce": msg`Ounce`,
  "Overhead Variance": msg`Overhead Variance`,
  "Pack": msg`Pack`,
  "Pallet": msg`Pallet`,
  "Payables": msg`Payables`,
  "Pension Obligations": msg`Pension Obligations`,
  "Pound": msg`Pound`,
  "Prepaid/ Pro forma": msg`Prepaid/ Pro forma`,
  "Preventive Action": msg`Preventive Action`,
  "Process": msg`Process`,
  "Process Deviation": msg`Process Deviation`,
  "Professional Fees": msg`Professional Fees`,
  "Property, Plant & Equipment": msg`Property, Plant & Equipment`,
  "Purchase Invoice": msg`Purchase Invoice`,
  "Purchase Order": msg`Purchase Order`,
  "Purchase Price Variance": msg`Purchase Price Variance`,
  "Purchase Tax Payable": msg`Purchase Tax Payable`,
  "Purchasing RFQ": msg`Purchasing RFQ`,
  "Quote": msg`Quote`,
  "R&D Expenses": msg`R&D Expenses`,
  "Receipt": msg`Receipt`,
  "Receivables": msg`Receivables`,
  "Rent & Utilities (Non-Factory)": msg`Rent & Utilities (Non-Factory)`,
  "Reserves (Currency Translation)": msg`Reserves (Currency Translation)`,
  "Retained Earnings": msg`Retained Earnings`,
  "Revenue": msg`Revenue`,
  "Reverse Charge Tax Payable": msg`Reverse Charge Tax Payable`,
  "RFQ (Sales)": msg`RFQ (Sales)`,
  "Roll": msg`Roll`,
  "Root Cause Analysis": msg`Root Cause Analysis`,
  "Rounding Account": msg`Rounding Account`,
  "Salaries - Administrative": msg`Salaries - Administrative`,
  "Sales": msg`Sales`,
  "Sales Commissions": msg`Sales Commissions`,
  "Sales Discounts": msg`Sales Discounts`,
  "Sales Invoice": msg`Sales Invoice`,
  "Sales Order": msg`Sales Order`,
  "Sales Tax Payable": msg`Sales Tax Payable`,
  "Scrap Sales": msg`Scrap Sales`,
  "Service Charge Account": msg`Service Charge Account`,
  "Shipment": msg`Shipment`,
  "Short-Term Loans": msg`Short-Term Loans`,
  "Stock Transfer": msg`Stock Transfer`,
  "Subcontracting Variance": msg`Subcontracting Variance`,
  "Supplier Issue": msg`Supplier Issue`,
  "Supplier Payment Discounts": msg`Supplier Payment Discounts`,
  "Supplier Quote": msg`Supplier Quote`,
  "Supplier Type": msg`Supplier Type`,
  "Tax Liabilities": msg`Tax Liabilities`,
  "Testing Failure": msg`Testing Failure`,
  "Ton": msg`Ton`,
  "Training Issue": msg`Training Issue`,
  "Travel & Entertainment": msg`Travel & Entertainment`,
  "Variances": msg`Variances`,
  "Verification": msg`Verification`,
  "Warehouse Transfer": msg`Warehouse Transfer`,
  "WIP": msg`WIP`,
  "Work In Progress (WIP)": msg`Work In Progress (WIP)`,
  "Yard": msg`Yard`,
};

export function translateSeedDisplayName(
  name: string,
  i18n: { _: (descriptor: MessageDescriptor) => string }
): string {
  const descriptor = seedDisplayNameMessages[name];
  return descriptor != null ? i18n._(descriptor) : name;
}
