import type { MessageDescriptor } from "@lingui/core";
import { msg } from "@lingui/core/macro";

/**
 * English display names from seed data (packages/database/supabase/functions/lib/seed.data.ts).
 * Use with translateSeedDisplayName() so locales can translate seeded defaults; unknown names pass through.
 */
const seedDisplayNameMessages: Record<string, MessageDescriptor> = {
  "1% 10 Net 30": msg`1% 10 Net 30`,
  "2% 10 Net 30": msg`2% 10 Net 30`,
  "Accumulated Depreciation": msg`Accumulated Depreciation`,
  "All Customers": msg`All Customers`,
  "All Employees": msg`All Employees`,
  "All Suppliers": msg`All Suppliers`,
  Assets: msg`Assets`,
  "Assets, Total": msg`Assets, Total`,
  Bag: msg`Bag`,
  "Balance Sheet": msg`Balance Sheet`,
  "Balance Sheet, Total": msg`Balance Sheet, Total`,
  "Bank - Cash": msg`Bank - Cash`,
  "Bank - Foreign Currency": msg`Bank - Foreign Currency`,
  "Bank - Local Currency": msg`Bank - Local Currency`,
  Box: msg`Box`,
  "Capacity Variance": msg`Capacity Variance`,
  Case: msg`Case`,
  COD: msg`COD`,
  "Containment Action": msg`Containment Action`,
  "Corrective Action": msg`Corrective Action`,
  "Cost of Goods Sold": msg`Cost of Goods Sold`,
  "Costs of Goods Sold": msg`Costs of Goods Sold`,
  "Costs of Goods Sold, Total": msg`Costs of Goods Sold, Total`,
  "Current Assets": msg`Current Assets`,
  "Current Assets, Total": msg`Current Assets, Total`,
  "Customer Communication": msg`Customer Communication`,
  "Customer Complaint": msg`Customer Complaint`,
  "Customer Payment Discounts": msg`Customer Payment Discounts`,
  "Customer Prepayments": msg`Customer Prepayments`,
  "Depreciation Expense": msg`Depreciation Expense`,
  "Depreciation of Fixed Assets": msg`Depreciation of Fixed Assets`,
  "Depreciation of Fixed Assets, Total": msg`Depreciation of Fixed Assets, Total`,
  "Design Error": msg`Design Error`,
  "Direct Capacity Cost": msg`Direct Capacity Cost`,
  "Direct Capacity Cost, Total": msg`Direct Capacity Cost, Total`,
  "Direct Cost Applied": msg`Direct Cost Applied`,
  Documentation: msg`Documentation`,
  "Documentation Error": msg`Documentation Error`,
  Drum: msg`Drum`,
  Each: msg`Each`,
  "Equipment Malfunction": msg`Equipment Malfunction`,
  Equity: msg`Equity`,
  "Equity, Total": msg`Equity, Total`,
  "Finished Goods": msg`Finished Goods`,
  "Fixed Asset Acquisition Cost": msg`Fixed Asset Acquisition Cost`,
  "Fixed Asset Acquisition Cost on Disposal": msg`Fixed Asset Acquisition Cost on Disposal`,
  "Fixed Asset Acquisition Depreciation on Disposal": msg`Fixed Asset Acquisition Depreciation on Disposal`,
  "Fixed Assets": msg`Fixed Assets`,
  "Fixed Assets, Total": msg`Fixed Assets, Total`,
  Foot: msg`Foot`,
  "Gains and Losses on Disposal": msg`Gains and Losses on Disposal`,
  Gallon: msg`Gallon`,
  Gauge: msg`Gauge`,
  Headquarters: msg`Headquarters`,
  "Inbound Inspection": msg`Inbound Inspection`,
  Inch: msg`Inch`,
  "Income Statement": msg`Income Statement`,
  "Income Statement, Total": msg`Income Statement, Total`,
  "Incoming Materials": msg`Incoming Materials`,
  Interest: msg`Interest`,
  "Interest Account": msg`Interest Account`,
  "Interest, Total": msg`Interest, Total`,
  Inventory: msg`Inventory`,
  "Inventory Adjustment": msg`Inventory Adjustment`,
  "Inventory Interim": msg`Inventory Interim`,
  "Inventory Invoiced Not Received": msg`Inventory Invoiced Not Received`,
  "Inventory Received Not Invoiced": msg`Inventory Received Not Invoiced`,
  "Inventory Shipped Not Invoiced": msg`Inventory Shipped Not Invoiced`,
  Issue: msg`Issue`,
  Job: msg`Job`,
  Liabilities: msg`Liabilities`,
  "Liabilities, Total": msg`Liabilities, Total`,
  Liter: msg`Liter`,
  "Maintenance Dispatch": msg`Maintenance Dispatch`,
  "Maintenance Expense": msg`Maintenance Expense`,
  "Manufacturing Defect": msg`Manufacturing Defect`,
  "Material Issue": msg`Material Issue`,
  "Material Variance": msg`Material Variance`,
  Meter: msg`Meter`,
  "Net 15": msg`Net 15`,
  "Net 30": msg`Net 30`,
  "Net 60": msg`Net 60`,
  "Net EOM 10th": msg`Net EOM 10th`,
  Ounce: msg`Ounce`,
  "Overhead Accounts": msg`Overhead Accounts`,
  "Overhead Applied": msg`Overhead Applied`,
  "Owner Equity": msg`Owner Equity`,
  Pack: msg`Pack`,
  Pallet: msg`Pallet`,
  Payables: msg`Payables`,
  Pound: msg`Pound`,
  "Prepaid/ Pro forma": msg`Prepaid/ Pro forma`,
  "Preventive Action": msg`Preventive Action`,
  Process: msg`Process`,
  "Process Deviation": msg`Process Deviation`,
  "Purchase Invoice": msg`Purchase Invoice`,
  "Purchase Order": msg`Purchase Order`,
  "Purchase Tax Payable": msg`Purchase Tax Payable`,
  "Purchase Variance": msg`Purchase Variance`,
  Purchases: msg`Purchases`,
  "Purchasing RFQ": msg`Purchasing RFQ`,
  Quote: msg`Quote`,
  Receipt: msg`Receipt`,
  Receivables: msg`Receivables`,
  "Retained Earnings": msg`Retained Earnings`,
  Revenue: msg`Revenue`,
  "Revenue, Total": msg`Revenue, Total`,
  "Reverse Charge Tax Payable": msg`Reverse Charge Tax Payable`,
  "RFQ (Sales)": msg`RFQ (Sales)`,
  Roll: msg`Roll`,
  "Root Cause Analysis": msg`Root Cause Analysis`,
  "Rounding Account": msg`Rounding Account`,
  Sales: msg`Sales`,
  "Sales Discounts": msg`Sales Discounts`,
  "Sales Invoice": msg`Sales Invoice`,
  "Sales Order": msg`Sales Order`,
  "Sales Tax Payable": msg`Sales Tax Payable`,
  "Service Charge Account": msg`Service Charge Account`,
  Shipment: msg`Shipment`,
  "Stock Transfer": msg`Stock Transfer`,
  "Supplier Issue": msg`Supplier Issue`,
  "Supplier Payment Discounts": msg`Supplier Payment Discounts`,
  "Supplier Quote": msg`Supplier Quote`,
  "Testing Failure": msg`Testing Failure`,
  Ton: msg`Ton`,
  "Training Issue": msg`Training Issue`,
  Verification: msg`Verification`,
  "Warehouse Transfer": msg`Warehouse Transfer`,
  WIP: msg`WIP`,
  "Work In Progress (WIP)": msg`Work In Progress (WIP)`,
  Yard: msg`Yard`
};

export function translateSeedDisplayName(
  name: string,
  i18n: { _: (descriptor: MessageDescriptor) => string }
): string {
  const descriptor = seedDisplayNameMessages[name];
  return descriptor != null ? i18n._(descriptor) : name;
}
