"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ProfilePhotoForm = exports.ProfileLanguageForm = exports.ProfileForm = exports.LoginMethodsForm = void 0;
var LoginMethodsForm_1 = require("./LoginMethodsForm");
exports.LoginMethodsForm = LoginMethodsForm_1.default;
var ProfileForm_1 = require("./ProfileForm");
exports.ProfileForm = ProfileForm_1.default;
var ProfileLanguageForm_1 = require("./ProfileLanguageForm");
exports.ProfileLanguageForm = ProfileLanguageForm_1.default;
var ProfilePhotoForm_1 = require("./ProfilePhotoForm");
exports.ProfilePhotoForm = ProfilePhotoForm_1.default;
