"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Constants = void 0;
exports.Constants = {
    graphql_public: {
        Enums: {},
    },
    public: {
        Enums: {
            salaryRecordStatus: ["Unpaid", "Partially Paid", "Paid"],
            accountingPeriodStatus: ["Inactive", "Active"],
            accountType: [
                "Bank",
                "Cash",
                "Accounts Receivable",
                "Accounts Payable",
                "Inventory",
                "Fixed Asset",
                "Accumulated Depreciation",
                "Other Current Asset",
                "Other Asset",
                "Other Current Liability",
                "Long Term Liability",
                "Equity - No Close",
                "Equity - Close",
                "Retained Earnings",
                "Income",
                "Cost of Goods Sold",
                "Expense",
                "Other Income",
                "Other Expense",
                "Tax",
                "Investments",
            ],
            approvalDocumentType: [
                "purchaseOrder",
                "qualityDocument",
                "supplier",
                "productionQuantityReport"
            ],
            approvalStatus: ["Pending", "Approved", "Rejected", "Cancelled"],
            membershipApplicationStatus: ["pending", "approved", "rejected"],
            configurationParameterDataType: [
                "text",
                "numeric",
                "boolean",
                "list",
                "date",
                "material",
            ],
            costLedgerType: [
                "Direct Cost",
                "Revaluation",
                "Rounding",
                "Indirect Cost",
                "Variance",
                "Total",
            ],
            deadlineType: ["No Deadline", "ASAP", "Soft Deadline", "Hard Deadline"],
            demandForecastSourceType: [
                "Job Material",
                "Sales Order",
                "Demand Projection",
            ],
            demandSourceType: ["Sales Order", "Job Material"],
            depreciationMethod: [
                "Straight Line",
                "Declining Balance",
                "Units of Production",
            ],
            dimensionEntityType: [
                "Custom",
                "Location",
                "ItemPostingGroup",
                "SupplierType",
                "CustomerType",
                "Department",
                "Employee",
                "CostCenter",
                "WorkCenter",
                "Process",
                "FixedAssetClass",
            ],
            disposalMethod: ["Sale", "Scrapping"],
            disposition: [
                "Conditional Acceptance",
                "Deviation Accepted",
                "Hold",
                "No Action Required",
                "Pending",
                "Quarantine",
                "Repair",
                "Return to Supplier",
                "Rework",
                "Scrap",
                "Use As Is",
            ],
            documentSourceType: [
                "Job",
                "Part",
                "Purchase Order",
                "Purchase Invoice",
                "Purchase Return Order",
                "Quote",
                "Receipt",
                "Request for Quote",
                "Sales Order",
                "Sales Invoice",
                "Sales Return Order",
                "Service",
                "Shipment",
                "Material",
                "Tool",
                "Fixture",
                "Consumable",
                "Issue",
                "Gauge Calibration Record",
                "Purchasing Request for Quote",
                "Supplier Quote",
            ],
            documentthreadtype: [
                "nonConformance",
                "quote",
                "salesOrder",
                "job",
                "purchaseOrder",
                "invoice",
                "receipt",
                "shipment",
            ],
            documentTransactionType: [
                "Download",
                "Edit",
                "Favorite",
                "Label",
                "Unfavorite",
                "Upload",
            ],
            documentType: [
                "Archive",
                "Document",
                "Presentation",
                "PDF",
                "Spreadsheet",
                "Text",
                "Image",
                "Video",
                "Audio",
                "Other",
                "Model",
            ],
            employeeTypeSystemType: ["Admin", "Console Operator"],
            externalLinkDocumentType: [
                "Quote",
                "SupplierQuote",
                "Customer",
                "Non-Conformance Supplier",
            ],
            factor: [
                "Hours/Piece",
                "Hours/100 Pieces",
                "Hours/1000 Pieces",
                "Minutes/Piece",
                "Minutes/100 Pieces",
                "Minutes/1000 Pieces",
                "Pieces/Hour",
                "Pieces/Minute",
                "Seconds/Piece",
                "Total Hours",
                "Total Minutes",
            ],
            fixedAssetStatus: ["Draft", "Active", "Fully Depreciated", "Disposed"],
            fulfillmentType: ["Inventory", "Job"],
            gaugeCalibrationStatus: [
                "Pending",
                "In-Calibration",
                "Out-of-Calibration",
            ],
            gaugeRole: ["Master", "Standard"],
            gaugeStatus: ["Active", "Inactive"],
            glAccountClass: ["Asset", "Liability", "Equity", "Revenue", "Expense"],
            glConsolidatedRate: ["Average", "Current", "Historical"],
            glIncomeBalance: ["Balance Sheet", "Income Statement"],
            inboundInspectionSampleStatus: ["Pending", "Passed", "Failed"],
            inboundInspectionStatus: [
                "Pending",
                "In Progress",
                "Passed",
                "Failed",
                "Partial",
            ],
            incoterm: [
                "EXW",
                "FCA",
                "FAS",
                "FOB",
                "CPT",
                "CIP",
                "CFR",
                "CIF",
                "DAP",
                "DPU",
                "DDP",
            ],
            inspectionLevel: ["I", "II", "III", "S1", "S2", "S3", "S4"],
            inspectionSeverity: ["Normal", "Tightened", "Reduced"],
            inspectionStatus: ["Pass", "Fail"],
            itemCostingMethod: ["Standard", "Average", "LIFO", "FIFO"],
            itemLedgerDocumentType: [
                "Sales Shipment",
                "Sales Invoice",
                "Sales Return Receipt",
                "Sales Credit Memo",
                "Purchase Receipt",
                "Purchase Invoice",
                "Purchase Return Shipment",
                "Purchase Credit Memo",
                "Transfer Shipment",
                "Transfer Receipt",
                "Service Shipment",
                "Service Invoice",
                "Service Credit Memo",
                "Posted Assembly",
                "Inventory Receipt",
                "Inventory Shipment",
                "Direct Transfer",
                "Job Consumption",
                "Job Receipt",
                "Batch Split",
                "Purchase Order",
                "Maintenance Consumption",
                "Non-Conformance",
                "Inbound Inspection",
            ],
            itemLedgerType: [
                "Purchase",
                "Sale",
                "Positive Adjmt.",
                "Negative Adjmt.",
                "Transfer",
                "Consumption",
                "Output",
                "Assembly Consumption",
                "Assembly Output",
            ],
            itemReorderingPolicy: [
                "Manual Reorder",
                "Demand-Based Reorder",
                "Fixed Reorder Quantity",
                "Maximum Quantity",
            ],
            itemReplenishmentSystem: ["Buy", "Make", "Buy and Make"],
            itemTrackingSourceDocument: [
                "Receipt",
                "Job Production",
                "Job Material",
                "Shipment",
            ],
            itemTrackingType: ["Inventory", "Non-Inventory", "Serial", "Batch"],
            itemType: [
                "Part",
                "Material",
                "Tool",
                "Service",
                "Consumable",
                "Fixture",
            ],
            jobOperationStatus: [
                "Canceled",
                "Done",
                "In Progress",
                "Paused",
                "Ready",
                "Todo",
                "Waiting",
            ],
            jobStatus: [
                "Draft",
                "Ready",
                "In Progress",
                "Paused",
                "Completed",
                "Cancelled",
                "Overdue",
                "Due Today",
                "Planned",
                "Closed",
            ],
            journalEntrySourceType: [
                "Manual",
                "Purchase Receipt",
                "Purchase Invoice",
                "Purchase Return",
                "Sales Invoice",
                "Sales Shipment",
                "Sales Return",
                "Transfer Receipt",
                "Inventory Adjustment",
                "Production Order",
                "Job Consumption",
                "Job Receipt",
                "Production Event",
                "Job Close",
                "Asset Depreciation",
                "Asset Disposal",
            ],
            journalEntryStatus: ["Draft", "Posted", "Reversed"],
            journalLineDocumentType: [
                "Receipt",
                "Invoice",
                "Credit Memo",
                "Blanket Order",
                "Return Order",
                "Sales Shipment",
                "Transfer Shipment",
                "Purchase Receipt",
                "Purchase Invoice",
                "Job Consumption",
                "Job Receipt",
                "Batch Split",
                "Maintenance Consumption",
                "Production Event",
                "Job Close",
            ],
            kanbanOutput: ["label", "qrcode", "url"],
            macrsConvention: ["Half-Year", "Mid-Quarter"],
            macrsPropertyClass: ["3", "5", "7", "10", "15", "20", "27.5", "39"],
            maintenanceDispatchPriority: ["Low", "Medium", "High", "Critical"],
            maintenanceDispatchStatus: [
                "Open",
                "Assigned",
                "In Progress",
                "Completed",
                "Cancelled",
            ],
            maintenanceFailureModeType: [
                "Maintenance",
                "Quality",
                "Operations",
                "Other",
            ],
            maintenanceFrequency: [
                "Daily",
                "Weekly",
                "Monthly",
                "Quarterly",
                "Annual",
            ],
            maintenanceSeverity: [
                "Preventive",
                "Operator Performed",
                "Support Required",
                "OEM Required",
            ],
            maintenanceSource: ["Scheduled", "Reactive", "Non-Conformance"],
            makeMethodStatus: ["Draft", "Active", "Archived"],
            methodOperationOrder: ["After Previous", "With Previous"],
            methodType: ["Purchase to Order", "Pull from Inventory", "Make to Order"],
            module: [
                "Accounting",
                "Documents",
                "Invoicing",
                "Inventory",
                "Items",
                "Messaging",
                "Parts",
                "People",
                "Production",
                "Purchasing",
                "Resources",
                "Sales",
                "Settings",
                "Users",
                "Quality",
                "Printing",
            ],
            month: [
                "January",
                "February",
                "March",
                "April",
                "May",
                "June",
                "July",
                "August",
                "September",
                "October",
                "November",
                "December",
            ],
            nonConformanceApproval: ["MRB"],
            nonConformancePriority: ["Low", "Medium", "High", "Critical"],
            nonConformanceSource: ["Internal", "External"],
            nonConformanceStatus: ["Registered", "In Progress", "Closed"],
            nonConformanceSystemActionType: [
                "Containment",
                "Corrective",
                "Preventive",
                "Verification",
                "Communication",
            ],
            nonConformanceTaskStatus: [
                "Pending",
                "In Progress",
                "Completed",
                "Skipped",
            ],
            oeeImpact: ["Down", "Planned", "Impact", "No Impact"],
            operationType: ["Inside", "Outside", "Inside and Outside"],
            payableLineType: [
                "Comment",
                "G/L Account",
                "Fixed Asset",
                "Part",
                "Material",
                "Tool",
                "Service",
                "Consumable",
                "Fixture",
            ],
            paymentTermCalculationMethod: ["Net", "End of Month", "Day of Month"],
            periodType: ["Week", "Day", "Month"],
            pickingListLineStatus: ["Pending", "Picked", "Short", "Cancelled"],
            pickingListStatus: ["Draft", "In Progress", "Completed", "Cancelled"],
            pickMethodSortMethod: ["Default", "FEFO", "FIFO", "LIFO"],
            pricingRuleAmountType: ["Percentage", "Fixed"],
            pricingRuleType: ["Discount", "Markup"],
            procedureStatus: ["Draft", "Active", "Archived"],
            procedureStepType: [
                "Value",
                "Measurement",
                "Checkbox",
                "Timestamp",
                "Person",
                "List",
                "File",
                "Task",
                "Inspection",
            ],
            processType: ["Inside", "Outside", "Inside and Outside"],
            productionEventType: ["Setup", "Labor", "Machine"],
            productionQuantityType: ["Rework", "Scrap", "Production"],
            purchaseInvoiceStatus: [
                "Draft",
                "Pending",
                "Open",
                "Return",
                "Debit Note Issued",
                "Paid",
                "Partially Paid",
                "Overdue",
                "Voided",
            ],
            purchaseOrderLineType: [
                "Comment",
                "G/L Account",
                "Fixed Asset",
                "Part",
                "Material",
                "Tool",
                "Service",
                "Consumable",
                "Fixture",
            ],
            purchaseOrderStatus: [
                "Draft",
                "To Review",
                "Rejected",
                "To Receive",
                "To Receive and Invoice",
                "To Invoice",
                "Completed",
                "Closed",
                "Planned",
                "Needs Approval",
            ],
            purchaseOrderTransactionType: [
                "Edit",
                "Favorite",
                "Unfavorite",
                "Approved",
                "Reject",
                "Request Approval",
            ],
            purchaseOrderType: ["Purchase", "Return", "Outside Processing"],
            purchasePriceUpdateTiming: [
                "Purchase Invoice Post",
                "Purchase Order Finalize",
            ],
            purchasingRfqStatus: ["Draft", "Requested", "Closed"],
            qualityDocumentStatus: ["Draft", "Active", "Archived"],
            quoteLineStatus: ["Not Started", "In Progress", "Complete", "No Quote"],
            quoteStatus: [
                "Draft",
                "Sent",
                "Ordered",
                "Partial",
                "Lost",
                "Cancelled",
                "Expired",
            ],
            receiptSourceDocument: [
                "Sales Order",
                "Sales Invoice",
                "Sales Return Order",
                "Purchase Order",
                "Purchase Invoice",
                "Purchase Return Order",
                "Inbound Transfer",
                "Outbound Transfer",
                "Manufacturing Consumption",
                "Manufacturing Output",
            ],
            receiptStatus: ["Draft", "Pending", "Posted", "Voided"],
            riskRegisterType: ["Risk", "Opportunity"],
            riskSource: [
                "Customer",
                "General",
                "Item",
                "Job",
                "Quote Line",
                "Supplier",
                "Work Center",
            ],
            riskStatus: ["Open", "In Review", "Mitigating", "Closed", "Accepted"],
            role: ["customer", "employee", "supplier"],
            salesInvoiceLineType: [
                "Comment",
                "Part",
                "Material",
                "Tool",
                "Service",
                "Consumable",
                "Fixture",
                "Fixed Asset",
            ],
            salesInvoiceStatus: [
                "Draft",
                "Pending",
                "Submitted",
                "Return",
                "Credit Note Issued",
                "Paid",
                "Partially Paid",
                "Overdue",
                "Voided",
            ],
            salesOrderLineStatus: ["Ordered", "In Progress", "Completed"],
            salesOrderLineType: [
                "Comment",
                "Part",
                "Material",
                "Tool",
                "Service",
                "Consumable",
                "Fixture",
                "Fixed Asset",
            ],
            salesOrderStatus: [
                "Draft",
                "Needs Approval",
                "Confirmed",
                "In Progress",
                "Completed",
                "Invoiced",
                "Cancelled",
                "Closed",
                "To Ship and Invoice",
                "To Ship",
                "To Invoice",
            ],
            salesOrderTransactionType: [
                "Edit",
                "Favorite",
                "Unfavorite",
                "Approved",
                "Reject",
                "Request Approval",
            ],
            salesRfqStatus: ["Draft", "Ready for Quote", "Closed", "Quoted"],
            samplingPlanType: ["All", "First", "Percentage", "AQL"],
            samplingStandard: ["ANSI_Z1_4", "ISO_2859_1"],
            serviceType: ["Internal", "External"],
            shelfLifeMode: ["Fixed Duration", "Calculated", "Set on Receipt"],
            shelfLifeTriggerTiming: ["Before", "After"],
            shipmentSourceDocument: [
                "Sales Order",
                "Sales Invoice",
                "Sales Return Order",
                "Purchase Order",
                "Purchase Invoice",
                "Purchase Return Order",
                "Inbound Transfer",
                "Outbound Transfer",
            ],
            shipmentStatus: ["Draft", "Pending", "Posted", "Voided"],
            shippingCarrier: ["UPS", "FedEx", "USPS", "DHL", "Other"],
            sourcingType: ["Specified", "Drop Ship", "Ship from Inventory"],
            stockTransferStatus: ["Draft", "Released", "In Progress", "Completed"],
            storageRuleTargetType: ["item", "workCenter"],
            supplierLedgerDocumentType: [
                "Payment",
                "Invoice",
                "Credit Memo",
                "Finance Charge Memo",
                "Reminder",
                "Refund",
            ],
            supplierPartPriceSourceType: ["Quote", "Purchase Order", "Manual Entry"],
            supplierQuoteStatus: [
                "Active",
                "Expired",
                "Draft",
                "Declined",
                "Cancelled",
            ],
            supplierStatusType: ["Active", "Inactive", "Pending", "Rejected"],
            supplySourceType: ["Purchase Order", "Production Order"],
            tableViewType: ["Public", "Private"],
            taxDepreciationMethod: ["Straight Line", "Declining Balance", "MACRS"],
            taxExemptionReason: [
                "Resale",
                "Government",
                "Nonprofit",
                "Agriculture",
                "Industrial",
                "Export",
                "Medical",
                "Educational",
                "Religious",
                "Other",
            ],
            trackedEntityStatus: [
                "Available",
                "Reserved",
                "On Hold",
                "Consumed",
                "Rejected",
            ],
            trackingSource: ["Purchased", "Manufactured"],
            trainingFrequency: ["Once", "Quarterly", "Annual"],
            trainingQuestionType: [
                "MultipleChoice",
                "TrueFalse",
                "MultipleAnswers",
                "MatchingPairs",
                "Numerical",
            ],
            trainingStatus: ["Draft", "Active", "Archived"],
            trainingType: ["Mandatory", "Optional"],
            transactionSurface: [
                "receipt",
                "shipment",
                "stockTransfer",
                "warehouseTransfer",
                "inventoryAdjustment",
                "place",
                "pick",
                "operationStart",
                "operationFinish",
                "materialIssue",
                "materialReceive",
            ],
            warehouseTransferStatus: [
                "Draft",
                "To Ship and Receive",
                "To Ship",
                "To Receive",
                "Completed",
                "Cancelled",
            ],
        },
    },
    storage: {
        Enums: {
            buckettype: ["STANDARD", "ANALYTICS", "VECTOR"],
        },
    },
};
