"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.renderEnv = renderEnv;
exports.writeEnv = writeEnv;
exports.syncAppPortlessConfigs = syncAppPortlessConfigs;
var node_fs_1 = require("node:fs");
var pathe_1 = require("pathe");
var constants_js_1 = require("./constants.js");
var worktree_js_1 = require("./worktree.js");
function renderEnv(opts) {
    var slug = opts.slug, ports = opts.ports, redisDb = opts.redisDb, jwt = opts.jwt, portless = opts.portless, branchPrefix = opts.branchPrefix;
    var host = function (sub) { return "".concat(sub, ".").concat(branchPrefix, ".dev"); };
    var local = function (port) { return "http://localhost:".concat(port); };
    var lines = [];
    lines.push("# Generated by crbn. Do not edit by hand.");
    lines.push("# Vite/React Router auto-load this file alongside .env;");
    lines.push("# values here override .env. The user's .env is left untouched.");
    lines.push("");
    lines.push("CARBON_WORKTREE=".concat(slug));
    if (portless)
        lines.push("PORTLESS_TLD=dev");
    lines.push("");
    lines.push("# Internal compose ports (apps do not read these directly)");
    for (var _i = 0, _a = Object.entries(ports); _i < _a.length; _i++) {
        var _b = _a[_i], k = _b[0], v = _b[1];
        lines.push("".concat(k, "=").concat(v));
    }
    lines.push("");
    lines.push(portless
        ? "# App-facing URLs (portless hostnames)"
        : "# App-facing URLs (localhost)");
    lines.push("DOMAIN=".concat(portless ? "".concat(branchPrefix, ".dev") : "localhost"));
    lines.push("ERP_URL=".concat(portless ? "https://".concat(host("erp")) : local(ports.PORT_ERP)));
    lines.push("MES_URL=".concat(portless ? "https://".concat(host("mes")) : local(ports.PORT_MES)));
    lines.push("VERCEL_URL=".concat(portless ? "https://".concat(host("erp")) : local(ports.PORT_ERP)));
    if (portless)
        lines.push("GTM_URL=https://".concat(host("starter")));
    lines.push("");
    lines.push("# Supabase (per-worktree dev keys, minted from random JWT_SECRET)");
    lines.push("SUPABASE_URL=".concat(portless ? "https://".concat(host("api")) : local(ports.PORT_API)));
    lines.push("SUPABASE_DB_URL=postgresql://postgres:postgres@localhost:".concat(ports.PORT_DB, "/postgres"));
    lines.push("PGSSLMODE=disable");
    lines.push("SUPABASE_JWT_SECRET=".concat(jwt.secret));
    lines.push("SUPABASE_ANON_KEY=".concat(jwt.anonKey));
    lines.push("SUPABASE_SERVICE_ROLE_KEY=".concat(jwt.serviceKey));
    // OAuth callback: portless uses the shared api.carbon.dev alias; localhost
    // mode uses the well-known Supabase default port so the redirect URI is
    // predictable and can be registered in Google/Azure console once.
    var oauthBase = portless
        ? "https://api.carbon.dev"
        : "http://localhost:54321";
    lines.push("SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI=".concat(oauthBase, "/auth/v1/callback"));
    lines.push("SUPABASE_AUTH_EXTERNAL_AZURE_REDIRECT_URI=".concat(oauthBase, "/auth/v1/callback"));
    lines.push("");
    lines.push("# Aux services");
    lines.push("REDIS_URL=redis://localhost:".concat(worktree_js_1.SHARED_REDIS_PORT, "/").concat(redisDb));
    lines.push("INNGEST_DEV=1");
    lines.push("INNGEST_BASE_URL=http://localhost:".concat(ports.PORT_INNGEST));
    // SDK advertises this as its serve URL during self-register. Must be
    // reachable from inside the inngest container (handled via extra_hosts +
    // portless CA mount in docker-compose.dev.yml).
    lines.push("INNGEST_SERVE_HOST=".concat(portless ? "https://".concat(host("erp")) : local(ports.PORT_ERP)));
    // Hostname (no scheme) that docker-compose maps to host-gateway inside the
    // inngest container, so the SDK URL above resolves to the dev server on the
    // host. extra_hosts only accepts fully-qualified names — no wildcards —
    // which is why we can't reuse ${DOMAIN} (e.g. `main.dev` won't match the
    // `erp.main.dev` host the SDK URL points at).
    lines.push("INNGEST_TLS_HOST=".concat(portless ? host("erp") : "localhost"));
    lines.push("");
    lines.push("# Dev auth bypass");
    lines.push("DEV_BYPASS_EMAIL=test@carbon.ms");
    lines.push("");
    return lines.join("\n");
}
function writeEnv(worktreeRoot, content) {
    (0, node_fs_1.writeFileSync)((0, pathe_1.join)(worktreeRoot, ".env.local"), content);
}
function syncAppPortlessConfigs(worktreeRoot) {
    for (var _i = 0, APP_CHOICES_1 = constants_js_1.APP_CHOICES; _i < APP_CHOICES_1.length; _i++) {
        var appId = APP_CHOICES_1[_i].value;
        var path = (0, pathe_1.join)(worktreeRoot, "apps", appId, "portless.json");
        if ((0, node_fs_1.existsSync)(path)) {
            (0, node_fs_1.unlinkSync)(path);
        }
    }
}
