import { existsSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "pathe";
import { APP_CHOICES } from "./constants.js";
import { type JwtCreds, type PortMap, SHARED_REDIS_PORT } from "./worktree.js";

export function renderEnv(opts: {
  slug: string;
  ports: PortMap;
  redisDb: number;
  jwt: JwtCreds;
  // Sanitized branch segment, e.g. `feat/boo` → `boo`, `main` → `main`.
  // Always non-empty — callers fall back to slug when branch is detached.
  branchPrefix: string;
}): string {
  const { slug, ports, redisDb, jwt, branchPrefix } = opts;
  const host = (sub: string) => `${branchPrefix}.${sub}.dev`;

  const lines: string[] = [];
  lines.push("# Generated by crbn. Do not edit by hand.");
  lines.push("# Vite/React Router auto-load this file alongside .env;");
  lines.push("# values here override .env. The user's .env is left untouched.");
  lines.push("");
  lines.push(`CARBON_WORKTREE=${slug}`);
  lines.push("PORTLESS_TLD=dev");
  lines.push("");
  lines.push("# Internal compose ports (apps do not read these directly)");
  for (const [k, v] of Object.entries(ports)) lines.push(`${k}=${v}`);
  lines.push("");
  lines.push("# App-facing URLs (portless hostnames)");
  lines.push(`DOMAIN=${host("erp")}`);
  lines.push(`ERP_URL=https://${host("erp")}`);
  lines.push(`MES_URL=https://${host("mes")}`);
  lines.push(`VERCEL_URL=https://${host("erp")}`);
  lines.push(`GTM_URL=https://${host("starter")}`);
  lines.push("");
  lines.push(
    "# Supabase (per-worktree dev keys, minted from random JWT_SECRET)"
  );
  lines.push(`SUPABASE_URL=https://${host("api")}`);
  lines.push(
    `SUPABASE_DB_URL=postgresql://postgres:postgres@localhost:${ports.PORT_DB}/postgres`
  );
  lines.push("PGSSLMODE=disable");
  lines.push(`SUPABASE_JWT_SECRET=${jwt.secret}`);
  lines.push(`SUPABASE_ANON_KEY=${jwt.anonKey}`);
  lines.push(`SUPABASE_SERVICE_ROLE_KEY=${jwt.serviceKey}`);
  // Branch-independent OAuth callback host (api.carbon.dev). Last `crbn up`
  // wins — registers `api.carbon` alias to its PORT_API.
  lines.push(
    `SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI=https://api.carbon.dev/auth/v1/callback`
  );
  lines.push(
    `SUPABASE_AUTH_EXTERNAL_AZURE_REDIRECT_URI=https://api.carbon.dev/auth/v1/callback`
  );
  lines.push("");
  lines.push("# Aux services");
  lines.push(`REDIS_URL=redis://localhost:${SHARED_REDIS_PORT}/${redisDb}`);
  lines.push("INNGEST_DEV=1");
  lines.push(`INNGEST_BASE_URL=http://localhost:${ports.PORT_INNGEST}`);
  lines.push("");
  return lines.join("\n");
}

export function writeEnv(worktreeRoot: string, content: string) {
  writeFileSync(join(worktreeRoot, ".env.local"), content);
}

// Stamp `apps/<id>/portless.json` so main-checkout gets `<prefix>.<app>.dev`
// too (portless auto-prefixes only in linked worktrees). Linked worktrees
// leave the file absent — stamping would double-prefix.
export function syncAppPortlessConfigs(opts: {
  worktreeRoot: string;
  branchPrefix: string | null;
  linked: boolean;
}) {
  const { worktreeRoot, branchPrefix, linked } = opts;
  for (const { value: appId } of APP_CHOICES) {
    const path = join(worktreeRoot, "apps", appId, "portless.json");
    const shouldStamp = !linked && branchPrefix !== null;
    if (shouldStamp) {
      writeFileSync(
        path,
        `${JSON.stringify({ name: `${branchPrefix}.${appId}` }, null, 2)}\n`
      );
    } else if (existsSync(path)) {
      unlinkSync(path);
    }
  }
}
