"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DepartmentsTreeView = exports.DepartmentsTable = exports.DepartmentsListView = exports.DepartmentForm = void 0;
var DepartmentForm_1 = require("./DepartmentForm");
exports.DepartmentForm = DepartmentForm_1.default;
var DepartmentsListView_1 = require("./DepartmentsListView");
Object.defineProperty(exports, "DepartmentsListView", { enumerable: true, get: function () { return DepartmentsListView_1.DepartmentsListView; } });
var DepartmentsTable_1 = require("./DepartmentsTable");
exports.DepartmentsTable = DepartmentsTable_1.default;
var DepartmentsTreeView_1 = require("./DepartmentsTreeView");
Object.defineProperty(exports, "DepartmentsTreeView", { enumerable: true, get: function () { return DepartmentsTreeView_1.DepartmentsTreeView; } });
