// Generates src/pdf/fonts.data.ts — the editor's body fonts as base64 woff data
// URIs from @fontsource/* (OFL/Apache), registered in-process with no network at
// render. Runs on the root postinstall + turbo build task; gitignored output.
//
// woff, NOT woff2: react-pdf preloads every registered font, and its fontkit's
// woff2/brotli decoder corrupts shared state across many decodes → DataView range
// errors at embed. woff (zlib) is stateless.
import { createRequire } from "node:module";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "src", "pdf", "fonts.data.ts");

// "latin" subset = Western European, keeps the bundle small. Mirrors the bundled
// fonts in DOCUMENT_FONTS (template/schema.ts).
const SUBSET = "latin";
const FAMILIES = [
  { family: "Inter", pkg: "@fontsource/inter", weights: [300, 400, 500, 700, 900] },
  { family: "Roboto", pkg: "@fontsource/roboto", weights: [400, 700] },
  { family: "Open Sans", pkg: "@fontsource/open-sans", weights: [400, 700] },
  { family: "Lato", pkg: "@fontsource/lato", weights: [400, 700] },
  { family: "Montserrat", pkg: "@fontsource/montserrat", weights: [400, 700] },
  { family: "Merriweather", pkg: "@fontsource/merriweather", weights: [400, 700] },
  { family: "Playfair Display", pkg: "@fontsource/playfair-display", weights: [400, 700] },
  { family: "Lora", pkg: "@fontsource/lora", weights: [400, 700] },
];

function filesDir(pkg) {
  // Probe install dirs via fs (which ignores the package's "exports" map, unlike
  // require.resolve), then fall back to require.
  const candidates = [
    join(here, "..", "node_modules", pkg, "files"),
    join(here, "..", "..", "..", "node_modules", pkg, "files"),
  ];
  for (const c of candidates) {
    if (existsSync(c)) return c;
  }
  const pkgJson = require.resolve(`${pkg}/package.json`);
  return join(dirname(pkgJson), "files");
}

function findWoff(dir, id, weight) {
  const exact = join(dir, `${id}-${SUBSET}-${weight}-normal.woff`);
  if (existsSync(exact)) return exact;
  const all = readdirSync(dir);
  const re = new RegExp(`^${id}-${SUBSET}.*-${weight}-normal\\.woff$`);
  const hit = all.find((f) => re.test(f)) ?? all.find((f) => f.includes(`-${SUBSET}-`) && f.endsWith(`-${weight}-normal.woff`));
  return hit ? join(dir, hit) : null;
}

const entries = [];
const warnings = [];
let totalBytes = 0;

for (const { family, pkg, weights } of FAMILIES) {
  let dir;
  try {
    dir = filesDir(pkg);
  } catch {
    warnings.push(`MISSING package ${pkg} — run pnpm install. Skipped ${family}.`);
    continue;
  }
  const fonts = [];
  for (const weight of weights) {
    const file = findWoff(dir, pkg.split("/")[1], weight);
    if (!file) {
      warnings.push(`No woff for ${family} ${weight} (${SUBSET}) in ${dir}`);
      continue;
    }
    const buf = readFileSync(file);
    totalBytes += buf.length;
    fonts.push({ src: `data:font/woff;base64,${buf.toString("base64")}`, fontWeight: weight });
  }
  if (fonts.length) entries.push({ family, fonts });
}

const body = entries
  .map(
    (e) =>
      `  {\n    family: ${JSON.stringify(e.family)},\n    fonts: [\n` +
      e.fonts
        .map((f) => `      { fontWeight: ${f.fontWeight}, src: ${JSON.stringify(f.src)} },`)
        .join("\n") +
      `\n    ],\n  },`
  )
  .join("\n");

const out = `// GENERATED by scripts/generate-fonts.mjs — DO NOT EDIT BY HAND.
// Run: pnpm --filter @carbon/documents build
// Document fonts embedded as base64 woff data URIs (decoded in-process by
// react-pdf/fontkit; no network at render).

export type BundledFont = {
  family: string;
  fonts: { fontWeight: number; src: string }[];
};

export const BUNDLED_FONTS: BundledFont[] = [
${body}
];
`;

writeFileSync(OUT, out);

for (const w of warnings) console.warn(`⚠️  ${w}`);
console.log(
  `✓ Wrote ${OUT}\n  ${entries.length} families, ${entries.reduce((n, e) => n + e.fonts.length, 0)} faces, ${(totalBytes / 1024).toFixed(0)} KiB raw woff (~${((totalBytes * 1.34) / 1024).toFixed(0)} KiB base64).`
);
