name: Deploy Migrations
on:
  push:
    branches: [main]
    paths: ["packages/database/supabase/**"]
  workflow_dispatch:

jobs:
  supabase:
    name: Supabase Sync
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID: ${{ secrets.SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_ID }}
      SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET: ${{ secrets.SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET }}
      SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI: ${{ secrets.SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI }}
      SUPABASE_AUTH_EXTERNAL_AZURE_CLIENT_ID: ${{ secrets.SUPABASE_AUTH_EXTERNAL_AZURE_CLIENT_ID }}
      SUPABASE_AUTH_EXTERNAL_AZURE_CLIENT_SECRET: ${{ secrets.SUPABASE_AUTH_EXTERNAL_AZURE_CLIENT_SECRET }}
      SUPABASE_AUTH_EXTERNAL_AZURE_REDIRECT_URI: ${{ secrets.SUPABASE_AUTH_EXTERNAL_AZURE_REDIRECT_URI }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run migrations
        run: pnpm --filter ci ci:migrations
